"""
GitHub Actions / GitLab CI workflow templates we push into source
repos on operator request (``pushCiWorkflow`` mutation).

The templates are inline strings rather than on-disk files so the
backend stays self-contained — no MANIFEST changes, no missing-file
flakiness in tests, no template hot-reload story to invent. When the
template surface grows past ~3 hosts we'll graduate to ``Jinja`` +
``astrolift_scm/templates/`` and the resolver will look up by host.

The GitHub Actions workflow follows three constraints:

* Triggers on ``push`` against the configured deploy branch(es). The
  workflow file only ever runs from the deploy branch itself, so the
  trigger is the source of truth for "when to deploy" — operators
  don't need a separate hook.
* Single job, no matrix. The Astrolift CLI talks to the platform; the
  platform is what dispatches the actual deploy workflow on Temporal.
  This file is "tell the platform a new SHA exists" — that's it.
* Auth via a repo secret named ``ASTROLIFT_DEPLOY_TOKEN``. The operator
  rotates by replacing the secret on the GitHub side; the workflow
  file doesn't change. ``astro app deploy`` reads the env var.
"""

from __future__ import annotations

import json

# ---- branches -------------------------------------------------------

_DEFAULT_BRANCHES = ("main", "master")


def _branch_list(deploy_branch: str | None) -> list[str]:
    """Render the ``push.branches`` list. An explicit deploy branch
    wins; absent that, we accept both ``main`` and ``master`` so the
    workflow fires on whichever convention the repo follows."""
    if deploy_branch and deploy_branch.strip():
        return [deploy_branch.strip()]
    return list(_DEFAULT_BRANCHES)


# ---- GitHub Actions -------------------------------------------------


def render_github_actions_deploy_yml(
    *,
    app_slug: str,
    deploy_branch: str | None,
) -> str:
    """Render the canonical ``.github/workflows/astrolift-deploy.yml``.

    YAML is hand-built (not generated through a library) because the
    file is small, the keys are stable, and operators will diff it
    against their existing CI config. Hand-built keeps the output
    readable for that diff."""
    branches = _branch_list(deploy_branch)
    branches_yaml = "[" + ", ".join(branches) + "]"
    # The slug goes inline; it's already validated against the
    # subdomain regex on the registry side, so quoting via JSON is
    # belt-and-suspenders — never bare-inject untrusted text into YAML.
    slug_literal = json.dumps(app_slug)
    return (
        "# Generated by Astrolift. Edit at your own risk; the wizard\n"
        "# regenerates this file when you re-push from /apps/<slug>.\n"
        "name: Astrolift deploy\n"
        "\n"
        "on:\n"
        "  push:\n"
        f"    branches: {branches_yaml}\n"
        "\n"
        "concurrency:\n"
        f"  group: astrolift-deploy-{app_slug}-${{{{ github.ref }}}}\n"
        "  cancel-in-progress: false\n"
        "\n"
        "jobs:\n"
        "  deploy:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - name: Install astro CLI\n"
        "        run: |\n"
        "          curl -fsSL https://get.astrolift.dev | sh\n"
        '          echo "$HOME/.astrolift/bin" >> "$GITHUB_PATH"\n'
        "      - name: Trigger Astrolift deploy\n"
        "        env:\n"
        "          ASTROLIFT_DEPLOY_TOKEN: ${{ secrets.ASTROLIFT_DEPLOY_TOKEN }}\n"
        "        run: |\n"
        f"          astro app deploy --app={slug_literal} --image-tag=${{{{ github.sha }}}}\n"
    )


# ---- GitLab CI ------------------------------------------------------


def render_gitlab_ci_deploy_yml(
    *,
    app_slug: str,
    deploy_branch: str | None,
) -> str:
    """Render the GitLab equivalent.

    GitLab's CI runs from a single ``.gitlab-ci.yml`` at the repo
    root; the ``only`` / ``rules`` constraint pins the job to the
    deploy branch. Operators with an existing ``.gitlab-ci.yml`` will
    want to include this file via ``include:`` rather than overwrite
    — that's a follow-up; this version assumes a fresh repo."""
    branches = _branch_list(deploy_branch)
    slug_literal = json.dumps(app_slug)
    rules = "\n".join(f"    - if: '$CI_COMMIT_REF_NAME == \"{b}\"'" for b in branches)
    return (
        "# Generated by Astrolift. Operators with an existing\n"
        "# .gitlab-ci.yml should `include:` this file instead of\n"
        "# overwriting their own pipeline.\n"
        "stages:\n"
        "  - deploy\n"
        "\n"
        "astrolift_deploy:\n"
        "  stage: deploy\n"
        "  image: ubuntu:24.04\n"
        "  rules:\n"
        f"{rules}\n"
        "  script:\n"
        "    - apt-get update && apt-get install -y curl ca-certificates\n"
        "    - curl -fsSL https://get.astrolift.dev | sh\n"
        '    - export PATH="$HOME/.astrolift/bin:$PATH"\n'
        f"    - astro app deploy --app={slug_literal} --image-tag=$CI_COMMIT_SHA\n"
        "  variables:\n"
        "    ASTROLIFT_DEPLOY_TOKEN: $ASTROLIFT_DEPLOY_TOKEN\n"
    )


# ---- dispatcher -----------------------------------------------------


def default_workflow_path_for(source_kind: str) -> str:
    """Conventional path for the workflow file the operator
    overrides per call."""
    if source_kind in {"github"}:
        return ".github/workflows/astrolift-deploy.yml"
    if source_kind in {"gitlab"}:
        return ".gitlab-ci.yml"
    raise ValueError(f"no default workflow path for source_kind={source_kind!r}")


def render_workflow_for(
    *,
    source_kind: str,
    app_slug: str,
    deploy_branch: str | None,
) -> str:
    """Pick the right template body for the app's source host."""
    if source_kind == "github":
        return render_github_actions_deploy_yml(
            app_slug=app_slug,
            deploy_branch=deploy_branch,
        )
    if source_kind == "gitlab":
        return render_gitlab_ci_deploy_yml(
            app_slug=app_slug,
            deploy_branch=deploy_branch,
        )
    raise ValueError(f"no CI template for source_kind={source_kind!r}")
