# Generated by Django 6.0.5 on 2026-05-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredapp',
            name='preview_screenshot_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
