# Generated by Django 6.0.5 on 2026-05-14 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0007_organizationallowlisteddomain'),
        ('astrolift_registry', '0004_registeredapp_cron_expression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredapp',
            name='approver_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_for_apps', to='astrolift_identity.team'),
        ),
        migrations.AddField(
            model_name='registeredapp',
            name='approver_users',
            field=models.ManyToManyField(blank=True, related_name='approver_for_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeredapp',
            name='cron_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeredapp',
            name='minimum_approvals',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registeredapp',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
    ]
