# Generated by Django 6.0.5 on 2026-05-16 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def _backfill_owner_rows(apps, schema_editor):
    """Materialize one ``AppTeamAccess(OWNER)`` per active
    ``(RegisteredApp, team)`` FK pair so the join table is the
    canonical answer to "which teams reach this app?" — the FK is
    just a pointer at one of those rows (the home/primary).

    Idempotent: existence check on the unique-active key before
    insert ensures re-running the migration against
    partially-backfilled data is safe."""

    AppTeamAccess = apps.get_model("astrolift_registry", "AppTeamAccess")
    RegisteredApp = apps.get_model("astrolift_registry", "RegisteredApp")

    for app in RegisteredApp.objects.filter(deleted_at__isnull=True).iterator():
        already_exists = AppTeamAccess.objects.filter(
            registered_app=app,
            team_id=app.team_id,
            deleted_at__isnull=True,
        ).exists()
        if already_exists:
            continue
        AppTeamAccess.objects.create(
            registered_app=app,
            team_id=app.team_id,
            access_level="owner",
        )


def _drop_owner_rows(apps, schema_editor):
    """Reverse: hard-delete any rows produced by the forward migration.

    We can't tell apart backfilled rows from user-created ones at
    revert time, so the safe reverse drops every row — the join table
    is metadata, not load-bearing user data, and reverting the
    migration would drop the model anyway.
    """

    AppTeamAccess = apps.get_model("astrolift_registry", "AppTeamAccess")
    AppTeamAccess.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_identity", "0008_resync_system_roles_cluster_manage"),
        ("astrolift_registry", "0005_approval_gate_and_cron_paused"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTeamAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("deployer", "Deployer"), ("owner", "Owner")],
                        default="deployer",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_accesses",
                        to="astrolift_registry.registeredapp",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_accesses",
                        to="astrolift_identity.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["registered_app"], name="apt_access_app_idx"),
                    models.Index(fields=["team"], name="apt_access_team_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("registered_app", "team"),
                        name="app_team_access_unique_active",
                    )
                ],
            },
        ),
        migrations.RunPython(_backfill_owner_rows, reverse_code=_drop_owner_rows),
    ]
