# Generated by Django 6.0.5 on 2026-05-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_registry', '0006_appteamaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredapp',
            name='last_resync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
