# Generated by Django 6.0.5 on 2026-05-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_registry", "0007_registeredapp_last_resync_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredapp",
            name="source_webhook_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="registeredapp",
            name="source_webhook_installed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
