# Generated by Django 6.0.5 on 2026-05-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_registry', '0013_registeredapp_apps_list_indexes'),
        ('astrolift_registry', '0013_registeredapp_secret_approval_policy'),
    ]

    operations = [
    ]
