# Generated by Django 6.0.5 on 2026-06-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_registry', '0025_workload_agent_variant_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredapp',
            name='build_args',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='registeredapp',
            name='build_context',
            field=models.CharField(blank=True, default='.', max_length=512),
        ),
        migrations.AddField(
            model_name='registeredapp',
            name='build_mode',
            field=models.CharField(choices=[('ci_pushed', 'Ci Pushed'), ('platform_build', 'Platform Build'), ('none', 'None')], default='ci_pushed', max_length=32),
        ),
        migrations.AddField(
            model_name='registeredapp',
            name='dockerfile_path',
            field=models.CharField(blank=True, default='Dockerfile', max_length=512),
        ),
    ]
