# Generated by Django 6.0.5 on 2026-06-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_registry', '0029_workload_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredapp',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('failed', 'Failed'), ('tearing_down', 'Tearing Down'), ('deregistered', 'Deregistered')], default='pending', max_length=32),
        ),
    ]
