# Generated by Django 6.0.5 on 2026-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_registry", "0032_registeredapp_ci_workflow_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredapp",
            name="ci_secrets_pushed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
