# Generated by Django 6.0.5 on 2026-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_registry', '0034_scope_repo_manifest_unique_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='run_mode',
            field=models.CharField(choices=[('once', 'Once'), ('loop', 'Loop'), ('schedule', 'Schedule'), ('trigger', 'Trigger'), ('persistent', 'Persistent')], default='once', max_length=16),
        ),
    ]
