# Generated by Django 6.0.5 on 2026-08-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_registry', '0036_registeredapp_manifest_bootstrap_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredapp',
            name='network_policy',
            field=models.JSONField(blank=True, default=dict, help_text='Per-app egress rules. Empty or {"enabled": false} emits no NetworkPolicy. Enabling it applies a deny-by-default posture: anything not listed here, not a bound managed service, and not DNS becomes unreachable from this app\'s pods.'),
        ),
    ]
