# Generated by Django 6.0.5 on 2026-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_registry', '0037_app_network_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredapp',
            name='dns_probe',
            field=models.JSONField(blank=True, default=dict, help_text='Cached hostname-resolution probe for the app doctor. Written by the scheduled prober; read by the doctor with its age.'),
        ),
    ]
