# Generated by Django 6.0.5 on 2026-09-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_registry', '0038_app_dns_probe'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredapp',
            name='cronjob_probe',
            field=models.JSONField(blank=True, default=dict, help_text='Cached cronjob-run probe for the app doctor. Written by the scheduled prober; read by the doctor with its age.'),
        ),
    ]
