# Generated by Django 6.0.5 on 2026-09-26 12:37

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_clusters", "0018_manageddomain_provision_zone_id"),
        ("astrolift_identity", "0034_resync_system_roles_stock_catalogue"),
        ("astrolift_lifecycle", "0037_devenvironment_data_file"),
        ("astrolift_registry", "0039_registeredapp_cronjob_probe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HostnameClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True
                    ),
                ),
                ("hostname", models.CharField(db_index=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostname_claims",
                        to="astrolift_lifecycle.appenvironment",
                    ),
                ),
                (
                    "managed_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostname_claims",
                        to="astrolift_clusters.manageddomain",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostname_claims",
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "registered_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostname_claims",
                        to="astrolift_registry.registeredapp",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostname_claims",
                        to="astrolift_registry.workload",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["registered_app"], name="hostname_claim_app_idx"),
                    models.Index(fields=["environment"], name="hostname_claim_env_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("managed_domain", "hostname"),
                        name="hostname_claim_unique_active_per_zone",
                    )
                ],
            },
        ),
    ]
