# Generated by Django 6.0.5 on 2026-05-31 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0017_userpreferences'),
        ('astrolift_pipelines', '0003_runner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='runner',
            name='runner_org_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='runner',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='runner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='runner',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='runner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runner',
            name='api_key_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='arch',
            field=models.CharField(choices=[('amd64', 'amd64 (x86_64)'), ('arm64', 'arm64 (Apple Silicon / Graviton)')], max_length=8),
        ),
        migrations.AlterField(
            model_name='runner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='current_job_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executing_runners', to='astrolift_pipelines.jobrun'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='runner',
            name='os',
            field=models.CharField(choices=[('linux', 'Linux'), ('macos', 'macOS'), ('windows', 'Windows')], max_length=16),
        ),
        migrations.AlterField(
            model_name='runner',
            name='registration_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='offline', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='runner',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'slug'), name='runner_slug_unique_per_org_active'),
        ),
    ]
