# Generated by Django 6.0.5 on 2026-08-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_pipelines', '0005_jobrun_log_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='commit_sha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
