# Generated by Django 6.0.5 on 2026-08-21 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_pipelines', '0006_pipelinerun_commit_sha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pipeline_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_definitions', to='astrolift_pipelines.pipelinerun'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('pipeline_run__isnull', True)), fields=('pipeline', 'job_id'), name='job_unique_shared_per_pipeline'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('pipeline_run__isnull', False)), fields=('pipeline_run', 'job_id'), name='job_unique_snapshot_per_run'),
        ),
    ]
