# Generated by Django 6.0.5 on 2026-08-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_pipelines', '0007_job_pipeline_run_job_job_unique_shared_per_pipeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='skip_secrets',
            field=models.BooleanField(default=False),
        ),
    ]
