# Generated by Django 6.0.5 on 2026-08-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_pipelines', '0008_pipelinerun_skip_secrets'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='definition_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='definition_schema_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
