# Generated by Django 6.0.5 on 2026-10-02 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_run_owners(apps, schema_editor):
    Pipeline = apps.get_model('astrolift_pipelines', 'Pipeline')
    Run = apps.get_model('astrolift_pipelines', 'PipelineRun')
    if Run._base_manager.values('pipeline_id', 'run_number').annotate(count=models.Count('pk')).filter(count__gt=1).exists():
        raise RuntimeError('Pipeline run identities collide; reconcile duplicate historical runs before this migration')
    for pipeline in Pipeline._base_manager.all().iterator():
        Run._base_manager.filter(pipeline_id=pipeline.pk).update(organization_id=pipeline.organization_id, registered_app_id=pipeline.registered_app_id, pipeline_version=pipeline.version)
    Run._base_manager.exclude(temporal_workflow_id='').update(dispatch_status='unknown')
    apps.get_model('astrolift_pipelines', 'JobRun')._base_manager.exclude(temporal_activity_id='').update(cleanup_status='unknown')
    # Backfilled foreign keys schedule deferred checks on PostgreSQL. Flush
    # them before adding constraints in this same atomic migration.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_identity", "0041_merge_agent_enforcement_scim_groups"),
        ("astrolift_pipelines", "0009_pipelinerun_definition_digest_and_more"),
        ("astrolift_registry", "0042_registeredapp_edge_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="cleanup_last_error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="cleanup_status",
            field=models.CharField(default="not_required", max_length=16),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="actor_key",
            field=models.CharField(blank=True, default="", max_length=96),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="cancellation_last_error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="cancellation_observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="cancellation_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="cancellation_status",
            field=models.CharField(default="not_requested", max_length=32),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="cleanup_status",
            field=models.CharField(default="unknown", max_length=16),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="dispatch_last_error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="dispatch_status",
            field=models.CharField(default="reserved", max_length=16),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="astrolift_identity.organization",
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="pipeline_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="registered_app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="astrolift_registry.registeredapp",
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="request_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="request_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="temporal_run_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.RunPython(backfill_run_owners, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="pipelinerun",
            constraint=models.UniqueConstraint(
                fields=("pipeline", "run_number"), name="pipeline_run_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinerun",
            constraint=models.UniqueConstraint(
                fields=("organization", "actor_key", "request_id"),
                name="pipeline_start_request_unique",
            ),
        ),
    ]
