# Generated by Django 6.0.5 on 2026-10-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_clusters", "0020_tenantcluster_edge_access_rules"),
        (
            "astrolift_pipelines",
            "0010_jobrun_cleanup_last_error_jobrun_cleanup_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="astrolift_clusters.tenantcluster",
            ),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="k8s_job_uid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="k8s_namespace",
            field=models.CharField(blank=True, default="", max_length=63),
        ),
    ]
