"""
Auto-generated by ``manage.py make_perms`` — do not edit by hand.

The dictionary below is the canonical permission catalog the role
engine consults. The source of truth is ``core.permissions.Permission``;
re-run ``make perms`` after modifying that enum.
"""

from __future__ import annotations

PERMISSIONS: dict[str, dict[str, str]] = {
    "admin.elevate": {"slug": "admin.elevate", "resource": "admin", "verb": "elevate"},
    "api_token.create": {"slug": "api_token.create", "resource": "api_token", "verb": "create"},
    "api_token.revoke": {"slug": "api_token.revoke", "resource": "api_token", "verb": "revoke"},
    "app.approve_deploy": {"slug": "app.approve_deploy", "resource": "app", "verb": "approve_deploy"},
    "app.create": {"slug": "app.create", "resource": "app", "verb": "create"},
    "app.delete": {"slug": "app.delete", "resource": "app", "verb": "delete"},
    "app.deploy": {"slug": "app.deploy", "resource": "app", "verb": "deploy"},
    "app.exec_pod": {"slug": "app.exec_pod", "resource": "app", "verb": "exec_pod"},
    "app.read": {"slug": "app.read", "resource": "app", "verb": "read"},
    "app.read_logs": {"slug": "app.read_logs", "resource": "app", "verb": "read_logs"},
    "app.read_metrics": {"slug": "app.read_metrics", "resource": "app", "verb": "read_metrics"},
    "app.rollback": {"slug": "app.rollback", "resource": "app", "verb": "rollback"},
    "app.transfer": {"slug": "app.transfer", "resource": "app", "verb": "transfer"},
    "app.update": {"slug": "app.update", "resource": "app", "verb": "update"},
    "audit_log.read": {"slug": "audit_log.read", "resource": "audit_log", "verb": "read"},
    "billing.read": {"slug": "billing.read", "resource": "billing", "verb": "read"},
    "billing.update": {"slug": "billing.update", "resource": "billing", "verb": "update"},
    "cluster.manage": {"slug": "cluster.manage", "resource": "cluster", "verb": "manage"},
    "cluster.register": {"slug": "cluster.register", "resource": "cluster", "verb": "register"},
    "cluster.unregister": {"slug": "cluster.unregister", "resource": "cluster", "verb": "unregister"},
    "cluster.update": {"slug": "cluster.update", "resource": "cluster", "verb": "update"},
    "deploy_token.create": {"slug": "deploy_token.create", "resource": "deploy_token", "verb": "create"},
    "deploy_token.revoke": {"slug": "deploy_token.revoke", "resource": "deploy_token", "verb": "revoke"},
    "deploy_token.rotate": {"slug": "deploy_token.rotate", "resource": "deploy_token", "verb": "rotate"},
    "managed_service.create": {
        "slug": "managed_service.create",
        "resource": "managed_service",
        "verb": "create",
    },
    "managed_service.destroy": {
        "slug": "managed_service.destroy",
        "resource": "managed_service",
        "verb": "destroy",
    },
    "managed_service.update": {
        "slug": "managed_service.update",
        "resource": "managed_service",
        "verb": "update",
    },
    "org.delete": {"slug": "org.delete", "resource": "org", "verb": "delete"},
    "org.manage_members": {"slug": "org.manage_members", "resource": "org", "verb": "manage_members"},
    "org.read": {"slug": "org.read", "resource": "org", "verb": "read"},
    "org.update": {"slug": "org.update", "resource": "org", "verb": "update"},
    "project.create": {"slug": "project.create", "resource": "project", "verb": "create"},
    "project.delete": {"slug": "project.delete", "resource": "project", "verb": "delete"},
    "project.read": {"slug": "project.read", "resource": "project", "verb": "read"},
    "project.update": {"slug": "project.update", "resource": "project", "verb": "update"},
    "provider_plugin.configure": {
        "slug": "provider_plugin.configure",
        "resource": "provider_plugin",
        "verb": "configure",
    },
    "provider_plugin.read": {"slug": "provider_plugin.read", "resource": "provider_plugin", "verb": "read"},
    "secret.list": {"slug": "secret.list", "resource": "secret", "verb": "list"},
    "secret.read": {"slug": "secret.read", "resource": "secret", "verb": "read"},
    "secret.write": {"slug": "secret.write", "resource": "secret", "verb": "write"},
    "team.create": {"slug": "team.create", "resource": "team", "verb": "create"},
    "team.delete": {"slug": "team.delete", "resource": "team", "verb": "delete"},
    "team.manage_members": {"slug": "team.manage_members", "resource": "team", "verb": "manage_members"},
    "team.read": {"slug": "team.read", "resource": "team", "verb": "read"},
    "team.update": {"slug": "team.update", "resource": "team", "verb": "update"},
    "webhook.create": {"slug": "webhook.create", "resource": "webhook", "verb": "create"},
    "webhook.delete": {"slug": "webhook.delete", "resource": "webhook", "verb": "delete"},
    "webhook.update": {"slug": "webhook.update", "resource": "webhook", "verb": "update"},
}
