"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 3.2.9.
For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import logging
import os
from pathlib import Path
from typing import overload

import django
import django.utils.encoding
import sentry_sdk

# patch https://stackoverflow.com/questions/70382084/import-error-force-text-from-django-utils-encoding
from corsheaders.defaults import default_headers
from django.core.cache import DEFAULT_CACHE_ALIAS
from django.core.exceptions import ImproperlyConfigured
from django.db import DEFAULT_DB_ALIAS
from django.utils.encoding import force_str
from dotenv import load_dotenv
from import_export.formats.base_formats import CSV, JSON, TSV, XLSX


def _strtobool(val: str) -> int:
    """Stand-in for the removed ``distutils.util.strtobool`` (gone in 3.12)."""
    val = val.lower()
    if val in ("y", "yes", "t", "true", "on", "1"):
        return 1
    if val in ("n", "no", "f", "false", "off", "0"):
        return 0
    raise ValueError(f"invalid truth value {val!r}")


def env_bool(name: str, default: bool = False) -> bool:
    val = env_str(name, str(default)) or str(default)
    return _strtobool(val) == 1


@overload
def env_str(name: str, default: str) -> str: ...


@overload  # noqa: E302
def env_str(name: str, default: None = None) -> str | None: ...


def env_str(name: str, default: str | None = None) -> str | None:
    return os.getenv(name, default)


logger = logging.getLogger(__name__)

VERSION = "0.1.0"
logger.warning(f"Settings Version - Start: {VERSION}")

django.utils.encoding.force_text = force_str  # type: ignore[attr-defined]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DOTENV_FILE = env_str("DOTENV", os.path.join(BASE_DIR, "config/local.env"))

if os.path.exists(DOTENV_FILE):
    logger.warning(f"Loading environment from DOTENV={DOTENV_FILE}")
    load_dotenv(DOTENV_FILE)
else:
    logger.warning(f"DOTENV - No environment file found at DOTENV={DOTENV_FILE}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

# Read once, up front: the developer configuration further down (and the
# #1715 engine guard below it) key off this rather than the
# DJANGO_CONFIGURATION label, because a label can be left unset and quietly
# resolve to the permissive default -- a boolean env var cannot silently mean
# the opposite of the default it was given (#1732).
DEBUG = env_bool("DJANGO_DEBUG", False)
DEFAULT_USER_TEST = env_str(
    "DJANGO_DEFAULT_USER_TEST", "admin"
)  # only for local login the user if there is no user logged in

# The default user to execute automatic system operations. i.e. scheduled tasks, automatic signatures...
# The default set of permissions available for the system user(s). For instance, the permission to sign documents.
FRONTEND_URL = env_str("FRONTEND_URL", "http://localhost:3000")
# Public base URL the platform's REST API answers at — surfaced to
# operators on the Settings page (#382) as the value to wire into
# ``ASTROLIFT_API_URL`` on the CI side so the deploy webhook hits the
# right install. Falls back to FRONTEND_URL for local dev where the
# Next.js proxy fronts the Django API at the same origin.
PLATFORM_API_URL = env_str("PLATFORM_API_URL", FRONTEND_URL)
# Optional because installs that use only the built-in K8s dispatch path do
# not need an external dispatcher.  The registration endpoint fails closed
# while this is empty; operators must explicitly provision a bootstrap token
# before onboarding a Dispatch Service.
DISPATCHER_BOOTSTRAP_TOKEN = env_str("DISPATCHER_BOOTSTRAP_TOKEN", "")
# Compute bounds for every agent task and agent box container (#1848).
AGENT_POD_CPU_REQUEST = env_str("AGENT_POD_CPU_REQUEST", "250m")
AGENT_POD_CPU_LIMIT = env_str("AGENT_POD_CPU_LIMIT", "4")
AGENT_POD_MEMORY_REQUEST = env_str("AGENT_POD_MEMORY_REQUEST", "512Mi")
AGENT_POD_MEMORY_LIMIT = env_str("AGENT_POD_MEMORY_LIMIT", "8Gi")
API_SYSTEM_USER = env_str("API_SYSTEM_USER", "system")
API_SYSTEM_PERMISSION_GROUP = env_str("API_SYSTEM_PERMISSION_GROUP", "astrolift_automatic_system_operations")

# Django
SECRET_KEY = env_str("DJANGO_SECRET_KEY", "not-a-secret")
ROOT_URLCONF = env_str("DJANGO_ROOT_URLCONF", "config.urls")
BASE_URL = env_str("DJANGO_BASE_URL", "app/")
LOGIN_URL = env_str("DJANGO_LOGIN_URL", "/auth/login")
LOGIN_REDIRECT_URL = env_str("DJANGO_LOGIN_REDIRECT_URL", f"/{BASE_URL}admin/")
SWITCHED_FROM_USER = "switched_from_user"

CORS_ALLOW_CREDENTIALS = env_bool("DJANGO_CORS_ALLOW_CREDENTIALS", True)
# Credentialed CORS is limited to the frontend origin(s), never every
# origin: apps and previews can run user code on a host that is same-site
# with the control plane, and a blanket allow would let that code drive
# GraphQL as whoever is signed in (#1926). Not env-switchable on purpose.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    value.strip().rstrip("/")
    for value in env_str("DJANGO_CORS_ALLOWED_ORIGINS", FRONTEND_URL).split(",")
    if value.strip()
]
CORS_ALLOW_HEADERS = default_headers + (
    "sentry-trace",
    "baggage",
    "x-platform",
    "last-event-id",
    "mcp-protocol-version",
    "mcp-session-id",
)
CORS_EXPOSE_HEADERS = ("MCP-Protocol-Version", "Mcp-Session-Id")
MCP_ALLOWED_ORIGINS = tuple(
    value.strip()
    for value in env_str("ASTROLIFT_MCP_ALLOWED_ORIGINS", FRONTEND_URL).split(",")
    if value.strip()
)
MCP_SESSION_TTL_SECONDS = int(env_str("ASTROLIFT_MCP_SESSION_TTL_SECONDS", "3600"))
MCP_MAX_REQUEST_BYTES = int(env_str("ASTROLIFT_MCP_MAX_REQUEST_BYTES", str(2 * 1024 * 1024)))
CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_ADDITIONAL_FIELDS = {
    # uid/gid 0 is root, which runAsNonRoot refuses.
    "posix_id": ["django.forms.IntegerField", {"min_value": 1, "max_value": 2147483647}],
}
CONSTANCE_DATABASE_CACHE_BACKEND = "default"

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

LANGUAGE_CODE = env_str("DJANGO_LANGUAGE_CODE", "en")
TIME_ZONE = env_str("DJANGO_TIME_ZONE", "UTC")
SYSTEM_TIME_ZONE = env_str("SYSTEM_TIME_ZONE", "UTC")
USE_I18N = env_bool("DJANGO_USE_I18N", True)
USE_L10N = env_bool("DJANGO_USE_L10N", True)
USE_TZ = env_bool("DJANGO_USE_TZ", True)

LANGUAGES = [
    ("en", "English"),
    ("es", "Spanish"),
]

CONFIGURATION = env_str(
    "DJANGO_CONFIGURATION",
)

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = env_str("DJANGO_STATIC_URL", "/static/")

# Google
GOOGLE_API_KEY = env_str("DJANGO_GOOGLE_API_KEY")
# DEFAULT_FILE_STORAGE = env_str('DJANGO_', )
GS_BUCKET_NAME = env_str("DJANGO_GS_BUCKET_NAME")
GS_DIR = env_str("DJANGO_GS_DIR")

GOOGLE_APPLICATION_CREDENTIALS = env_str("GOOGLE_APPLICATION_CREDENTIALS")
GOOGLE_MAPS_API_KEY = env_str("GOOGLE_MAPS_API_KEY")

ROCKETCHAT_URL = env_str("ROCKETCHAT_URL", "")
ROCKETCHAT_API_USER_ID = env_str("ROCKETCHAT_API_USER_ID", "")
ROCKETCHAT_API_AUTH_TOKEN = env_str("ROCKETCHAT_API_AUTH_TOKEN", "")

# Load Auth0 application settings into memory
AUTH0_DOMAIN = os.environ.get("AUTH0_DOMAIN")
AUTH0_CLIENT_ID = os.environ.get("AUTH0_CLIENT_ID")
AUTH0_CLIENT_SECRET = os.environ.get("AUTH0_CLIENT_SECRET")
AUTH0_CLIENT_SCOPES = os.environ.get(
    "AUTH0_CLIENT_SCOPES", "openid profile email read:users create:users update:users"
)
# OIDC discovery URL override. On Auth0 the discovery doc lives at the same
# host as the login UI, so AUTH0_DOMAIN is enough — `https://<domain>/.well-known/openid-configuration`
# is correct. Other OIDC providers (notably AWS Cognito) split the two:
# the hosted-UI domain serves /oauth2/authorize and /logout, but the
# discovery doc lives at `cognito-idp.<region>.amazonaws.com/<pool-id>`.
# When set, AUTH0_SERVER_METADATA_URL overrides the constructed default
# without disturbing the login/logout flow that still uses AUTH0_DOMAIN.
AUTH0_SERVER_METADATA_URL = os.environ.get("AUTH0_SERVER_METADATA_URL")
logger.warning(
    f"[Auth0] AUTH0_DOMAIN={AUTH0_DOMAIN!r} AUTH0_SERVER_METADATA_URL={AUTH0_SERVER_METADATA_URL!r}"
)
AUTH0_DATABASE_CONNECTION_ID = os.environ.get(
    "AUTH0_DATABASE_CONNECTION_ID", "Username-Password-Authentication"
)
CLIENT_SESSION_API_KEY = os.environ.get("CLIENT_SESSION_API_KEY")

# EMail Configuration
AWS_SES_REGION_NAME = os.environ.get("AWS_SES_REGION_NAME", "us-west-2")
AWS_SES_REGION_ENDPOINT = os.environ.get("AWS_SES_REGION_ENDPOINT", "email.us-west-2.amazonaws.com")
EMAIL_BACKEND = env_str("DJANGO_EMAIL_BACKEND", "django_ses.SESBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 25))
FROM_EMAIL = os.environ.get("FROM_EMAIL", "no-reply@example.com")

# SES → SNS event publishing (#756). When set, the AmazonSES driver
# wires a ``CreateConfigurationSetEventDestination`` with this topic ARN
# at provision time, and the SNS webhook receiver at
# ``/app/webhooks/ses-events/`` will accept SubscriptionConfirmation
# and Notification POSTs from the same topic. Empty (the default)
# leaves event publishing disabled — the platform still provisions
# SES identities, but no per-message log accrues. The opscode module
# that creates the topic + subscribes the webhook lives in
# ``astrolift-opscode``; this var carries the ARN it returns.
SES_EVENTS_SNS_TOPIC_ARN = env_str("ASTROLIFT_SES_EVENTS_SNS_TOPIC_ARN", "")

# Public URL the frontend is reachable at — used to build absolute
# links inside outbound mail (invitation accept URLs, etc.) AND to
# embed the public webhook URL in the GitHub App manifest. Default
# is empty so the GitHub-manifest start view can fall back to
# request.build_absolute_uri() in dev. Production installs MUST set
# APP_BASE_URL explicitly — otherwise GitHub rejects the manifest with
# "Hook url is not supported because it isn't reachable over the
# public Internet (localhost)".
APP_BASE_URL = os.environ.get("APP_BASE_URL", "").rstrip("/")

# GitHub-App connection reuse scope. Controls whether the "Connect
# GitHub" manifest flow mints a brand-new GitHub App on every connect
# or reuses an existing one so an install stops accumulating duplicate
# Apps (astrolift-<x>, <x>-astrolift, …).
#   per_org (default): one App per Astrolift org — the first connect in
#     an org creates the App, later connects in that org reuse it.
#   per_install: one App for the whole Astrolift install — the first org
#     to connect creates the App; every other org installs that same App
#     instead of creating a duplicate.
# Install-level config (not per-request), so a plain env-driven setting
# rather than a runtime constance flag. Unknown values normalise to
# per_org at read time (see auth1.scm_app_manifest._connection_scope).
GITHUB_APP_CONNECTION_SCOPE = env_str("GITHUB_APP_CONNECTION_SCOPE", "per_org")

# Mobile universal-link / app-link well-known manifest values (#541).
# The two strings below feed the JSON payload served at
# /.well-known/apple-app-site-association and /.well-known/assetlinks.json
# — see ``core.views_well_known``. Defaults are obvious placeholders so
# the file stays well-formed in dev; production installs MUST override
# both via env var. MOBILE_ANDROID_SHA256 accepts a comma-separated
# list to carry both the upload key + the Play app-signing key.
MOBILE_TEAM_ID = env_str("MOBILE_TEAM_ID", "PLACEHOLDER_TEAM_ID")
MOBILE_ANDROID_SHA256 = env_str("MOBILE_ANDROID_SHA256", "PLACEHOLDER_UPLOAD_KEY_SHA256")


# Firebase configuration
def var2file(variable):
    if (content := os.environ.get(variable)) is None:
        return None
    if os.path.exists(content):
        return content
    filename = f"/tmp/{variable}"
    with open(filename, "w") as stream:
        stream.write(content)
    return filename


# firebase credentials
FIREBASE_ADMIN_SDK = var2file("FIREBASE_ADMIN_SDK")

# Start of AWS Buckets
USE_S3 = env_bool("USE_S3", True)

if USE_S3:
    # aws / s3-compatible settings (works with AWS S3, MinIO, etc.)
    SERVER_NAME = env_str("SERVER_NAME", "localhost")
    AWS_ACCESS_KEY_ID = env_str("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env_str("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env_str("AWS_STORAGE_BUCKET_NAME")
    # Leave the endpoint unset for AWS S3; an empty string is invalid to boto3.
    AWS_S3_ENDPOINT_URL = env_str("AWS_S3_ENDPOINT_URL") or None  # MinIO: http://minio-local:9000
    AWS_S3_CUSTOM_DOMAIN = env_str("AWS_S3_CUSTOM_DOMAIN", "")
    if not AWS_S3_CUSTOM_DOMAIN:
        if AWS_S3_ENDPOINT_URL:
            AWS_S3_CUSTOM_DOMAIN = None  # Let boto3 use endpoint URL directly
        else:
            AWS_S3_CUSTOM_DOMAIN = f"static.{SERVER_NAME.replace('local', 'dev')}"
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True  # Required for pre-signed URLs with MinIO

    # s3 static settings
    AWS_LOCATION = ""
    STATIC_URL = "/static/"
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            # WhiteNoise's CompressedManifest storage hashes asset filenames so
            # browsers can cache aggressively, and pre-generates gzip/brotli
            # alongside originals so the runtime serve is just a file read.
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    STATIC_ROOT = os.path.join(BASE_DIR, "assets")
else:
    STATIC_URL = "/staticfiles/"
    STATIC_ROOT = os.path.join(BASE_DIR, "assets")

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

MEDIA_URL = "/mediafiles/"
MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")

# MEDIA_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# End of AWS Buckets

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    DEFAULT_DB_ALIAS: {
        "ENGINE": env_str("POSTGRES_ENGINE"),
        "NAME": env_str("POSTGRES_DB"),
        "USER": env_str("POSTGRES_USER"),
        "PASSWORD": env_str("POSTGRES_PASSWORD"),
        "HOST": env_str("POSTGRES_HOST"),
        "PORT": env_str("POSTGRES_PORT"),
        "OPTIONS": {"options": "-c search_path=public"},
    },
}

DATABASE_ROUTERS = []

CACHES = {
    DEFAULT_CACHE_ALIAS: {
        # 'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("DJANGO_CACHE_URL"),
    },
    "memory_cache": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
}

CSRF_TRUSTED_ORIGINS = [
    "https://storage.googleapis.com/",
    "http://localhost:3000",
    "http://localhost:80",
    "https://localhost:443",
    "https://localhost:8443",
]

# Application definition
INSTALLED_APPS = [
    # Start of Django Standard
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "strawberry_django",
    "phonenumber_field",
    "core",
    "rolepermissions",
    "django_filters",
    "djmoney",
    "nested_admin",
    "sslserver",
    "storages",
    "django_crontab",
    "import_export",
    "simple_history",
    "workflows",
    # End of Django Standard
    # Start of Email
    "django_ses",
    # End of Email
    # Start of health_check
    "health_check",  # required
    "health_check.db",  # stock Django health checkers
    "health_check.cache",
    "health_check.storage",
    "health_check.contrib.migrations",
    # End of health_check
    # Start of Astrolift
    "auth1",
    "config.middleware",
    "organization",
    "core_logs",
    # Canonical Astrolift platform apps (control-plane data model)
    "astrolift_identity",
    "astrolift_clusters",
    "astrolift_registry",
    "astrolift_lifecycle",
    "astrolift_services",
    "astrolift_operations",
    "astrolift_observability",
    "astrolift_billing",
    "astrolift_scm",
    "astrolift_forms",
    "astrolift_pipelines",
    "astrolift_agents",
    "astrolift_dispatch",
    # Retired (#1528): its four models are dropped by
    # astrolift_ci/0002_delete_ci_models. The app stays listed until that
    # migration has run everywhere — unlisting it first would strand the
    # tables. The shell goes in a follow-up.
    "astrolift_ci",
    # End of Astrolift
    "constance",
    "constance.backends.database",
]

# Feature toggles — remove disabled feature apps
from config.features import filter_installed_apps  # noqa: E402

INSTALLED_APPS = filter_installed_apps(INSTALLED_APPS)

# `testdata` ships the dev seed fixtures + the `seed` management
# command. It's harmless in any environment (only adds management
# commands and fixtures, no migrations of its own) and is needed by
# the test suite regardless of CONFIGURATION value.
if "testdata" not in INSTALLED_APPS:
    INSTALLED_APPS.append("testdata")

# Discover and merge domain app configurations
# Domain apps declare their configuration
# in astrolift_config/settings.py files
logger.info("Discovering domain apps...")
from config.config_merger import ConfigMerger  # noqa: E402

config_merger = ConfigMerger(BASE_DIR)
config_merger.discover()

# Merge INSTALLED_APPS from domain apps
DOMAIN_APPS = config_merger.get_installed_apps()
INSTALLED_APPS.extend(DOMAIN_APPS)
logger.info(f"Added {len(DOMAIN_APPS)} domain app(s) to INSTALLED_APPS")

# Merge MIDDLEWARE from domain apps
DOMAIN_MIDDLEWARE = config_merger.get_middleware()
if DOMAIN_MIDDLEWARE:
    # MIDDLEWARE will be extended after it's defined below
    pass

# Merge custom settings from domain apps
config_merger.merge_settings(globals())

CRONJOBS = []

# Temporal durable-workflow enable flag. Default ON; set
# ASTROLIFT_TEMPORAL_ENABLED=false at deploy time to disable globally
# (e.g. compose stacks without a Temporal server). Operators can also
# flip this at runtime via the Constance entry below — Constance wins
# when set, the env var is the seed default on first boot.
ASTROLIFT_TEMPORAL_ENABLED = env_bool("ASTROLIFT_TEMPORAL_ENABLED", True)

# Deploy-pipeline gate. Default ON. Seeded from FEATURE_DEPLOY_PIPELINE
# at boot, runtime-toggleable via /app/admin/constance/ so operators
# can pause start/promote/rollback/teardown without a redeploy
# (parity with TEMPORAL_ENABLED). When False every gated mutation
# returns a PRECONDITION envelope; cluster adoption is not gated.
ASTROLIFT_DEPLOY_PIPELINE_ENABLED = env_bool("FEATURE_DEPLOY_PIPELINE", True)

# Client Cove support integration. The module is default-off; deployments must
# opt in only after configuring an authenticated upstream and completing the
# entitlement-to-case smoke test.
ASTROLIFT_SUPPORT_ENABLED = env_bool("FEATURE_SUPPORT", False)
CLIENT_COVE_SUPPORT_URL = os.environ.get("CLIENT_COVE_SUPPORT_URL", "").rstrip("/")
CLIENT_COVE_SUPPORT_API_KEY = os.environ.get("CLIENT_COVE_SUPPORT_API_KEY", "")

CONSTANCE_CONFIG = {
    "AGENT_POD_UID": (
        42042,
        "uid non-root agent pods run as. Must be the agent user baked into the agent "
        "images (astrolift-agents creates 42042); a uid the image does not own cannot "
        "write its HOME and every non-root pod fails. Change only with matching images.",
        "posix_id",
    ),
    "AGENT_NETWORK_FENCE": (
        False,
        "Apply a NetworkPolicy to agent task and box pods: no inbound pod traffic; outbound "
        "only DNS and the public internet, never private ranges or cloud metadata. Agents "
        "that reach private git, an in-cluster Zentinelle, or managed databases need those "
        "in AGENT_EGRESS_ALLOW_CIDRS first. Turning it off does not remove an applied "
        "policy (delete astrolift-agent-fence). Needs a NetworkPolicy-capable CNI.",
    ),
    "AGENT_EGRESS_ALLOW_CIDRS": (
        "",
        "Comma-separated CIDRs agent pods may reach despite the fence, e.g. the control "
        "plane or Zentinelle when they run in-cluster.",
    ),
    "AGENT_POD_GID": (
        42042,
        "gid (and fsGroup) non-root agent pods run as. Same rule as AGENT_POD_UID.",
        "posix_id",
    ),
    "TIME_ZONE": (TIME_ZONE, "System timezone"),
    "PUT_PRESIGNED_URL_EXPIRATION": (60, "Time to live in seconds of presigned urls for uploading."),
    "GET_PRESIGNED_URL_EXPIRATION": (3600, "Time to live in seconds of presigned urls for downloading."),
    "AUTH0_REGISTER_NEW_USER": (False, "Register new users in Auth0"),
    "RESTRICT_SOURCE_REPOS_TO_ORG": (
        False,
        "Only accept app source repos owned by a connected organization. Personal "
        "repos are refused at registration and hidden from the repo picker. Default "
        "off, which is the existing behavior.",
    ),
    "EMAIL_NOTIFICATIONS": (False, "Enables the platform to send Email Notifications"),
    "ZENTINELLE_ENABLED": (
        False,
        "Enable Zentinelle governance surfaces (agent Activity/Reasoning/Token-Usage/Compliance tabs)",
    ),
    "ZENTINELLE_GATEWAY_ENABLED": (
        False,
        "Deploy the Zentinelle gateway (Deployment + Service zentinelle-gateway in astrolift-system) "
        "into clusters an organization registered with its Zentinelle connection, and let fenced "
        "agent pods reach it. Off deploys nothing new; turning it off does not remove a running "
        "gateway (turn the cluster's gateway off, or disconnect).",
    ),
    "ZENTINELLE_GATEWAY_IMAGE": (
        "ghcr.io/calliopeai/zentinelle-gateway:main-107ad0b",
        "Zentinelle gateway image, pinned. Point it at a mirror or a digest for private registries. "
        "Needs a build that reads its credential from /var/run/zentinelle (calliopeai/zentinelle#387). "
        "Applies to gateways deployed after the change.",
    ),
    "TEMPORAL_ENABLED": (
        ASTROLIFT_TEMPORAL_ENABLED,
        "Enable the durable-workflow runtime. When False the client returns synthetic handles "
        "instead of starting workflows — useful for dev/test envs without a Temporal server. "
        "Seeded from the ASTROLIFT_TEMPORAL_ENABLED env var (default True) and can be toggled "
        "at runtime here.",
    ),
    "DEPLOY_PIPELINE_ENABLED": (
        ASTROLIFT_DEPLOY_PIPELINE_ENABLED,
        "Enable the app deploy pipeline (start/promote/rollback/teardown). When False those "
        "mutations short-circuit with a PRECONDITION envelope so operators can pause rollouts "
        "without a redeploy. Cluster adoption (bringClusterIntoManagement) is not gated. "
        "Seeded from the FEATURE_DEPLOY_PIPELINE env var (default True).",
    ),
    "SUPPORT_ENABLED": (
        ASTROLIFT_SUPPORT_ENABLED,
        "Enable the Client Cove support case module. Default off until the "
        "authenticated entitlement contract and production smoke test are complete.",
    ),
    # ---- Organization modules (#1859) ----
    # Install-wide force-off for modules an org admin turns on per org
    # (astrolift_identity.org_modules). On by default: the org decides.
    # Turning one off disables the module for every organization at once.
    "CHAT_STUDIO_INTEGRATION_ALLOWED": (
        True,
        "Organizations may turn on the Chat Studio integration module (shipping apps "
        "through the builder API). Off forces the module off for every organization.",
    ),
    "AGENT_LIVE_ATTACH_ALLOWED": (
        True,
        "Organizations may turn on live attach to running agents. Off forces the module "
        "off for every organization.",
    ),
    "WEBHOOK_SECRET_ROTATION_GRACE_SECONDS": (
        3600,
        "Window (in seconds) the previous webhook subscription secret stays valid after a "
        "rotation. Subscribers verify against the new secret first; on mismatch the platform "
        "falls back to the previous secret until this window expires. Default 1h; bump for "
        "fleets that need a longer rollout window, lower (e.g. 60) after a compromise so the "
        "old secret dies fast.",
    ),
    "DEPLOY_TOKEN_ROTATION_GRACE_SECONDS": (
        86400,
        "Window (in seconds) the previous deploy-token secret stays valid after a rotation "
        "so in-flight CI runs holding the old token finish without failing. Default 24h. "
        "Lower bound 60s, upper bound 7d. Surfaced in the rotate-confirm dialog so operators "
        "see the exact grace they're committing to. Use the explicit ``revokeDeployToken`` "
        "path (or ``immediate=True`` in code) for compromised-token cutover.",
    ),
    "DEPLOY_TOKEN_LEGACY_PREFIX_ACCEPTED": (
        True,
        "Accept the pre-#449 legacy ``alfdt_`` deploy-token prefix in addition to the "
        "canonical ``alft_dt_`` shape. Default True so in-flight tokens issued before #449 "
        "keep authenticating after the canonicalisation ships. Flip to False once the "
        "``deploy_token.legacy_prefix_accepted`` audit stream confirms no caller is still "
        "presenting the legacy shape — at that point any straggler legacy token will fail "
        "auth with a 401 and operators can re-issue.",
    ),
    "ALLOW_SELF_APPROVE_DEPLOYS": (
        False,
        "When False (default), the user who triggered a deployment cannot also approve it — "
        "compliance + separation-of-duties. Flip to True for single-engineer / dev orgs that "
        "still want the deploy-approval audit trail without blocking on a second approver. "
        "Per-deployment auditability is unchanged either way.",
    ),
    "BUILDER_DATA_FILE_MAX_BYTES": (
        64 * 1024 * 1024,
        "Largest data file (e.g. an app's data.sqlite) the App Builder accepts in one "
        "files sync, in decoded bytes. It travels base64 in the request, so the request "
        "can be a third larger; an ingress in front of the control plane must allow that "
        "body size. The file is stored in Postgres and shipped to the cluster as Secrets.",
    ),
    # ---- Admin console surfaces (feature flipper) ----
    # Runtime gates for the platform-admin cost / quotas / permissions
    # screens. Default OFF — the screens ship dark and each gates itself
    # on its flag once the underlying implementation lands. Flip on from
    # /administration/features (the in-app feature flipper) or here.
    "ADMIN_COST_ENABLED": (
        False,
        "Enable the platform-admin Cost console (/administration/cost). Default OFF until the "
        "cost aggregation surface is production-ready; toggle from the in-app feature flipper.",
    ),
    "ADMIN_QUOTAS_ENABLED": (
        False,
        "Enable the platform-admin Quotas console (/administration/quotas). Default OFF until "
        "the quota-enforcement surface is production-ready; toggle from the feature flipper.",
    ),
    "ADMIN_PERMISSIONS_ENABLED": (
        False,
        "Enable the platform-admin Permissions console (/administration/permissions). Default "
        "OFF until the permissions surface is production-ready; toggle from the feature flipper.",
    ),
    "AUDIT_RETENTION_DAYS": (
        90,
        "Platform-wide default audit-log retention, in days, for the retention sweeper. "
        "The per-org window shown/edited on /administration/audit and "
        "/administration/organization is the Organization.audit_log_retention_days column; "
        "this flag is the fallback default only. Lower bound 1 day, upper bound 2557 days "
        "(~7 years, the spec ceiling).",
    ),
    "AUDIT_EXPORT_DOWNLOAD_TTL_SECONDS": (
        3600,
        "How long a generated audit-export download URL stays valid before the token "
        "expires (default 1h). Lengthen for fleets that need to hand off the URL to a "
        "third-party auditor; shorten after an incident.",
    ),
    "AUDIT_EXPORT_MAX_ROWS": (
        100000,
        "Hard cap on the row count a single exportAuditEvents call will dump. Protects "
        "the worker from runaway exports while still leaving room for multi-year SOC2 "
        "extracts at the default retention.",
    ),
    "APP_LOG_EXPORT_MAX_LINES": (
        100000,
        "Hard cap on the line count a single exportAstroliftAppLogs call serializes "
        "into the downloadable artifact. Mirrors AUDIT_EXPORT_MAX_ROWS — protects the "
        "synchronous render path while still covering typical incident bundles.",
    ),
    "APP_LOG_EXPORT_TTL_SECONDS": (
        3600,
        "How long the token-gated download URL stays valid after exportAstroliftAppLogs "
        "succeeds (default 1h). Single-use token in addition to the TTL.",
    ),
    "MAX_SESSIONS_PER_CLIENT_KIND": (
        '{"web": 5, "cli": 3, "mobile": 3, "browser_extension": 2, "api_token": 10}',
        "Per-user concurrent-session cap, JSON-shaped per client kind. When a fresh "
        "session would push the user above the cap for that kind, the oldest live "
        "session of that kind is auto-revoked (audit action `session.quota_evicted`). "
        "Lower e.g. mobile to 1 if your install enforces single-device mobile; raise "
        "cli for shops with many concurrent CI runners per engineer. Unknown kinds in "
        "the JSON are ignored; missing kinds fall back to the per-kind default.",
    ),
    "STALE_SESSION_TTL_SECONDS_WEB": (
        30 * 24 * 3600,
        "Browser session stale threshold (seconds). `PruneStaleSessionsWorkflow` "
        "soft-revokes web sessions whose `last_seen_at` is older than this. Default 30 "
        "days; lower for high-security envs, raise for kiosk-style installs.",
    ),
    "STALE_SESSION_TTL_SECONDS_CLI": (
        90 * 24 * 3600,
        "CLI session stale threshold (seconds). Default 90 days — covers long-running "
        "CI tokens that may sit idle between pipeline runs.",
    ),
    "STALE_SESSION_TTL_SECONDS_MOBILE": (
        60 * 24 * 3600,
        "Mobile session stale threshold (seconds). Default 60 days; covers the common "
        "'phone in a drawer for a vacation' case before auto-revoking.",
    ),
    "STALE_SESSION_TTL_SECONDS_BROWSER_EXTENSION": (
        60 * 24 * 3600,
        "Browser-extension session stale threshold (seconds). Default 60 days.",
    ),
    "STALE_SESSION_TTL_SECONDS_API_TOKEN": (
        180 * 24 * 3600,
        "API-token session stale threshold (seconds). Default 180 days; raise for "
        "long-lived programmatic clients that legitimately sit idle for quarters.",
    ),
    "REQUIRE_STEP_UP_AUTH": (
        False,
        "Master switch for the #487 step-up auth gate. Default OFF — sensitive "
        "mutations run without a re-auth prompt unless explicitly enabled. Flip "
        "to True for installs whose compliance posture requires SOC2 / SOX-style "
        "fresh-auth on secret writes, role changes, force-redeploys, etc. When "
        "True, STEP_UP_AUTH_TTL_SECONDS controls the elevation window.",
    ),
    "STEP_UP_AUTH_TTL_SECONDS": (
        900,
        "Default elevation window (in seconds) granted by elevateAdminSession. After "
        "this window expires every @requires_elevation mutation re-prompts for the "
        "step-up credential. Default 900s (15 min) matches the spec 27 §4.1 ceiling "
        "and SOC2 / SOX fresh-auth expectations. The mutation accepts a per-call "
        "ttlSeconds override capped at STEP_UP_AUTH_MAX_TTL_SECONDS.",
    ),
    "STEP_UP_AUTH_MAX_TTL_SECONDS": (
        900,
        "Hard cap on the per-call ttlSeconds an elevateAdminSession request can ask "
        "for. The spec ceiling is 15 minutes; a longer-lived elevation defeats the "
        "purpose of step-up auth. Anything above this is silently clamped.",
    ),
    "STEP_UP_SSO_FRESHNESS_SECONDS": (
        60,
        "Maximum age (in seconds) of the IdP-asserted auth_time claim that the SSO "
        "step-up callback will accept. A cached id_token with an auth_time older than "
        "this window is rejected to prevent replay — even if state + nonce check out, "
        "the operator must have actually re-authenticated at the IdP within this "
        "window for the elevation to succeed. Default 60s gives a generous round-trip "
        "buffer while keeping the replay surface tight.",
    ),
    # ---- Device attestation (#496) ----
    "REQUIRE_ATTESTATION_FOR_MOBILE": (
        False,
        "Master feature flag for device attestation. When True, mobile sessions must "
        "produce a verified iOS App Attest or Android Play Integrity blob before the "
        "platform will run any mutation through them. Most installs leave this off; "
        "regulated-industry tenants flip it on. Browser / CLI / API-token sessions are "
        "never affected by this flag.",
    ),
    "REQUIRE_ATTESTATION_FOR_SENSITIVE_OPS": (
        False,
        "When True, only step-up-gated (sensitive) mutations require device attestation "
        "from mobile sessions; non-sensitive reads + day-to-day mutations are unaffected. "
        "Use this when REQUIRE_ATTESTATION_FOR_MOBILE is too broad — the mobile app can "
        "still browse but must attest before approving deploys / setting secrets / "
        "rotating tokens.",
    ),
    "REQUIRE_STRONG_ANDROID_INTEGRITY": (
        False,
        "When True, Android sessions must produce a MEETS_STRONG_INTEGRITY verdict "
        "(hardware-backed keystore) — excludes older / cheaper devices that only pass "
        "MEETS_DEVICE_INTEGRITY. Off by default to match the broadest device matrix.",
    ),
    "IOS_APP_ID": (
        "",
        "iOS App ID in the canonical <TEAM_ID>.<BUNDLE_ID> form, e.g. "
        "'A1B2C3D4E5.com.example.mobile'. Required when REQUIRE_ATTESTATION_FOR_MOBILE "
        "is on; used as the App Attest RP ID and verified against the rpIdHash field "
        "of the attestation authenticator data.",
    ),
    "ANDROID_PACKAGE_NAME": (
        "",
        "Android application package name, e.g. 'com.example.mobile'. Required when "
        "REQUIRE_ATTESTATION_FOR_MOBILE is on; verified against the "
        "requestPackageName field of the decoded Play Integrity token.",
    ),
    "GOOGLE_PLAY_INTEGRITY_API_KEY": (
        "",
        "API key (or service-account JSON) used to call Google's Play Integrity API "
        "decodeIntegrityToken endpoint. Required when REQUIRE_ATTESTATION_FOR_MOBILE "
        "is on for any Android session. Treat as secret — do NOT commit to source.",
    ),
    "ATTESTATION_CHALLENGE_TTL_SECONDS": (
        300,
        "How long a server-issued attestation nonce stays valid before the verifier "
        "rejects it. Default 300s (5 min) matches Apple's recommended ceiling for the "
        "App Attest ceremony. Lower for high-security envs; raise only if a tap-to-"
        "approve UX legitimately needs more time.",
    ),
}

CONSTANCE_CONFIG_FIELDSETS = {
    "Agent pods": {
        "fields": ("AGENT_POD_UID", "AGENT_POD_GID", "AGENT_NETWORK_FENCE", "AGENT_EGRESS_ALLOW_CIDRS"),
        "collapse": False,
    },
    "System": {
        "fields": ("TIME_ZONE", "PUT_PRESIGNED_URL_EXPIRATION", "GET_PRESIGNED_URL_EXPIRATION"),
        "collapse": False,
    },
    "Auth0": {"fields": ("AUTH0_REGISTER_NEW_USER",), "collapse": False},
    "Source repositories": {"fields": ("RESTRICT_SOURCE_REPOS_TO_ORG",), "collapse": False},
    "Notifications": {"fields": ("EMAIL_NOTIFICATIONS",), "collapse": False},
    "Support": {"fields": ("SUPPORT_ENABLED",), "collapse": False},
    "Zentinelle": {
        "fields": ("ZENTINELLE_ENABLED", "ZENTINELLE_GATEWAY_ENABLED", "ZENTINELLE_GATEWAY_IMAGE"),
        "collapse": False,
    },
    "Organization modules": {
        "fields": ("CHAT_STUDIO_INTEGRATION_ALLOWED", "AGENT_LIVE_ATTACH_ALLOWED"),
        "collapse": False,
    },
    "Log exports": {
        "fields": ("APP_LOG_EXPORT_MAX_LINES", "APP_LOG_EXPORT_TTL_SECONDS"),
        "collapse": False,
    },
    "Admin screens": {
        "fields": (
            "ADMIN_COST_ENABLED",
            "ADMIN_QUOTAS_ENABLED",
            "ADMIN_PERMISSIONS_ENABLED",
        ),
        "collapse": False,
    },
    "Workflows": {
        "fields": ("TEMPORAL_ENABLED", "DEPLOY_PIPELINE_ENABLED", "ALLOW_SELF_APPROVE_DEPLOYS"),
        "collapse": False,
    },
    "App Builder": {"fields": ("BUILDER_DATA_FILE_MAX_BYTES",), "collapse": False},
    "Webhooks": {"fields": ("WEBHOOK_SECRET_ROTATION_GRACE_SECONDS",), "collapse": False},
    "Deploy tokens": {
        "fields": (
            "DEPLOY_TOKEN_ROTATION_GRACE_SECONDS",
            "DEPLOY_TOKEN_LEGACY_PREFIX_ACCEPTED",
        ),
        "collapse": False,
    },
    "Audit": {
        "fields": (
            "AUDIT_RETENTION_DAYS",
            "AUDIT_EXPORT_DOWNLOAD_TTL_SECONDS",
            "AUDIT_EXPORT_MAX_ROWS",
        ),
        "collapse": False,
    },
    "Sessions": {
        "fields": (
            "MAX_SESSIONS_PER_CLIENT_KIND",
            "STALE_SESSION_TTL_SECONDS_WEB",
            "STALE_SESSION_TTL_SECONDS_CLI",
            "STALE_SESSION_TTL_SECONDS_MOBILE",
            "STALE_SESSION_TTL_SECONDS_BROWSER_EXTENSION",
            "STALE_SESSION_TTL_SECONDS_API_TOKEN",
        ),
        "collapse": False,
    },
    "Device attestation": {
        "fields": (
            "REQUIRE_ATTESTATION_FOR_MOBILE",
            "REQUIRE_ATTESTATION_FOR_SENSITIVE_OPS",
            "REQUIRE_STRONG_ANDROID_INTEGRITY",
            "IOS_APP_ID",
            "ANDROID_PACKAGE_NAME",
            "GOOGLE_PLAY_INTEGRITY_API_KEY",
            "ATTESTATION_CHALLENGE_TTL_SECONDS",
        ),
        "collapse": False,
    },
    "Step-up auth": {
        "fields": (
            "REQUIRE_STEP_UP_AUTH",
            "STEP_UP_AUTH_TTL_SECONDS",
            "STEP_UP_AUTH_MAX_TTL_SECONDS",
            "STEP_UP_SSO_FRESHNESS_SECONDS",
        ),
        "collapse": False,
    },
}

INTERNAL_IPS = [
    "127.0.0.1",
]

DEBUG_TOOLBAR_CONFIG = {
    # Gate the toolbar on a dedicated env var rather than on DEBUG: it leaks
    # internal SQL / settings / cache details to anyone who can reach the
    # page and adds noticeable per-request overhead, so an operator debugging
    # a dev-configuration install still gets to decide. (Until #1732 the
    # server configurations ran DEBUG=True, which is what made a dedicated
    # gate load-bearing rather than a convenience.)
    "SHOW_TOOLBAR_CALLBACK": lambda request: env_bool("ASTROLIFT_ENABLE_DJT", False),
    # Allow test runs without removing debug_toolbar from INSTALLED_APPS
    "IS_RUNNING_TESTS": False,
}

# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django_ratelimit.middleware.RatelimitMiddleware",
    # Determines Ip ranges supported, specific hosts are managed via the ALLOWED_HOSTS setting in each env
    "config.middleware.allow_cidr_hosts.AllowCIDRHostsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves collected static files (admin css/js, etc.) directly
    # from the app server. Must come immediately after SecurityMiddleware per
    # https://whitenoise.readthedocs.io/.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "auth1.middleware.Auth0SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.auth.middleware.RemoteUserMiddleware",  # Required for Auth0
    # API token bearer auth (#428): resolves alft_at_… tokens, stamps
    # last_used_* columns, swaps in the token owner so resolvers see
    # the correct request.user. Runs after AuthenticationMiddleware
    # so it can override the anonymous user it just set, and before
    # CurrentUserMiddleware so the thread-local picks up the
    # token-authed identity.
    "astrolift_identity.middleware.ApiTokenAuthMiddleware",
    # Deploy-token bearer auth (#425): resolves alft_dt_… tokens for
    # CI deploys, stamps last_used_* columns onto the matched
    # DeployToken row, attaches the row to request._deploy_token so
    # downstream views can read the app binding without re-verifying.
    # Doesn't swap request.user — deploy tokens are app-scoped
    # credentials with their own permission model.
    "astrolift_lifecycle.middleware.DeployTokenAuthMiddleware",
    "core.middleware.current_user.CurrentUserMiddleware",  # Track current user for signals
    "core.middleware.request_id.RequestIdMiddleware",  # ULID + W3C traceparent → contextvar
    "core.middleware.tenant.TenantContextMiddleware",  # Resolve org/team/project, populate TenantContext
    # Sidecar AstroliftSession write path (#480 / #495 / #498). Runs
    # after AuthenticationMiddleware + TenantContextMiddleware so we
    # have a resolved user + org context to stamp on the row.
    "astrolift_identity.sessions.SessionTrackingMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'django.middleware.gzip.GZipMiddleware',
]

TEMPLATES_CACHE_BACKEND = DEFAULT_CACHE_ALIAS

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "config/templates/")],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                        "core.loaders.template.Loader",
                    ],
                ),
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    # 'config.backend.MagicBackend',
]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DATE_INPUT_FORMATS": [
        "%Y-%m-%d",  # 1962-08-15
        "%Y-%m-%dT%H:%M:%S",  # 1962-08-15T00:00:00
        "iso-8601",  # keep DRF's default
    ],
    "DATETIME_INPUT_FORMATS": [
        "%Y-%m-%dT%H:%M:%S",  # 1962-08-15T00:00:00
        "iso-8601",
    ],
}

# Rate limiting
# django-ratelimit renders this view when a request is blocked. Django's
# permission_denied view returned a bare 403, which reads as "you lost
# access" rather than "you spent your budget" (#1248).
RATELIMIT_VIEW = "config.views.ratelimited"
RATELIMIT_RETRY_AFTER_SECONDS = int(env_str("RATELIMIT_RETRY_AFTER_SECONDS", "60"))

# Per-user (or per-IP when anonymous) budget for the GraphQL endpoint.
#
# This was a hardcoded 100/m, which the UI exceeded on its own: ~98 polled
# queries exist in the frontend, ~21 of them at 5s or faster, and a single
# page such as clusters/[slug]/status mounts about seven at once. One
# operator on one dashboard could exhaust the window without doing anything
# unusual, and then *every* request 403'd until it rolled — including the
# app-shell query, so the whole UI appeared to break.
#
# 600/m is 10 requests/second sustained per user: comfortable for a polling
# dashboard, still tight enough to stop a runaway client loop. Tune via env
# without a code change; the auth endpoint keeps its own tighter budget
# since it is unauthenticated and brute-forceable.
RATELIMIT_GRAPHQL_RATE = env_str("RATELIMIT_GRAPHQL_RATE", "600/m")
RATELIMIT_GRAPHQL_AUTH_RATE = env_str("RATELIMIT_GRAPHQL_AUTH_RATE", "30/m")

# Temporal — durable workflow runtime
TEMPORAL_ADDRESS = env_str("TEMPORAL_ADDRESS", "localhost:7233")
TEMPORAL_NAMESPACE = env_str("TEMPORAL_NAMESPACE", "default")
TEMPORAL_TASK_QUEUE = env_str("TEMPORAL_TASK_QUEUE", "astrolift-main")

# GitHub personal access token used by the agent Brief assembler to fetch
# config-repo zipballs. Empty means unauthenticated requests (public repos
# only, subject to GitHub's lower anonymous rate limit).
GITHUB_PAT = env_str("GITHUB_PAT", "")


# Structured logging: JSON in non-local envs, human-readable text
# locally. ``core.logging.build_logging_config`` is the single source
# of truth — set ``LOG_FORMAT`` (``json`` | ``text`` | ``ecs``),
# ``LOG_LEVEL`` (default ``INFO``), and ``LOG_DESTINATION``
# (``stdout`` | ``stderr``) to override.
TELEMETRY_LOGS = env_bool("TELEMETRY_LOGS", True)
LOG_LEVEL = env_str("LOG_LEVEL", env_str("DJANGO_LOG_LEVEL", "INFO"))
LOG_FORMAT = env_str("LOG_FORMAT", "json")
LOG_DESTINATION = env_str("LOG_DESTINATION", "stdout")

from core.logging import build_logging_config  # noqa: E402

LOGGING = build_logging_config(
    level=LOG_LEVEL,
    format_=LOG_FORMAT,
    destination=LOG_DESTINATION,
)

# ================ DEV
# Every configuration name the branching below actually handles. Kept beside
# the read so a new branch and this set are edited together -- the failure mode
# it guards is a name that matches nothing and falls through (#1715).
# "prod" is deliberately absent: the Sentry match above accepts it, but no
# branch below configures it, so it falls through exactly like an invented
# name -- and IS_PROD tests for "prd", so it would also have produced a
# production deployment with IS_PROD False. Refusing it is the honest answer;
# adding it as an alias would be a behaviour change, not a guard.
_KNOWN_CONFIGURATIONS = frozenset({"dev", "prd", "int", "stg", "tests", "local", "localpg", "localverbose"})

CONFIGURATION = env_str("DJANGO_CONFIGURATION", "Dev")
logger.warning(f"DJANGO_CONFIGURATION: {CONFIGURATION}")

SENTRY_DSN = env_str("SENTRY_DSN")

match CONFIGURATION.lower():
    case "stg" | "dev" | "prd" | "prod":
        if SENTRY_DSN:
            sentry_sdk.init(
                dsn=SENTRY_DSN,
                traces_sample_rate=1.0,
                profiles_sample_rate=1.0,
                environment=CONFIGURATION,
            )
        else:
            logger.info("Sentry DSN not configured; skipping Sentry init")
    case _:
        logger.info(f"Sentry is not enabled for configuration: {CONFIGURATION}")

ALLOWED_HOSTS = [
    "*",
]

IS_PROD = CONFIGURATION.lower() == "prd"
IS_DEV = CONFIGURATION.lower() == "dev" or CONFIGURATION.lower() == "local"
IS_LOCAL = CONFIGURATION.lower() in ("local", "localpg", "localverbose")

# The server configurations (#1732). ``DEBUG`` was True on all four and
# the password validators were emptied, which on a real install means
# Django's technical 500 page -- full traceback, every frame's locals, and
# the settings dump redacted only by name-matching -- is served to anyone
# who can provoke an unhandled exception, and every request's SQL is
# retained in ``connection.queries`` on a long-lived worker.
#
# This reverses a deliberate earlier choice (the DJT comment above still
# describes prod as keeping DEBUG=True "for error-page debugging"). The
# trade it made is not one a hosted install can keep: the traceback goes
# to whoever provoked it, not to the operator.
#
# WhiteNoise serves collected static files from its own middleware
# regardless of DEBUG, so this does not change static serving; ALLOWED_HOSTS
# keeps its wildcard, so nothing that reaches the app today stops reaching
# it. What changes is the error page, and that is the point.
#
# The other half of #1732: CONFIGURATION defaults to "Dev" a few lines up
# when DJANGO_CONFIGURATION is unset, which is exactly the SteadyMD
# install's situation. That install must not inherit the technical error
# page and cleared password validators just because nothing was declared,
# so the Dev branch below no longer hardcodes DEBUG -- it keeps whatever
# DJANGO_DEBUG resolved to above. Every dev/test surface in this repo sets
# DJANGO_DEBUG explicitly (local.env, docker-compose.yaml, CI's
# backend-test-shard job), so nothing that already opts in changes; an
# install that declares neither variable now gets the safe posture by
# default instead of the most permissive one.
if CONFIGURATION.lower() in ("prd", "stg", "int"):
    DEBUG = False
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "*"]
elif CONFIGURATION.lower() == "Dev".lower():
    # The developer configuration keeps the technical error page only when
    # DJANGO_DEBUG says so explicitly (#1732) -- DEBUG itself was already
    # resolved from that variable at the top of this file.
    if DEBUG:
        AUTH_PASSWORD_VALIDATORS = []
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "*"]
elif CONFIGURATION.lower() == "Tests".lower():
    DEBUG = True
    SECRET_KEY = "not-a-secret"
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}}
    CACHES = {
        DEFAULT_CACHE_ALIAS: {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        },
        "memory_cache": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        },
    }
    # testdata already appended unconditionally above.
elif CONFIGURATION.lower() == "Local".lower() or CONFIGURATION.lower() == "LocalPG".lower():
    DEBUG = True
    ALLOWED_HOSTS = [
        "*",
    ]
    AUTH_PASSWORD_VALIDATORS = []
    DEFAULT_USER_TEST = env_str(
        "DJANGO_", "admin"
    )  # only for local login the user if there is no user logged in
    TELEMETRY_LOGS = False
    # testdata already appended unconditionally above.
    LOGGING = build_logging_config(
        level=LOG_LEVEL,
        format_=env_str("LOG_FORMAT", "text"),
        destination=LOG_DESTINATION,
    )
elif CONFIGURATION.lower() == "LocalVerbose".lower():
    DEBUG = True
    ALLOWED_HOSTS = [
        "*",
    ]
    AUTH_PASSWORD_VALIDATORS = []
    DEFAULT_USER_TEST = env_str(
        "DJANGO_", "admin"
    )  # only for local login the user if there is no user logged in
    TELEMETRY_LOGS = False
    LOGGING = build_logging_config(
        level=env_str("LOG_LEVEL", "DEBUG"),
        format_=env_str("LOG_FORMAT", "text"),
        destination=LOG_DESTINATION,
    )
else:
    # Refuse to start rather than fall back (#1715).
    #
    # This branch used to hand any unrecognised name an in-memory SQLite and
    # a hardcoded SECRET_KEY. A deployment that invented a configuration name
    # ("Production", which is not a name this application declares) therefore
    # came up, served its login page and passed its load balancer health check
    # while every write went to a database inside one task: two tasks disagreed
    # with each other, a restart was a factory reset, and migrations ran against
    # a schema thrown away when the process exited. Every POSTGRES_* variable
    # was present and correct the whole time.
    #
    # Nothing about that is detectable from outside the process, which is what
    # makes silence the wrong default: a typo in one environment variable is a
    # data-loss bug that looks like a healthy install.
    raise ImproperlyConfigured(
        f"DJANGO_CONFIGURATION={CONFIGURATION!r} is not a configuration this "
        f"application declares. Valid values: {', '.join(sorted(_KNOWN_CONFIGURATIONS))}. "
        f"Refusing to start -- the previous behaviour was to fall back to an "
        f"in-memory SQLite database, which serves traffic and loses every write."
    )

# A non-dev configuration has no legitimate reason to run on SQLite (#1715).
# Belt to the braces above: this catches the case where the engine is selected
# by some path other than the name check -- a missing POSTGRES_HOST, a settings
# import order change -- and turns it into a refusal instead of silent data
# loss. Tests declare sqlite deliberately and are excluded by name.
#
# Keyed on DEBUG rather than IS_DEV/IS_LOCAL (#1732): IS_DEV is true for any
# install that never declares DJANGO_CONFIGURATION, because CONFIGURATION
# silently defaults to "Dev" above -- exactly the label a real deployment can
# (and did) leave unset, which made this guard inert on the one install it
# was written for. DEBUG now requires the same explicit DJANGO_DEBUG opt-in
# that the developer configuration does, so an undeclared configuration gets
# the same refusal a misspelled one already gets instead of being waved
# through as "probably a laptop".
if not DEBUG and CONFIGURATION.lower() != "tests":
    # ``POSTGRES_ENGINE`` unset reads as None, and the membership test
    # below raised TypeError on it -- an unhandled crash from the guard
    # written to turn this exact situation into a readable refusal.
    _engine = str(DATABASES[DEFAULT_DB_ALIAS].get("ENGINE") or "")
    if not _engine:
        raise ImproperlyConfigured(
            f"DJANGO_CONFIGURATION={CONFIGURATION!r} has no database engine configured. "
            f"A server configuration cannot run without one. Set POSTGRES_ENGINE and the "
            f"rest of the POSTGRES_* variables."
        )
    if "sqlite" in _engine:
        raise ImproperlyConfigured(
            f"DJANGO_CONFIGURATION={CONFIGURATION!r} resolved to {_engine}. "
            f"A non-development configuration must not run on SQLite: it serves "
            f"traffic normally and loses every write on restart. Check the "
            f"POSTGRES_* variables."
        )

logger.warning(f"Settings Version - End: {VERSION}")
logger.warning(f"DATABASE: {DATABASES[DEFAULT_DB_ALIAS]['ENGINE']}")
logger.warning(f"DB NAME: {DATABASES[DEFAULT_DB_ALIAS]['NAME']}")
if "USER" in DATABASES[DEFAULT_DB_ALIAS]:
    logger.warning(f"DB USER: {DATABASES[DEFAULT_DB_ALIAS]['USER']}")
logger.warning(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")


# multiple import options
IMPORT_FORMATS = [JSON]

# single export options
EXPORT_FORMATS = [JSON, TSV, CSV, XLSX]

# Twilio Settings
TWILIO_SID = os.getenv("TWILIO_SID", "")
TWILIO_SECRET = os.getenv("TWILIO_SECRET", "")
TWILIO_FROM_NUMBER = os.getenv("TWILIO_FROM_NUMBER", "")
TWILIO_CALLBACK = os.getenv("TWILIO_CALLBACK", "")
