"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 3.2.9.
For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import logging
import os
from pathlib import Path
from typing import overload

import django
import django.utils.encoding
import sentry_sdk

# patch https://stackoverflow.com/questions/70382084/import-error-force-text-from-django-utils-encoding
from corsheaders.defaults import default_headers
from django.core.cache import DEFAULT_CACHE_ALIAS
from django.db import DEFAULT_DB_ALIAS
from django.utils.encoding import force_str
from dotenv import load_dotenv
from import_export.formats.base_formats import CSV, JSON, TSV, XLSX


def _strtobool(val: str) -> int:
    """Stand-in for the removed ``distutils.util.strtobool`` (gone in 3.12)."""
    val = val.lower()
    if val in ("y", "yes", "t", "true", "on", "1"):
        return 1
    if val in ("n", "no", "f", "false", "off", "0"):
        return 0
    raise ValueError(f"invalid truth value {val!r}")


def env_bool(name: str, default: bool = False) -> bool:
    val = env_str(name, str(default)) or str(default)
    return _strtobool(val) == 1


@overload
def env_str(name: str, default: str) -> str: ...


@overload  # noqa: E302
def env_str(name: str, default: None = None) -> str | None: ...


def env_str(name: str, default: str | None = None) -> str | None:
    return os.getenv(name, default)


logger = logging.getLogger(__name__)

VERSION = "0.0.40"
logger.warning(f"Settings Version - Start: {VERSION}")

django.utils.encoding.force_text = force_str  # type: ignore[attr-defined]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DOTENV_FILE = env_str("DOTENV", os.path.join(BASE_DIR, "config/local.env"))

if os.path.exists(DOTENV_FILE):
    logger.warning(f"Loading environment from DOTENV={DOTENV_FILE}")
    load_dotenv(DOTENV_FILE)
else:
    logger.warning(f"DOTENV - No environment file found at DOTENV={DOTENV_FILE}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

DEBUG = env_bool("DJANGO_DEBUG", False)
DEFAULT_USER_TEST = env_str(
    "DJANGO_DEFAULT_USER_TEST", "admin"
)  # only for local login the user if there is no user logged in

# The default user to execute automatic system operations. i.e. scheduled tasks, automatic signatures...
# The default set of permissions available for the system user(s). For instance, the permission to sign documents.
FRONTEND_URL = env_str("FRONTEND_URL", "http://localhost:3000")
# Public base URL the platform's REST API answers at — surfaced to
# operators on the Settings page (#382) as the value to wire into
# ``ASTROLIFT_API_URL`` on the CI side so the deploy webhook hits the
# right install. Falls back to FRONTEND_URL for local dev where the
# Next.js proxy fronts the Django API at the same origin.
PLATFORM_API_URL = env_str("PLATFORM_API_URL", FRONTEND_URL)
API_SYSTEM_USER = env_str("API_SYSTEM_USER", "system")
API_SYSTEM_PERMISSION_GROUP = env_str("API_SYSTEM_PERMISSION_GROUP", "astrolift_automatic_system_operations")

# Django
SECRET_KEY = env_str("DJANGO_SECRET_KEY", "not-a-secret")
ROOT_URLCONF = env_str("DJANGO_ROOT_URLCONF", "config.urls")
BASE_URL = env_str("DJANGO_BASE_URL", "app/")
LOGIN_REDIRECT_URL = env_str("DJANGO_LOGIN_REDIRECT_URL", f"/{BASE_URL}admin/")
SWITCHED_FROM_USER = "switched_from_user"

CORS_ALLOW_CREDENTIALS = env_bool("DJANGO_CORS_ALLOW_CREDENTIALS", True)
CORS_ALLOW_ALL_ORIGINS = env_bool("DJANGO_CORS_ALLOW_ALL_ORIGINS", True)
CORS_ALLOW_HEADERS = default_headers + (
    "sentry-trace",
    "baggage",
    "x-platform",
)
CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_DATABASE_CACHE_BACKEND = "default"

CORS_ORIGIN_WHITELIST = ("https://storage.googleapis.com",)

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

LANGUAGE_CODE = env_str("DJANGO_LANGUAGE_CODE", "en")
TIME_ZONE = env_str("DJANGO_TIME_ZONE", "UTC")
SYSTEM_TIME_ZONE = env_str("SYSTEM_TIME_ZONE", "UTC")
USE_I18N = env_bool("DJANGO_USE_I18N", True)
USE_L10N = env_bool("DJANGO_USE_L10N", True)
USE_TZ = env_bool("DJANGO_USE_TZ", True)

LANGUAGES = [
    ("en", "English"),
    ("es", "Spanish"),
]

CONFIGURATION = env_str(
    "DJANGO_CONFIGURATION",
)

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = env_str("DJANGO_STATIC_URL", "/static/")

# Google
GOOGLE_API_KEY = env_str("DJANGO_GOOGLE_API_KEY")
# DEFAULT_FILE_STORAGE = env_str('DJANGO_', )
GS_BUCKET_NAME = env_str("DJANGO_GS_BUCKET_NAME")
GS_DIR = env_str("DJANGO_GS_DIR")

GOOGLE_APPLICATION_CREDENTIALS = env_str("GOOGLE_APPLICATION_CREDENTIALS")
GOOGLE_MAPS_API_KEY = env_str("GOOGLE_MAPS_API_KEY")

ROCKETCHAT_URL = env_str("ROCKETCHAT_URL", "")
ROCKETCHAT_API_USER_ID = env_str("ROCKETCHAT_API_USER_ID", "")
ROCKETCHAT_API_AUTH_TOKEN = env_str("ROCKETCHAT_API_AUTH_TOKEN", "")

# Load Auth0 application settings into memory
AUTH0_DOMAIN = os.environ.get("AUTH0_DOMAIN")
AUTH0_CLIENT_ID = os.environ.get("AUTH0_CLIENT_ID")
AUTH0_CLIENT_SECRET = os.environ.get("AUTH0_CLIENT_SECRET")
AUTH0_CLIENT_SCOPES = os.environ.get(
    "AUTH0_CLIENT_SCOPES", "openid profile email read:users create:users update:users"
)
# OIDC discovery URL override. On Auth0 the discovery doc lives at the same
# host as the login UI, so AUTH0_DOMAIN is enough — `https://<domain>/.well-known/openid-configuration`
# is correct. Other OIDC providers (notably AWS Cognito) split the two:
# the hosted-UI domain serves /oauth2/authorize and /logout, but the
# discovery doc lives at `cognito-idp.<region>.amazonaws.com/<pool-id>`.
# When set, AUTH0_SERVER_METADATA_URL overrides the constructed default
# without disturbing the login/logout flow that still uses AUTH0_DOMAIN.
AUTH0_SERVER_METADATA_URL = os.environ.get("AUTH0_SERVER_METADATA_URL")
logger.warning(
    f"[Auth0] AUTH0_DOMAIN={AUTH0_DOMAIN!r} AUTH0_SERVER_METADATA_URL={AUTH0_SERVER_METADATA_URL!r}"
)
AUTH0_DATABASE_CONNECTION_ID = os.environ.get(
    "AUTH0_DATABASE_CONNECTION_ID", "Username-Password-Authentication"
)
CLIENT_SESSION_API_KEY = os.environ.get("CLIENT_SESSION_API_KEY")

# EMail Configuration
AWS_SES_REGION_NAME = os.environ.get("AWS_SES_REGION_NAME", "us-west-2")
AWS_SES_REGION_ENDPOINT = os.environ.get("AWS_SES_REGION_ENDPOINT", "email.us-west-2.amazonaws.com")
EMAIL_BACKEND = env_str("DJANGO_EMAIL_BACKEND", "django_ses.SESBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 25))
FROM_EMAIL = os.environ.get("FROM_EMAIL", "no-reply@example.com")

# Public URL the frontend is reachable at — used to build absolute
# links inside outbound mail (invitation accept URLs, etc.) AND to
# embed the public webhook URL in the GitHub App manifest. Default
# is empty so the GitHub-manifest start view can fall back to
# request.build_absolute_uri() in dev. Production installs MUST set
# APP_BASE_URL explicitly — otherwise GitHub rejects the manifest with
# "Hook url is not supported because it isn't reachable over the
# public Internet (localhost)".
APP_BASE_URL = os.environ.get("APP_BASE_URL", "").rstrip("/")


# Firebase configuration
def var2file(variable):
    if (content := os.environ.get(variable)) is None:
        return None
    if os.path.exists(content):
        return content
    filename = f"/tmp/{variable}"
    with open(filename, "w") as stream:
        stream.write(content)
    return filename


# firebase credentials
FIREBASE_ADMIN_SDK = var2file("FIREBASE_ADMIN_SDK")

# Start of AWS Buckets
USE_S3 = env_bool("USE_S3", True)

if USE_S3:
    # aws / s3-compatible settings (works with AWS S3, MinIO, etc.)
    SERVER_NAME = env_str("SERVER_NAME", "localhost")
    AWS_ACCESS_KEY_ID = env_str("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env_str("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env_str("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = env_str("AWS_S3_ENDPOINT_URL", "")  # MinIO: http://minio-local:9000
    AWS_S3_CUSTOM_DOMAIN = env_str("AWS_S3_CUSTOM_DOMAIN", "")
    if not AWS_S3_CUSTOM_DOMAIN:
        if AWS_S3_ENDPOINT_URL:
            AWS_S3_CUSTOM_DOMAIN = None  # Let boto3 use endpoint URL directly
        else:
            AWS_S3_CUSTOM_DOMAIN = f"static.{SERVER_NAME.replace('local', 'dev')}"
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True  # Required for pre-signed URLs with MinIO

    # s3 static settings
    AWS_LOCATION = ""
    STATIC_URL = "/static/"
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            # WhiteNoise's CompressedManifest storage hashes asset filenames so
            # browsers can cache aggressively, and pre-generates gzip/brotli
            # alongside originals so the runtime serve is just a file read.
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    STATIC_ROOT = os.path.join(BASE_DIR, "assets")
else:
    STATIC_URL = "/staticfiles/"
    STATIC_ROOT = os.path.join(BASE_DIR, "assets")

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

MEDIA_URL = "/mediafiles/"
MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")

# MEDIA_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# End of AWS Buckets

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    DEFAULT_DB_ALIAS: {
        "ENGINE": env_str("POSTGRES_ENGINE"),
        "NAME": env_str("POSTGRES_DB"),
        "USER": env_str("POSTGRES_USER"),
        "PASSWORD": env_str("POSTGRES_PASSWORD"),
        "HOST": env_str("POSTGRES_HOST"),
        "PORT": env_str("POSTGRES_PORT"),
        "OPTIONS": {"options": "-c search_path=public"},
    },
}

DATABASE_ROUTERS = []

CACHES = {
    DEFAULT_CACHE_ALIAS: {
        # 'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("DJANGO_CACHE_URL"),
    },
    "memory_cache": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
}

# OpenSearch
OPENSEARCH_URL = os.environ.get("OPENSEARCH_URL", "http://localhost:9200")
# Indexing is opt-in; staging/prod set OPENSEARCH_INDEXING=1.
# Off by default keeps test/local stacks free of NXDOMAIN noise from
# the indexing signals when no OpenSearch host is reachable.
OPENSEARCH_INDEXING = os.environ.get("OPENSEARCH_INDEXING", "").lower() in ("1", "true", "yes", "on")

CSRF_TRUSTED_ORIGINS = [
    "https://storage.googleapis.com/",
    "http://localhost:3000",
    "http://localhost:80",
    "https://localhost:443",
    "https://localhost:8443",
]

# Application definition
INSTALLED_APPS = [
    # Start of Django Standard
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "strawberry_django",
    "phonenumber_field",
    "core",
    "rolepermissions",
    "django_filters",
    "djmoney",
    "nested_admin",
    "sslserver",
    "storages",
    "django_crontab",
    "import_export",
    "simple_history",
    "workflows",
    # End of Django Standard
    # Start of Email
    "django_ses",
    # End of Email
    # Start of health_check
    "health_check",  # required
    "health_check.db",  # stock Django health checkers
    "health_check.cache",
    "health_check.storage",
    "health_check.contrib.migrations",
    # End of health_check
    # Start of Astrolift
    "auth1",
    "config.middleware",
    "organization",
    "core_logs",
    # Canonical Astrolift platform apps (control-plane data model)
    "astrolift_identity",
    "astrolift_clusters",
    "astrolift_registry",
    "astrolift_lifecycle",
    "astrolift_services",
    "astrolift_operations",
    "astrolift_observability",
    "astrolift_billing",
    "astrolift_scm",
    "astrolift_forms",
    # End of Astrolift
    "constance",
    "constance.backends.database",
]

# Feature toggles — remove disabled feature apps
from config.features import filter_installed_apps  # noqa: E402

INSTALLED_APPS = filter_installed_apps(INSTALLED_APPS)

# `testdata` ships the dev seed fixtures + the `seed` management
# command. It's harmless in any environment (only adds management
# commands and fixtures, no migrations of its own) and is needed by
# the test suite regardless of CONFIGURATION value.
if "testdata" not in INSTALLED_APPS:
    INSTALLED_APPS.append("testdata")

# Discover and merge domain app configurations
# Domain apps declare their configuration
# in astrolift_config/settings.py files
logger.info("Discovering domain apps...")
from config.config_merger import ConfigMerger  # noqa: E402

config_merger = ConfigMerger(BASE_DIR)
config_merger.discover()

# Merge INSTALLED_APPS from domain apps
DOMAIN_APPS = config_merger.get_installed_apps()
INSTALLED_APPS.extend(DOMAIN_APPS)
logger.info(f"Added {len(DOMAIN_APPS)} domain app(s) to INSTALLED_APPS")

# Merge MIDDLEWARE from domain apps
DOMAIN_MIDDLEWARE = config_merger.get_middleware()
if DOMAIN_MIDDLEWARE:
    # MIDDLEWARE will be extended after it's defined below
    pass

# Merge custom settings from domain apps
config_merger.merge_settings(globals())

CRONJOBS = []

# Temporal durable-workflow enable flag. Default ON; set
# ASTROLIFT_TEMPORAL_ENABLED=false at deploy time to disable globally
# (e.g. compose stacks without a Temporal server). Operators can also
# flip this at runtime via the Constance entry below — Constance wins
# when set, the env var is the seed default on first boot.
ASTROLIFT_TEMPORAL_ENABLED = env_bool("ASTROLIFT_TEMPORAL_ENABLED", True)

# Deploy-pipeline gate. Default ON. Seeded from FEATURE_DEPLOY_PIPELINE
# at boot, runtime-toggleable via /app/admin/constance/ so operators
# can pause start/promote/rollback/teardown without a redeploy
# (parity with TEMPORAL_ENABLED). When False every gated mutation
# returns a PRECONDITION envelope; cluster adoption is not gated.
ASTROLIFT_DEPLOY_PIPELINE_ENABLED = env_bool("FEATURE_DEPLOY_PIPELINE", True)

CONSTANCE_CONFIG = {
    "TIME_ZONE": (TIME_ZONE, "System timezone"),
    "PUT_PRESIGNED_URL_EXPIRATION": (60, "Time to live in seconds of presigned urls for uploading."),
    "GET_PRESIGNED_URL_EXPIRATION": (3600, "Time to live in seconds of presigned urls for downloading."),
    "AUTH0_REGISTER_NEW_USER": (False, "Register new users in Auth0"),
    "SEARCH_PROFILE_ENABLED": (False, "Enables opensearch for profile search"),
    "EMAIL_NOTIFICATIONS": (False, "Enables the platform to send Email Notifications"),
    "TEMPORAL_ENABLED": (
        ASTROLIFT_TEMPORAL_ENABLED,
        "Enable the durable-workflow runtime. When False the client returns synthetic handles "
        "instead of starting workflows — useful for dev/test envs without a Temporal server. "
        "Seeded from the ASTROLIFT_TEMPORAL_ENABLED env var (default True) and can be toggled "
        "at runtime here.",
    ),
    "DEPLOY_PIPELINE_ENABLED": (
        ASTROLIFT_DEPLOY_PIPELINE_ENABLED,
        "Enable the app deploy pipeline (start/promote/rollback/teardown). When False those "
        "mutations short-circuit with a PRECONDITION envelope so operators can pause rollouts "
        "without a redeploy. Cluster adoption (bringClusterIntoManagement) is not gated. "
        "Seeded from the FEATURE_DEPLOY_PIPELINE env var (default True).",
    ),
    "WEBHOOK_SECRET_ROTATION_GRACE_SECONDS": (
        3600,
        "Window (in seconds) the previous webhook subscription secret stays valid after a "
        "rotation. Subscribers verify against the new secret first; on mismatch the platform "
        "falls back to the previous secret until this window expires. Default 1h; bump for "
        "fleets that need a longer rollout window, lower (e.g. 60) after a compromise so the "
        "old secret dies fast.",
    ),
    "DEPLOY_TOKEN_ROTATION_GRACE_SECONDS": (
        86400,
        "Window (in seconds) the previous deploy-token secret stays valid after a rotation "
        "so in-flight CI runs holding the old token finish without failing. Default 24h. "
        "Lower bound 60s, upper bound 7d. Surfaced in the rotate-confirm dialog so operators "
        "see the exact grace they're committing to. Use the explicit ``revokeDeployToken`` "
        "path (or ``immediate=True`` in code) for compromised-token cutover.",
    ),
    "ALLOW_SELF_APPROVE_DEPLOYS": (
        False,
        "When False (default), the user who triggered a deployment cannot also approve it — "
        "compliance + separation-of-duties. Flip to True for single-engineer / dev orgs that "
        "still want the deploy-approval audit trail without blocking on a second approver. "
        "Per-deployment auditability is unchanged either way.",
    ),
    "AUDIT_RETENTION_DAYS": (
        90,
        "How long audit log entries are retained, in days, per compliance policy. Surfaces "
        "as a subtitle on the /audit page so operators see the policy at a glance. The "
        "retention sweeper honours this value; bumping it lengthens the visible history "
        "without redeploy. Lower bound 1 day, upper bound 2557 days (~7 years, the spec "
        "ceiling).",
    ),
    "AUDIT_EXPORT_DOWNLOAD_TTL_SECONDS": (
        3600,
        "How long a generated audit-export download URL stays valid before the token "
        "expires (default 1h). Lengthen for fleets that need to hand off the URL to a "
        "third-party auditor; shorten after an incident.",
    ),
    "AUDIT_EXPORT_MAX_ROWS": (
        100000,
        "Hard cap on the row count a single exportAuditEvents call will dump. Protects "
        "the worker from runaway exports while still leaving room for multi-year SOC2 "
        "extracts at the default retention.",
    ),
}

CONSTANCE_CONFIG_FIELDSETS = {
    "System": {
        "fields": ("TIME_ZONE", "PUT_PRESIGNED_URL_EXPIRATION", "GET_PRESIGNED_URL_EXPIRATION"),
        "collapse": False,
    },
    "Auth0": {"fields": ("AUTH0_REGISTER_NEW_USER",), "collapse": False},
    "Search": {"fields": ("SEARCH_PROFILE_ENABLED",), "collapse": False},
    "Notifications": {"fields": ("EMAIL_NOTIFICATIONS",), "collapse": False},
    "Workflows": {
        "fields": ("TEMPORAL_ENABLED", "DEPLOY_PIPELINE_ENABLED", "ALLOW_SELF_APPROVE_DEPLOYS"),
        "collapse": False,
    },
    "Webhooks": {"fields": ("WEBHOOK_SECRET_ROTATION_GRACE_SECONDS",), "collapse": False},
    "Deploy tokens": {
        "fields": ("DEPLOY_TOKEN_ROTATION_GRACE_SECONDS",),
        "collapse": False,
    },
    "Audit": {
        "fields": (
            "AUDIT_RETENTION_DAYS",
            "AUDIT_EXPORT_DOWNLOAD_TTL_SECONDS",
            "AUDIT_EXPORT_MAX_ROWS",
        ),
        "collapse": False,
    },
}

INTERNAL_IPS = [
    "127.0.0.1",
]

DEBUG_TOOLBAR_CONFIG = {
    # Gate the toolbar on a dedicated env var instead of just DEBUG so prod
    # installs (which keep DEBUG=True for error-page debugging) can still
    # hide DJT — it leaks internal SQL / settings / cache details to anyone
    # who can reach the page and adds noticeable per-request overhead.
    "SHOW_TOOLBAR_CALLBACK": lambda request: env_bool("ASTROLIFT_ENABLE_DJT", False),
    # Allow test runs without removing debug_toolbar from INSTALLED_APPS
    "IS_RUNNING_TESTS": False,
}

# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django_ratelimit.middleware.RatelimitMiddleware",
    # Determines Ip ranges supported, specific hosts are managed via the ALLOWED_HOSTS setting in each env
    "config.middleware.allow_cidr_hosts.AllowCIDRHostsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves collected static files (admin css/js, etc.) directly
    # from the app server. Must come immediately after SecurityMiddleware per
    # https://whitenoise.readthedocs.io/.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "auth1.middleware.Auth0SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.auth.middleware.RemoteUserMiddleware",  # Required for Auth0
    # API token bearer auth (#428): resolves alft_at_… tokens, stamps
    # last_used_* columns, swaps in the token owner so resolvers see
    # the correct request.user. Runs after AuthenticationMiddleware
    # so it can override the anonymous user it just set, and before
    # CurrentUserMiddleware so the thread-local picks up the
    # token-authed identity.
    "astrolift_identity.middleware.ApiTokenAuthMiddleware",
    # Deploy-token bearer auth (#425): resolves alft_dt_… tokens for
    # CI deploys, stamps last_used_* columns onto the matched
    # DeployToken row, attaches the row to request._deploy_token so
    # downstream views can read the app binding without re-verifying.
    # Doesn't swap request.user — deploy tokens are app-scoped
    # credentials with their own permission model.
    "astrolift_lifecycle.middleware.DeployTokenAuthMiddleware",
    "core.middleware.current_user.CurrentUserMiddleware",  # Track current user for signals
    "core.middleware.request_id.RequestIdMiddleware",  # ULID + W3C traceparent → contextvar
    "core.middleware.tenant.TenantContextMiddleware",  # Resolve org/team/project, populate TenantContext
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'django.middleware.gzip.GZipMiddleware',
]

TEMPLATES_CACHE_BACKEND = DEFAULT_CACHE_ALIAS

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "config/templates/")],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                        "core.loaders.template.Loader",
                    ],
                ),
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    # 'config.backend.MagicBackend',
]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DATE_INPUT_FORMATS": [
        "%Y-%m-%d",  # 1962-08-15
        "%Y-%m-%dT%H:%M:%S",  # 1962-08-15T00:00:00
        "iso-8601",  # keep DRF's default
    ],
    "DATETIME_INPUT_FORMATS": [
        "%Y-%m-%dT%H:%M:%S",  # 1962-08-15T00:00:00
        "iso-8601",
    ],
}

# Rate limiting
RATELIMIT_VIEW = "django.views.defaults.permission_denied"

# Temporal — durable workflow runtime
TEMPORAL_ADDRESS = env_str("TEMPORAL_ADDRESS", "localhost:7233")
TEMPORAL_NAMESPACE = env_str("TEMPORAL_NAMESPACE", "default")
TEMPORAL_TASK_QUEUE = env_str("TEMPORAL_TASK_QUEUE", "astrolift-main")


# Structured logging: JSON in non-local envs, human-readable text
# locally. ``core.logging.build_logging_config`` is the single source
# of truth — set ``LOG_FORMAT`` (``json`` | ``text`` | ``ecs``),
# ``LOG_LEVEL`` (default ``INFO``), and ``LOG_DESTINATION``
# (``stdout`` | ``stderr``) to override.
TELEMETRY_LOGS = env_bool("TELEMETRY_LOGS", True)
LOG_LEVEL = env_str("LOG_LEVEL", env_str("DJANGO_LOG_LEVEL", "INFO"))
LOG_FORMAT = env_str("LOG_FORMAT", "json")
LOG_DESTINATION = env_str("LOG_DESTINATION", "stdout")

from core.logging import build_logging_config  # noqa: E402

LOGGING = build_logging_config(
    level=LOG_LEVEL,
    format_=LOG_FORMAT,
    destination=LOG_DESTINATION,
)

# ================ DEV
CONFIGURATION = env_str("DJANGO_CONFIGURATION", "Dev")
logger.warning(f"DJANGO_CONFIGURATION: {CONFIGURATION}")

SENTRY_DSN = env_str("SENTRY_DSN")

match CONFIGURATION.lower():
    case "stg" | "dev" | "prd" | "prod":
        if SENTRY_DSN:
            sentry_sdk.init(
                dsn=SENTRY_DSN,
                traces_sample_rate=1.0,
                profiles_sample_rate=1.0,
                environment=CONFIGURATION,
            )
        else:
            logger.info("Sentry DSN not configured; skipping Sentry init")
    case _:
        logger.info(f"Sentry is not enabled for configuration: {CONFIGURATION}")

ALLOWED_HOSTS = [
    "*",
]

IS_PROD = CONFIGURATION.lower() == "prd"
IS_DEV = CONFIGURATION.lower() == "dev" or CONFIGURATION.lower() == "local"
IS_LOCAL = CONFIGURATION.lower() in ("local", "localpg", "localverbose")

if CONFIGURATION.lower() == "Prd".lower():
    DEBUG = True
    AUTH_PASSWORD_VALIDATORS = []
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "*"]
elif CONFIGURATION.lower() == "Dev".lower():
    DEBUG = True
    AUTH_PASSWORD_VALIDATORS = []
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "*"]

elif CONFIGURATION.lower() == "int":
    DEBUG = True
    AUTH_PASSWORD_VALIDATORS = []
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "*"]

elif CONFIGURATION.lower() == "stg":
    DEBUG = True
    AUTH_PASSWORD_VALIDATORS = []
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "*"]
elif CONFIGURATION.lower() == "Tests".lower():
    DEBUG = True
    SECRET_KEY = "not-a-secret"
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}}
    CACHES = {
        DEFAULT_CACHE_ALIAS: {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        },
        "memory_cache": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        },
    }
    # testdata already appended unconditionally above.
elif CONFIGURATION.lower() == "Local".lower() or CONFIGURATION.lower() == "LocalPG".lower():
    DEBUG = True
    ALLOWED_HOSTS = [
        "*",
    ]
    AUTH_PASSWORD_VALIDATORS = []
    DEFAULT_USER_TEST = env_str(
        "DJANGO_", "admin"
    )  # only for local login the user if there is no user logged in
    TELEMETRY_LOGS = False
    # testdata already appended unconditionally above.
    LOGGING = build_logging_config(
        level=LOG_LEVEL,
        format_=env_str("LOG_FORMAT", "text"),
        destination=LOG_DESTINATION,
    )
elif CONFIGURATION.lower() == "LocalVerbose".lower():
    DEBUG = True
    ALLOWED_HOSTS = [
        "*",
    ]
    AUTH_PASSWORD_VALIDATORS = []
    DEFAULT_USER_TEST = env_str(
        "DJANGO_", "admin"
    )  # only for local login the user if there is no user logged in
    TELEMETRY_LOGS = False
    LOGGING = build_logging_config(
        level=env_str("LOG_LEVEL", "DEBUG"),
        format_=env_str("LOG_FORMAT", "text"),
        destination=LOG_DESTINATION,
    )
else:
    DEBUG = True
    SECRET_KEY = "not-a-secret"
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}}
    CACHES = {
        DEFAULT_CACHE_ALIAS: {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        },
        "memory_cache": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        },
    }

logger.warning(f"Settings Version - End: {VERSION}")
logger.warning(f"DATABASE: {DATABASES[DEFAULT_DB_ALIAS]['ENGINE']}")
logger.warning(f"DB NAME: {DATABASES[DEFAULT_DB_ALIAS]['NAME']}")
if "USER" in DATABASES[DEFAULT_DB_ALIAS]:
    logger.warning(f"DB USER: {DATABASES[DEFAULT_DB_ALIAS]['USER']}")
logger.warning(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")


# multiple import options
IMPORT_FORMATS = [JSON]

# single export options
EXPORT_FORMATS = [JSON, TSV, CSV, XLSX]

# Twilio Settings
TWILIO_SID = os.getenv("TWILIO_SID", "")
TWILIO_SECRET = os.getenv("TWILIO_SECRET", "")
TWILIO_FROM_NUMBER = os.getenv("TWILIO_FROM_NUMBER", "")
TWILIO_CALLBACK = os.getenv("TWILIO_CALLBACK", "")

# Start of Metabase Config
METABASE_SITE_URL = env_str("METABASE_SITE_URL", "")
METABASE_SECRET_KEY = env_str("METABASE_SECRET_KEY", "")
METABASE_BACKEND_API_KEY = env_str("METABASE_BACKEND_API_KEY", "")

logger.warning(f"METABASE_URL = {METABASE_SITE_URL}")
logger.warning(f"METABASE_SECRET_KEY = {METABASE_SECRET_KEY}")
