# Generated by Django 6.0.5 on 2026-05-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0003_append_only_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deployment',
            name='ci_actor_kind',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deployment',
            name='ci_provider',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deployment',
            name='ci_run_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deployment',
            name='commit_sha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
