# Generated by Django 6.0.5 on 2026-05-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0004_deployment_branch_deployment_ci_actor_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytoken',
            name='last_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploytoken',
            name='previous_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploytoken',
            name='previous_token_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
