# Generated by Django 6.0.5 on 2026-05-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0005_deploytoken_last_rotated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='approval_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approval_token_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approval_token_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
