# Generated by Django 6.0.5 on 2026-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0006_deployment_approval_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='expected_cname_target',
            field=models.CharField(blank=True, default='', help_text="Cluster ingress hostname the operator's CNAME should point at. Captured at addAppDomain time so the operator sees a stable target even if the cluster's resolver shape changes later.", max_length=255),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='is_platform_managed_zone',
            field=models.BooleanField(default=False, help_text="True when the hostname's parent zone matches a row in ``ManagedDomain`` — the platform owns the zone and creates the records automatically. False when the operator's authoritative DNS is somewhere the platform can't write to and they have to add records themselves."),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='last_validation_error',
            field=models.CharField(blank=True, default='', help_text="Operator-facing reason the most recent validation pass failed (e.g., 'TXT record not found at _astrolift-challenge.example.com — still propagating?'). Cleared on successful validation.", max_length=512),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='required_dns_records',
            field=models.JSONField(blank=True, default=list, help_text="List of ``{kind, name, value, ttl, propagated, last_checked_at, message}`` rows the operator must add to their authoritative DNS for the hostname to validate. When the parent zone is platform-managed, the platform creates these via ``DnsDriver.ensure_record`` and the rows reflect the platform's own create state."),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='txt_challenge_token',
            field=models.CharField(blank=True, default='', help_text='Random token the operator pastes into a TXT record at ``_astrolift-challenge.<hostname>`` so DNS-TXT validation can confirm they control the hostname.', max_length=64),
        ),
        migrations.AlterField(
            model_name='customdomain',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('validated', 'Validated'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
