# Generated by Django 6.0.5 on 2026-05-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0007_customdomain_expected_cname_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='byo_certificate_pem',
            field=models.TextField(blank=True, default='', help_text="Operator-uploaded certificate chain (PEM) for the BYO path — used when the platform can't auto-issue (AWS with externally-managed DNS, LE rate-limited zones, custom CA). Write-only via GraphQL; never echoed back."),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='byo_certificate_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='certificate_state',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('issuing', 'Issuing'), ('active', 'Active'), ('failed', 'Failed'), ('byo', 'Byo')], default='not_requested', help_text="not_requested: validation hasn't completed yet. issuing: ensure_certificate fired; provider still provisioning. active: cert is usable by the renderer. failed: cert issuance failed — operator action needed (BYO cert, switch validation method, etc.). byo: operator uploaded a cert via ``uploadCustomDomainCertificate``, bypassing auto-issuance.", max_length=16),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='last_certificate_error',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
