# Generated by Django 6.0.5 on 2026-05-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0008_customdomain_byo_certificate_pem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appenvironment',
            name='ingress_paused',
            field=models.BooleanField(default=False),
        ),
    ]
