# Generated by Django 6.0.5 on 2026-05-31 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0026_merge_0025_agentrun_log_excerpt_0025_function_invocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='functioninvocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='functioninvocation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='functioninvocation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='functioninvocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='log_excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customdomain',
            name='cert_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Cached ``not_after`` from the TLS driver's ``list_certificates`` call.  Null when no certificate has been issued yet (state ``not_requested`` / ``issuing``) or the driver returned no row.  The FE renders 'expires in N days' off this column and dots the chip warning when less than 14 days.", null=True),
        ),
        migrations.AlterField(
            model_name='customdomain',
            name='cert_issuer_serial',
            field=models.CharField(blank=True, default='', help_text="Stable identifier for the current cert across renewals — the ACM ARN, the Let's Encrypt serial, etc.  Lets the renewal workflow observe a renewal landing (the serial changes) versus the same cert living on past its originally-issued date (the serial holds steady).", max_length=255),
        ),
        migrations.AlterField(
            model_name='customdomain',
            name='cert_metadata_refreshed_at',
            field=models.DateTimeField(blank=True, help_text="Last time the resolver's lazy refresher (or the renewal workflow) updated cert_expires_at / cert_issuer_serial / cert_observability_status.  Reads older than 1h trigger a background refresh; null forces a refresh on the next read.", null=True),
        ),
        migrations.AlterField(
            model_name='customdomain',
            name='cert_observability_status',
            field=models.CharField(blank=True, default='', help_text="Driver-reported renewal status the FE colours the chip off ('auto' / 'manual' / 'failed' / 'unknown').  Empty string when never populated; the FE renders the chip neutral in that case.", max_length=32),
        ),
        migrations.AlterField(
            model_name='functioninvocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='functioninvocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
