# Generated by Django 6.0.5 on 2026-07-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0027_agentrun_created_by_agentrun_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='github_deployment_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
