"""The cross-domain session handoff token (#1631).

Purely additive: one new table, no column touched on any existing one, so
nothing on the deploy path changes shape when this lands.

The table is expected to be write-heavy on the login path and short-lived
per row -- a 60-second TTL and one row per custom-domain login -- which is
why ``core.domain_handoff.purge_expired_handoffs`` hard-deletes rather than
soft-deleting. See the model docstring for why each field is load-bearing.
"""

# Generated by Django 6.0.5 on 2026-08-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0032_orgsecret'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSessionHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text="The audience, denormalised from the domain at mint time and compared on exchange. Denormalised on purpose: renaming the domain row must not silently widen an already-minted token's audience to the new hostname.", max_length=255)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the plaintext; the plaintext is never stored.', max_length=64, unique=True)),
                ('subject', models.CharField(help_text="The verified IdP subject the auth host authenticated. The domain's proxy mints its own session from this rather than receiving a copy of the auth host's.", max_length=255)),
                ('email', models.EmailField(blank=True, default='', help_text='Verified email claim when the IdP supplies one; blank otherwise.', max_length=254)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, help_text='Stamped by the conditional UPDATE in ``consume_domain_handoff``. Non-null means spent; a second exchange attempt is a replay.', null=True)),
                ('custom_domain', models.ForeignKey(help_text="The domain this grant is for. Carried as a relation rather than a bare hostname so 'who established a session on which custom domain' resolves to an app and an org for audit.", on_delete=django.db.models.deletion.CASCADE, related_name='session_handoffs', to='astrolift_lifecycle.customdomain')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='domainhandoff_expires_idx'), models.Index(fields=['hostname', 'consumed_at'], name='domainhandoff_host_idx')],
            },
        ),
    ]
