# Generated by Django 6.0.5 on 2026-08-25 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0034_appenvironment_previewed_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='edge_auth_enabled',
            field=models.BooleanField(default=False, help_text="Opt this domain into the cluster's edge auth gate via a first-party /oauth2 endpoint on the domain itself (#1631). Default off, and that default is load-bearing: custom domains serve ungated today, so turning the gate on is a behaviour change for live traffic -- answering a silent security gap with a silent outage is not an improvement. Per-domain rather than per-app deliberately: an app routinely carries several hostnames (a marketing site and an admin console are the same app), and gating is the decision most likely to differ between them. A per-app flag would force the public hostname behind a login to protect the private one. Setting this alone gates nothing -- the cluster also needs edge auth configured; see core.app_deploy.custom_domain_edge_auth_state."),
        ),
        migrations.AlterField(
            model_name='appenvironment',
            name='previewed_environment',
            field=models.ForeignKey(blank=True, help_text='For a preview environment, the environment it is a preview OF (#1578 feature 2). Null on every non-preview environment, and null on a preview whose app has no non-preview environment on the same cluster to point at.\n\nExists because a preview could not previously answer that question at all: `PreviewEnvironment` carries the app, the PR number, the branch and its own `AppEnvironment`, and nothing linked back to a primary. So there was no declared source for which managed services a preview should get -- a preview owns zero `ManagedService` rows and inherits none, and the deploy render only synthesizes the bindings Secret when that set is non-empty, so a preview workload boots with no DB / redis / queue envelope.\n\n`SET_NULL` rather than `CASCADE`: deleting a production environment must not delete the previews pointing at it. They become orphaned previews, which is recoverable; cascading would silently destroy live PR environments as a side effect of retiring an environment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previews', to='astrolift_lifecycle.appenvironment'),
        ),
    ]
