# Generated by Django 6.0.5 on 2026-09-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0035_customdomain_edge_auth_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='build_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
