# Generated by Django 6.0.5 on 2026-09-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0036_deployment_build_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='devenvironment',
            name='data_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devenvironment',
            name='data_file_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
