# Generated by Django 6.0.5 on 2026-09-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_lifecycle", "0038_backfill_devenvironment_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="secret_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
