# Generated by Django 6.0.5 on 2026-09-30 05:08

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("astrolift_lifecycle", "0044_deployment_approval_identities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymentlog",
            name="status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="deploymentlog",
            name="event",
            field=models.CharField(blank=True, db_default="", default="", max_length=32),
        ),
        migrations.AddField(
            model_name="deploymentlog",
            name="phase",
            field=models.CharField(blank=True, db_default="", default="", max_length=16),
        ),
        AddIndexConcurrently(
            model_name="deploymentlog",
            index=models.Index(fields=["deployment", "id"], name="deploylog_cursor_idx"),
        ),
    ]
