# Generated by Django 6.0.5 on 2026-10-04 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def refuse_retained_origins(apps, schema_editor):
    model = apps.get_model("astrolift_lifecycle", "DeploymentIdentityOrigin")
    if model._base_manager.using(schema_editor.connection.alias).exists():
        raise RuntimeError("DEPLOYMENT_ORIGIN_ROLLBACK_REQUIRES_EMPTY_HISTORY")


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_identity", "0042_team_membership_actions"),
        ("astrolift_lifecycle", "0045_deployment_run_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentIdentityOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("authority_reference", models.JSONField()),
                ("authority_sha256", models.CharField(max_length=64)),
                ("deployment_binding", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_origin",
                        to="astrolift_lifecycle.deployment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION astrolift_refuse_deployment_origin_mutation() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'DEPLOYMENT_ORIGIN_IMMUTABLE';
            END;
            $$;
            CREATE TRIGGER deployment_origin_immutable
            BEFORE UPDATE OR DELETE ON astrolift_lifecycle_deploymentidentityorigin
            FOR EACH ROW EXECUTE FUNCTION astrolift_refuse_deployment_origin_mutation();
            """,
            reverse_sql="""
            DROP TRIGGER deployment_origin_immutable ON astrolift_lifecycle_deploymentidentityorigin;
            DROP FUNCTION astrolift_refuse_deployment_origin_mutation();
            """,
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=refuse_retained_origins),
    ]
