# Generated by Django 6.0.5 on 2026-10-04 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def refuse_retained_execution(apps, schema_editor):
    model = apps.get_model("astrolift_lifecycle", "DeploymentExecutionReceipt")
    if model._base_manager.using(schema_editor.connection.alias).exists():
        raise RuntimeError("DEPLOYMENT_EXECUTION_ROLLBACK_REQUIRES_EMPTY_HISTORY")


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_identity", "0042_team_membership_actions"),
        ("astrolift_lifecycle", "0046_deploymentidentityorigin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentExecutionReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("EXPECTED", "Expected"), ("BOUND", "Bound")],
                        max_length=8,
                    ),
                ),
                ("workflow_id", models.CharField(max_length=256)),
                ("workflow_type", models.CharField(max_length=64)),
                ("run_id", models.CharField(blank=True, max_length=64)),
                ("input_sha256", models.CharField(max_length=64)),
                ("operation_uuid", models.UUIDField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_lifecycle.deployment",
                    ),
                ),
                (
                    "expected",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_lifecycle.deploymentexecutionreceipt",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_lifecycle.deploymentidentityorigin",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment", "kind"),
                        name="deployment_execution_kind_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expected__isnull", True),
                                ("kind", "EXPECTED"),
                                ("run_id", ""),
                            ),
                            models.Q(
                                ("expected__isnull", False),
                                ("kind", "BOUND"),
                                models.Q(("run_id", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="deployment_execution_receipt_shape",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION astrolift_refuse_deployment_execution_mutation() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'DEPLOYMENT_EXECUTION_IMMUTABLE';
            END;
            $$;
            CREATE TRIGGER deployment_execution_immutable
            BEFORE UPDATE OR DELETE ON astrolift_lifecycle_deploymentexecutionreceipt
            FOR EACH ROW EXECUTE FUNCTION astrolift_refuse_deployment_execution_mutation();
            """,
            reverse_sql="""
            DROP TRIGGER deployment_execution_immutable ON astrolift_lifecycle_deploymentexecutionreceipt;
            DROP FUNCTION astrolift_refuse_deployment_execution_mutation();
            """,
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=refuse_retained_execution),
    ]
