# Generated by Django 6.0.5 on 2026-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0003_task_meter_task_token_workflow_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeteringrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tasktoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowwebhook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowwebhook',
            name='input_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="JSONPath / key-mapping spec that maps incoming payload fields to the workflow's input schema."),
        ),
        migrations.AlterField(
            model_name='workflowwebhook',
            name='slug',
            field=models.SlugField(help_text='URL-safe identifier used in the endpoint path.', max_length=64, unique=True),
        ),
    ]
