# Generated by Django 6.0.5 on 2026-06-12 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0004_alter_taskmeteringrecord_id_alter_tasktoken_id_and_more'),
        ('astrolift_registry', '0025_workload_agent_variant_runtime'),
        ('workflows', '0003_historicalworkflowdefinition_pattern_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowwebhook',
            name='registered_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_webhooks', to='astrolift_registry.registeredapp'),
        ),
        migrations.AddIndex(
            model_name='workflowwebhook',
            index=models.Index(fields=['registered_app', 'enabled'], name='wfwebhook_app_enabled_idx'),
        ),
    ]
