# Generated by Django 6.0.5 on 2026-06-12 06:21

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0004_alter_taskmeteringrecord_id_alter_tasktoken_id_and_more'),
        ('astrolift_identity', '0017_userpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='pod_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='source_ref',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='skill',
            name='agent_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='scaffolding_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tooldef',
            name='agent_type_bindings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tooldef',
            name='capability_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tooldef',
            name='commands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tooldef',
            name='is_builtin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tooldef',
            name='required_packages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AgentEnvironmentSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=128)),
                ('image_tag', models.CharField(max_length=512)),
                ('agent_type', models.CharField(choices=[('claude', 'Claude'), ('codex', 'Codex')], max_length=50)),
                ('tool_preset', models.CharField(blank=True, default='', max_length=128)),
                ('allow_install', models.BooleanField(default=False)),
                ('vnc_enabled', models.BooleanField(default=False)),
                ('secret_refs', models.JSONField(blank=True, default=list)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('config_repo', models.CharField(blank=True, default='', max_length=512)),
                ('config_branch', models.CharField(default='main', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_environment_specs', to='astrolift_identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agenttask',
            name='environment_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='astrolift_agents.agentenvironmentspec'),
        ),
        migrations.AddIndex(
            model_name='agentenvironmentspec',
            index=models.Index(fields=['organization'], name='agent_env_spec_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentenvironmentspec',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'slug'), name='agent_env_spec_slug_unique_active_per_org'),
        ),
    ]
