# Generated by Django 6.0.5 on 2026-06-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0005_add_registered_app_to_workflow_webhook'),
        ('astrolift_agents', '0006_workflowwebhook_scm_fields'),
    ]

    operations = [
    ]
