# Generated by Django 6.0.5 on 2026-06-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0007_merge_20260612_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='vnc_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='vnc_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
