# Generated by Django 6.0.5 on 2026-06-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0008_agent_task_vnc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentenvironmentspec',
            name='runtime',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='snapshot_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='agentenvironmentspec',
            name='image_tag',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
