# Generated by Django 6.0.5 on 2026-06-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0009_agent_runtime_and_snapshot_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentenvironmentspec',
            name='config_manifest_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
