# Generated by Django 6.0.5 on 2026-06-19 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0012_agentskillref'),
        ('astrolift_identity', '0019_resync_system_roles_agent_workflow'),
        ('astrolift_scm', '0010_source_trigger_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSkillRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('alias', models.CharField(help_text="Short handle a manifest references as '<alias>/<skill-path>@<ref>'.", max_length=128)),
                ('repo_full_name', models.CharField(help_text="owner/repo on the source host, e.g. 'acme/dev-skills'.", max_length=512)),
                ('source_kind', models.CharField(default='github', help_text='Source host: github / gitlab / bitbucket / gitea.', max_length=32)),
                ('default_ref', models.CharField(default='main', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_skill_repos', to='astrolift_identity.organization')),
                ('source_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_skill_repos', to='astrolift_scm.sourceconnection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'is_active'], name='org_skill_repo_org_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'alias'), name='org_skill_repo_alias_unique_active_per_org')],
            },
        ),
    ]
