# Generated by Django 6.0.5 on 2026-06-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0013_orgskillrepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='namespace',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
