# Generated by Django 6.0.5 on 2026-06-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0014_agenttask_namespace"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="dispatch_input",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
