# Generated by Django 6.0.5 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0015_agenttask_dispatch_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentenvironmentspec",
            name="managed_model",
            field=models.BooleanField(default=False),
        ),
    ]
