# Generated by Django 6.0.5 on 2026-07-26 02:35

import core.fields.uuid_v7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0016_agentenvironmentspec_managed_model'),
        ('astrolift_identity', '0019_resync_system_roles_agent_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('control_api', 'Control Api'), ('tool_call', 'Tool Call'), ('signal', 'Signal'), ('gate', 'Gate')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='ok', max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('agent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='astrolift_agents.agenttask')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_interactions', to='astrolift_identity.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['agent_task', 'occurred_at'], name='agentixn_task_time_idx'), models.Index(fields=['organization', '-occurred_at'], name='agentixn_org_time_idx')],
            },
        ),
    ]
