# Generated by Django 6.0.5 on 2026-07-26 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0017_agentinteraction'),
        ('astrolift_lifecycle', '0028_deployment_github_deployment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='agent_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_task', to='astrolift_lifecycle.agentrun'),
        ),
    ]
