# Generated by Django 6.0.5 on 2026-09-16 18:05

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0023_agentbox_drop_session_name'),
        ('astrolift_identity', '0030_organization_image_signing_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='event_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='event_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AgentTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('turn_id', models.CharField(max_length=64)),
                ('message_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('assistant_delta', 'Assistant Delta'), ('terminal_delta', 'Terminal Delta'), ('message_end', 'Message End'), ('input_required', 'Input Required'), ('approval_required', 'Approval Required'), ('input_resolved', 'Input Resolved')], max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('agent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='astrolift_agents.agenttask')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrolift_identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('agent_task', 'sequence'), name='agent_event_task_sequence_uniq')],
            },
        ),
    ]
