# Generated by Django 6.0.5 on 2026-09-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0023_agentbox_drop_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='dispatch_target',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
