# Generated by Django 6.0.5 on 2026-09-16 20:02

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_agents', '0024_agent_task_events'),
        ('astrolift_identity', '0030_organization_image_signing_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTaskInputReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('response', models.JSONField()),
                ('author_label', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agenttaskevent',
            name='request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='agenttaskevent',
            index=models.Index(fields=['agent_task', 'turn_id', 'message_id'], name='agent_event_message_idx'),
        ),
        migrations.AddField(
            model_name='agenttaskinputreply',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenttaskinputreply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='agenttaskinputreply',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenttaskinputreply',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='agenttaskinputreply',
            name='request_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_reply', to='astrolift_agents.agenttaskevent'),
        ),
        migrations.AddField(
            model_name='agenttaskinputreply',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
