# Generated by Django 6.0.5 on 2026-09-17 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0024_agenttask_dispatch_target"),
        ("astrolift_agents", "0025_agent_task_input_replies"),
    ]

    operations = []
