# Generated by Django 6.0.5 on 2026-09-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0026_merge_20260917_0050"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="cancel_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
