# Generated by Django 6.0.5 on 2026-09-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0033_model_gateway_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentenvironmentspec",
            name="gpu",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentenvironmentspec",
            name="gpu_type",
            field=models.CharField(blank=True, default="", max_length=63),
        ),
        migrations.AddField(
            model_name="agentenvironmentspec",
            name="mig_profile",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
