# Generated by Django 6.0.5 on 2026-09-26 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0034_agent_env_spec_gpu"),
        ("astrolift_identity", "0035_alter_organizationmodule_key"),
        ("astrolift_lifecycle", "0039_deployment_secret_snapshot"),
        ("astrolift_operations", "0025_zentinelle_connection"),
        ("astrolift_registry", "0041_populate_hostname_claims"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="client_request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="agenttask",
            constraint=models.UniqueConstraint(
                fields=("organization", "client_request_id"), name="agenttask_org_request_unique"
            ),
        ),
    ]
