# Generated by Django 6.0.5 on 2026-09-26 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0035_agenttask_client_request_id"),
        ("astrolift_identity", "0035_alter_organizationmodule_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentbox",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_boxes",
                to="astrolift_identity.project",
            ),
        ),
        migrations.AddField(
            model_name="agentbox",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_boxes",
                to="astrolift_identity.team",
            ),
        ),
        migrations.AddField(
            model_name="agentenvironmentspec",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="agent_environment_specs",
                to="astrolift_identity.project",
            ),
        ),
        migrations.AddField(
            model_name="agentenvironmentspec",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="agent_environment_specs",
                to="astrolift_identity.team",
            ),
        ),
    ]
