# Generated by Django 6.0.5 on 2026-09-30 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0038_agent_host_projection"),
        ("astrolift_agents", "0039_backfill_agent_spec_and_box_owner"),
    ]

    operations = []
