# Generated by Django 6.0.5 on 2026-09-30 05:00

import core.fields.uuid_v7
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0041_merge_startup_and_backlog"),
        ("astrolift_clusters", "0020_tenantcluster_edge_access_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedBoxRuntime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("owner_epoch", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("api_url", models.URLField(max_length=512)),
                ("workspace_path", models.CharField(max_length=1024)),
                ("namespace", models.CharField(max_length=63)),
                ("job_name", models.CharField(max_length=253)),
                ("job_uid", models.CharField(max_length=128)),
                ("claim_name", models.CharField(max_length=253)),
                ("claim_uid", models.CharField(max_length=128)),
                ("pod_name", models.CharField(max_length=253)),
                ("pod_uid", models.CharField(max_length=128)),
                ("container_name", models.CharField(max_length=63)),
                ("image", models.CharField(max_length=512)),
                ("observed_image_id", models.CharField(max_length=512)),
                (
                    "runtime_instance_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("token_hash", models.CharField(max_length=64)),
                ("token_expires_at", models.DateTimeField()),
                (
                    "box",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="managed_runtime",
                        to="astrolift_agents.agentbox",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="astrolift_clusters.tenantcluster",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("owner_epoch",), name="managed_box_owner_epoch_unique")
                ],
            },
        ),
    ]
