# Generated by Django 6.0.5 on 2026-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0042_managed_box_runtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedboxruntime",
            name="phase",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("certified", "Certified"),
                    ("revoked", "Revoked"),
                ],
                default="certified",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="managedboxruntime",
            name="claim_uid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="managedboxruntime",
            name="job_uid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="managedboxruntime",
            name="observed_image_id",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="managedboxruntime",
            name="pod_name",
            field=models.CharField(blank=True, default="", max_length=253),
        ),
        migrations.AlterField(
            model_name="managedboxruntime",
            name="pod_uid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="managedboxruntime",
            name="token_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
