# Generated by Django 6.0.5 on 2026-10-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0045_task_completion_callbacks_2234"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="completion_usage",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
