# Generated by Django 6.0.5 on 2026-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_agents", "0046_completion_usage_2234"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="dispatch_execution",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
