# Generated by Django 6.0.5 on 2026-06-30 21:11

import core.models.common
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0019_resync_system_roles_agent_workflow'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflows', '0003_historicalworkflowdefinition_pattern_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkflow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stage_bindings', models.JSONField(blank=True, default=dict)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('trigger_kind', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('event', 'Event')], default='manual', max_length=16)),
                ('schedule_cron', models.CharField(blank=True, max_length=128, null=True)),
                ('trigger_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical workflow',
                'verbose_name_plural': 'historical workflows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stage_bindings', models.JSONField(blank=True, default=dict)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('trigger_kind', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('event', 'Event')], default='manual', max_length=16)),
                ('schedule_cron', models.CharField(blank=True, max_length=128, null=True)),
                ('trigger_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
            bases=(core.models.common.ModelPermissionsMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='workflowdefinition',
            name='unique_workflow_per_model',
        ),
        migrations.AddField(
            model_name='historicalworkflowdefinition',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='historicalworkflowinstance',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='historicalworkflowstage',
            name='role',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_definitions', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='role',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalworkflowinstance',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowdefinition'),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='workflowdefinition_org_slug_unique'),
        ),
        migrations.AddField(
            model_name='historicalworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='historicalworkflow',
            name='definition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows.workflowdefinition'),
        ),
        migrations.AddField(
            model_name='historicalworkflow',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalworkflow',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalworkflow',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='historicalworkflow',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='workflows.workflowdefinition'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalworkflowinstance',
            name='configured_workflow',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='configured_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='workflows.workflow'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['organization', 'current_state'], name='workflows_w_organiz_bdcd70_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='workflow_org_slug_unique'),
        ),
    ]
