# Generated by Django 6.0.5 on 2026-06-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_historicalworkflow_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkflowstage',
            name='approvers',
            field=models.JSONField(blank=True, default=list, help_text='Approver references for human_gate/escalation stages (e.g. team or role slugs).'),
        ),
        migrations.AddField(
            model_name='historicalworkflowstage',
            name='fan_out_dynamic',
            field=models.BooleanField(default=False, help_text="When true, spawn count is derived dynamically from the prior stage's output."),
        ),
        migrations.AddField(
            model_name='historicalworkflowstage',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='approvers',
            field=models.JSONField(blank=True, default=list, help_text='Approver references for human_gate/escalation stages (e.g. team or role slugs).'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='fan_out_dynamic',
            field=models.BooleanField(default=False, help_text="When true, spawn count is derived dynamically from the prior stage's output."),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalworkflowstage',
            name='fan_out_count',
            field=models.IntegerField(blank=True, help_text='Static parallel-task count for fan_out stages. Null → none (or dynamic, see fan_out_dynamic).', null=True),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='fan_out_count',
            field=models.IntegerField(blank=True, help_text='Static parallel-task count for fan_out stages. Null → none (or dynamic, see fan_out_dynamic).', null=True),
        ),
    ]
