# Generated by Django 6.0.5 on 2026-07-16 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_identity", "0019_resync_system_roles_agent_workflow"),
        ("workflows", "0006_seed_workflow_catalogue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflow",
            name="workflow_org_slug_unique",
        ),
        migrations.RemoveConstraint(
            model_name="workflowdefinition",
            name="workflowdefinition_org_slug_unique",
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "slug"),
                name="workflow_org_slug_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "slug"),
                name="workflowdefinition_org_slug_unique",
            ),
        ),
    ]
