# Generated by Django 6.0.5 on 2026-10-02 04:06

import core.fields.uuid_v7
import core.run_input_contract
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_identity", "0041_merge_agent_enforcement_scim_groups"),
        ("astrolift_operations", "0028_user_privacy_projection"),
        ("workflows", "0012_workflowstage_workflow_ref"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkflowdefinition",
            name="input_schema",
            field=models.JSONField(default=core.run_input_contract.no_input_schema),
        ),
        migrations.AddField(
            model_name="workflowdefinition",
            name="input_schema",
            field=models.JSONField(default=core.run_input_contract.no_input_schema),
        ),
        migrations.CreateModel(
            name="WorkflowDefinitionStart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("actor_key", models.CharField(max_length=96)),
                ("request_id", models.CharField(max_length=128)),
                ("request_digest", models.CharField(max_length=64)),
                ("definition_revision", models.CharField(max_length=64)),
                ("input_schema_digest", models.CharField(max_length=64)),
                ("payload_backend_kind", models.CharField(max_length=32)),
                ("payload_ciphertext", models.BinaryField()),
                (
                    "dispatch_status",
                    models.CharField(default="reserved", max_length=16),
                ),
                (
                    "dispatch_last_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="start_requests",
                        to="workflows.workflowdefinition",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="definition_start",
                        to="astrolift_operations.workflowrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "actor_key", "request_id"),
                        name="workflow_start_request_unique",
                    )
                ],
            },
        ),
    ]
