# Generated by Django 6.0.5 on 2026-10-02 09:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_registry", "0042_registeredapp_edge_access"),
        ("workflows", "0013_historicalworkflowdefinition_input_schema_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkflowstage",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Maximum attempts per stage visit, including its initial dispatch (1–20).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Maximum attempts per stage visit, including its initial dispatch (1–20).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstage",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1), ("max_attempts__lte", 20)),
                name="workflowstage_attempts_bounded",
            ),
        ),
    ]
