# Generated by Django 6.0.5 on 2026-10-02 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0014_historicalworkflowstage_max_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkflowstage",
            name="back_edge",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional bounded return edge to an earlier stage output_key; max_rounds is required.",
            ),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="caused_by",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="fanout_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="fanout_parent_execution",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workflows.workflowstageexecution",
            ),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="round_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="back_edge",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional bounded return edge to an earlier stage output_key; max_rounds is required.",
            ),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="caused_by",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="fanout_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="fanout_parent_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fanout_children",
                to="workflows.workflowstageexecution",
            ),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="round_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
