# Generated by Django 6.0.5 on 2026-10-02 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0016_seed_bounded_catalogue_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkflowstage",
            name="iteration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Bounded serial body range or supported record formatter configuration.",
            ),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="collection_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="collection_parent_execution",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workflows.workflowstageexecution",
            ),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="collection_workflow_id",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="iteration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Bounded serial body range or supported record formatter configuration.",
            ),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="collection_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="collection_parent_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_children",
                to="workflows.workflowstageexecution",
            ),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="collection_workflow_id",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="historicalworkflowstage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("agent_dispatch", "Agent Dispatch"),
                    ("human_gate", "Human Gate"),
                    ("checkpoint", "Checkpoint"),
                    ("aggregation", "Aggregation"),
                    ("workflow", "Workflow"),
                    ("collection", "Collection"),
                    ("format_record", "Format Record"),
                ],
                default="agent_dispatch",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("agent_dispatch", "Agent Dispatch"),
                    ("human_gate", "Human Gate"),
                    ("checkpoint", "Checkpoint"),
                    ("aggregation", "Aggregation"),
                    ("workflow", "Workflow"),
                    ("collection", "Collection"),
                    ("format_record", "Format Record"),
                ],
                default="agent_dispatch",
                max_length=32,
            ),
        ),
    ]
