# Generated by Django 6.0.5 on 2026-10-05 08:00

from django.db import migrations, models


def track_existing_schedules(apps, schema_editor):
    # Legacy best-effort cleanup can leave schedules even on inactive rows.
    for name in ("Workflow", "HistoricalWorkflow"):
        apps.get_model("workflows", name).objects.using(schema_editor.connection.alias).update(
            schedule_managed=True
        )


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0017_historicalworkflowstage_iteration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkflow",
            name="schedule_managed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="historicalworkflow",
            name="schedule_revision",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="historicalworkflow",
            name="schedule_spec_hash",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="workflow",
            name="schedule_managed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="workflow",
            name="schedule_revision",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="workflow",
            name="schedule_spec_hash",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.RunPython(track_existing_schedules, migrations.RunPython.noop),
    ]
