# Generated by Django 6.0.5 on 2026-10-05 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_lifecycle", "0045_deployment_run_history"),
        ("astrolift_operations", "0029_preview_log_export_source"),
        ("workflows", "0018_schedule_lifecycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="temporal_activity_id",
            field=models.CharField(blank=True, default="", editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="temporal_activity_key",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="temporal_namespace",
            field=models.CharField(blank=True, default="", editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="temporal_run_id",
            field=models.CharField(blank=True, default="", editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalworkflowstageexecution",
            name="temporal_workflow_id",
            field=models.CharField(blank=True, default="", editable=False, max_length=512),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="temporal_activity_id",
            field=models.CharField(blank=True, default="", editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="temporal_activity_key",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="temporal_namespace",
            field=models.CharField(blank=True, default="", editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="temporal_run_id",
            field=models.CharField(blank=True, default="", editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name="workflowstageexecution",
            name="temporal_workflow_id",
            field=models.CharField(blank=True, default="", editable=False, max_length=512),
        ),
        migrations.AddConstraint(
            model_name="workflowstageexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("temporal_activity_key", ""), _negated=True),
                fields=("temporal_activity_key",),
                name="wfstageexec_temporal_activity_uq",
            ),
        ),
    ]
