# Generated by Django 6.0.5 on 2026-05-07 14:45

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedServiceCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('variant', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('binding_envs', models.JSONField(blank=True, default=list)),
                ('is_default_for_kind', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='0.0.0', max_length=64)),
                ('capabilities_manifest', models.JSONField(blank=True, default=dict)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPluginConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TenantCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('provider_config', models.JSONField(blank=True, default=dict)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('endpoint', models.URLField(blank=True, default='')),
                ('ca_cert', models.TextField(blank=True, default='')),
                ('auth_method', models.CharField(choices=[('kubeconfig', 'Kubeconfig'), ('exec_plugin', 'Exec Plugin'), ('service_account_token', 'Service Account Token')], max_length=32)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('ingress_class', models.CharField(default='nginx', max_length=64)),
                ('default_namespace_prefix', models.CharField(blank=True, default='', max_length=64)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('capabilities_probed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('zone', models.CharField(max_length=255)),
                ('dns_driver', models.CharField(max_length=64)),
                ('dns_config', models.JSONField(blank=True, default=dict)),
                ('default_for', models.CharField(choices=[('tenant_apps', 'Tenant Apps'), ('preview_envs', 'Preview Envs'), ('both', 'Both'), ('none', 'None')], default='none', max_length=32)),
                ('is_wildcard_managed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
