# Generated by Django 6.0.5 on 2026-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_clusters', '0004_tenantcluster_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcluster',
            name='lifecycle',
            field=models.CharField(choices=[('registered', 'Registered'), ('managing', 'Managing'), ('managed', 'Managed'), ('error', 'Error'), ('decommissioning', 'Decommissioning'), ('decommissioned', 'Decommissioned')], default='registered', max_length=32),
        ),
    ]
