# Generated by Django 6.0.5 on 2026-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_clusters", "0005_alter_tenantcluster_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantcluster",
            name="secrets_backend_provisioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
