# Generated by Django 6.0.5 on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_clusters', '0007_clusterbootstraprun'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageddomain',
            name='provision_state',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    "Current ZoneRegistrationStep. Empty = not started; "
                    "'mark_active' = fully provisioned."
                ),
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='manageddomain',
            name='provision_nameservers',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='NS records returned when the zone was created. Shown to operator for registrar delegation.',
            ),
        ),
        migrations.AddField(
            model_name='manageddomain',
            name='provision_cert_id',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Cloud cert ID/ARN — used for poll and reissue operations.',
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name='manageddomain',
            name='provision_validation_records',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='DNS validation CNAME records the operator must add (cloud cert DNS-01 challenge).',
            ),
        ),
    ]
