# Generated by Django 6.0.5 on 2026-06-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_clusters', '0010_tenantcluster_alb_auth_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcluster',
            name='agent_key_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the scoped agent key the in-cluster keep-alive agent signs its heartbeat with. The plaintext is surfaced exactly once at issuance (issueClusterAgentKey); only the hash persists. Empty = no agent provisioned yet.', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantcluster',
            name='heartbeat_interval_seconds',
            field=models.IntegerField(default=30, help_text='Cadence (seconds) the agent should pulse at. Returned in the heartbeat response so the agent can self-tune. The derived live status treats a cluster as DEGRADED once it misses one interval and OFFLINE once it misses three.'),
        ),
        migrations.AddField(
            model_name='tenantcluster',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Wall-clock time of the most recent agent heartbeat pulse.', null=True),
        ),
        migrations.AddField(
            model_name='tenantcluster',
            name='last_heartbeat_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot from the most recent heartbeat — node count, pod counts by namespace, CPU/memory utilization summary, ingress IPs, agent version. Free-form JSON so the agent version can evolve without a control-plane lockstep.'),
        ),
    ]
