# Generated by Django 6.0.5 on 2026-08-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_clusters', '0013_providerplugin_plugin_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcluster',
            name='cloud_account_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantcluster',
            name='cloud_account_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
