# Generated by Django 6.0.5 on 2026-08-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_clusters', '0014_tenantcluster_cloud_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcluster',
            name='ingress_mode',
            field=models.CharField(choices=[('shared_ingress', 'shared_ingress'), ('per_app_ingress', 'per_app_ingress')], default='per_app_ingress', help_text='shared_ingress: one load balancer fronts every app in the org (ALB group annotation). per_app_ingress: one load balancer per app Ingress. Only honoured on ALB clusters -- an nginx-family controller already shares one load balancer per cluster.', max_length=32),
        ),
    ]
