# Generated by Django 6.0.5 on 2026-10-03 09:22

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_clusters", "0020_tenantcluster_edge_access_rules"),
        ("astrolift_identity", "0041_merge_agent_enforcement_scim_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantcluster",
            name="agent_deployment_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="tenantcluster",
            name="agent_deployment_uid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="tenantcluster",
            name="agent_secret_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="tenantcluster",
            name="agent_secret_uid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.CreateModel(
            name="ClusterAgentInstall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("expected_version", models.PositiveIntegerField()),
                ("source_digest", models.CharField(max_length=64)),
                ("credential_ceiling", models.JSONField(default=dict)),
                ("credential_hash", models.CharField(max_length=64)),
                ("credential_backend_kind", models.CharField(max_length=64)),
                ("credential_ciphertext", models.BinaryField()),
                ("interval_seconds", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("installing", "Installing"),
                            ("awaiting_heartbeat", "Awaiting Heartbeat"),
                            ("succeeded", "Succeeded"),
                            ("refused", "Refused"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("generation", models.PositiveIntegerField(default=0)),
                (
                    "workflow_run_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "secret_uid",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "secret_resource_version",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("manifest_identities", models.JSONField(default=dict)),
                (
                    "previous_deployment_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "previous_deployment_uid",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("previous_deployment_retired", models.BooleanField(default=False)),
                (
                    "activation_source_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("deployment_confirmed", models.BooleanField(default=False)),
                ("heartbeat_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "tenant_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_installations",
                        to="astrolift_clusters.tenantcluster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "actor", "request_id"),
                        name="agent_install_actor_request_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            (
                                "status__in",
                                [
                                    "queued",
                                    "installing",
                                    "awaiting_heartbeat",
                                    "uncertain",
                                ],
                            ),
                        ),
                        fields=("tenant_cluster",),
                        name="agent_install_one_live_attempt",
                    ),
                ],
            },
        ),
    ]
