# Generated by Django 6.0.5 on 2026-10-03 10:28

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_clusters", "0021_reviewed_agent_install"),
        ("astrolift_identity", "0041_merge_agent_enforcement_scim_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterLogCollectorOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("expected_version", models.PositiveIntegerField()),
                ("expected_source", models.CharField(max_length=64)),
                ("source_digest", models.CharField(max_length=64)),
                ("binding_digest", models.CharField(max_length=64)),
                ("credential_ceiling", models.JSONField(default=dict)),
                ("retention_days", models.PositiveIntegerField()),
                ("probe_image", models.CharField(max_length=256)),
                ("policy_digest", models.CharField(max_length=64)),
                ("deadline", models.DateTimeField()),
                ("query_since", models.DateTimeField()),
                ("query_until", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("preparing", "Preparing"),
                            ("installing", "Installing"),
                            ("readiness_pending", "Readiness Pending"),
                            ("reader_grant_pending", "Reader Grant Pending"),
                            ("ingestion_pending", "Ingestion Pending"),
                            ("probe_deletion_pending", "Probe Deletion Pending"),
                            ("post_loss_read_pending", "Post Loss Read Pending"),
                            ("uncertain", "Uncertain"),
                            ("refused", "Refused"),
                            ("activated", "Activated"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("generation", models.PositiveIntegerField(default=0)),
                (
                    "workflow_run_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("checkpoints", models.JSONField(default=dict)),
                ("stage", models.CharField(blank=True, default="", max_length=96)),
                ("coverage", models.CharField(default="unknown", max_length=32)),
                ("cleanup_pending", models.BooleanField(default=False)),
                ("event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("post_loss_verified_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activated_cluster_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "activation_source_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "tenant_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="log_collector_operations",
                        to="astrolift_clusters.tenantcluster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "actor", "request_id"),
                        name="collector_actor_request_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            models.Q(("status__in", ["refused", "activated"]), _negated=True),
                        ),
                        fields=("tenant_cluster",),
                        name="collector_one_live_operation",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
CREATE FUNCTION astrolift_collector_request_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF ROW(NEW.guid, NEW.tenant_cluster_id, NEW.organization_id, NEW.actor_id,
         NEW.request_id, NEW.request_digest, NEW.expected_version, NEW.expected_source,
         NEW.source_digest, NEW.binding_digest, NEW.credential_ceiling,
         NEW.retention_days, NEW.probe_image, NEW.policy_digest, NEW.deadline,
         NEW.query_since, NEW.query_until)
     IS DISTINCT FROM
     ROW(OLD.guid, OLD.tenant_cluster_id, OLD.organization_id, OLD.actor_id,
         OLD.request_id, OLD.request_digest, OLD.expected_version, OLD.expected_source,
         OLD.source_digest, OLD.binding_digest, OLD.credential_ceiling,
         OLD.retention_days, OLD.probe_image, OLD.policy_digest, OLD.deadline,
         OLD.query_since, OLD.query_until)
  THEN RAISE EXCEPTION 'Collector original request is immutable'; END IF;
  IF NEW.generation < OLD.generation THEN
    RAISE EXCEPTION 'Collector generation cannot move backwards';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER collector_request_immutable BEFORE UPDATE ON astrolift_clusters_clusterlogcollectoroperation
FOR EACH ROW EXECUTE FUNCTION astrolift_collector_request_immutable();
""",
            reverse_sql="""
DROP TRIGGER collector_request_immutable ON astrolift_clusters_clusterlogcollectoroperation;
DROP FUNCTION astrolift_collector_request_immutable();
""",
        ),
    ]
