# Generated by Django 6.0.5 on 2026-10-04 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def refuse_retained_connection_rollback(apps, schema_editor):
    alias = schema_editor.connection.alias
    if any(
        apps.get_model("astrolift_clusters", name)._base_manager.using(alias).exists()
        for name in ("DnsProviderConnection", "DnsProviderOAuthAttempt")
    ):
        raise RuntimeError("Retained DNS connection or OAuth history prevents rollback.")


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_clusters", "0022_reviewed_log_collector"),
        ("astrolift_identity", "0041_merge_agent_enforcement_scim_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manageddomain",
            name="dns_provider_connection_version",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="manageddomain",
            name="dns_provider_zone_id",
            field=models.CharField(blank=True, default="", editable=False, max_length=32),
        ),
        migrations.CreateModel(
            name="DnsProviderConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "provider",
                    models.CharField(default="CLOUDFLARE", editable=False, max_length=32),
                ),
                ("auth_method", models.CharField(max_length=16)),
                ("oauth_client_id", models.CharField(blank=True, max_length=128)),
                ("state", models.CharField(default="ACTIVE", max_length=32)),
                ("revocation_state", models.CharField(default="NOT_REQUESTED", max_length=32)),
                ("secret_backend_kind", models.CharField(max_length=32)),
                ("secret_ciphertext", models.BinaryField()),
                ("refresh_backend_kind", models.CharField(blank=True, max_length=32)),
                ("refresh_ciphertext", models.BinaryField(default=bytes)),
                ("verified_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="manageddomain",
            name="dns_provider_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="astrolift_clusters.dnsproviderconnection",
            ),
        ),
        migrations.CreateModel(
            name="DnsProviderOAuthAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("state_sha256", models.CharField(max_length=64, unique=True)),
                ("session_hmac", models.CharField(max_length=64)),
                ("client_sha256", models.CharField(max_length=64)),
                ("verifier_backend_kind", models.CharField(max_length=32)),
                ("verifier_ciphertext", models.BinaryField()),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_retained_connection_rollback),
    ]
