# Generated by Django 6.0.5 on 2026-05-07 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrolift_billing', '0001_initial'),
        ('astrolift_identity', '0001_initial'),
        ('astrolift_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costsnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='costsnapshot',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_snapshots', to='astrolift_identity.project'),
        ),
        migrations.AddField(
            model_name='costsnapshot',
            name='registered_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_snapshots', to='astrolift_registry.registeredapp'),
        ),
        migrations.AddField(
            model_name='quota',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='quota',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quota',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='quota',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['organization', 'scope_kind', 'scope_id'], name='budget_org_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='costsnapshot',
            index=models.Index(fields=['organization', '-taken_at', 'by'], name='cost_org_date_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='quota',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'scope_kind', 'scope_id', 'resource'), name='quota_unique_active'),
        ),
    ]
