# Generated by Django 6.0.5 on 2026-07-25 23:35

import core.fields.uuid_v7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_billing', '0004_quota_increase_request'),
        ('astrolift_identity', '0019_resync_system_roles_agent_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('captured_at', models.DateField(db_index=True)),
                ('used', models.DecimalField(decimal_places=4, max_digits=20)),
                ('limit', models.DecimalField(decimal_places=4, max_digits=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage_snapshots', to='astrolift_identity.organization')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='astrolift_billing.quota')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'quota', '-captured_at'], name='quota_usage_org_quota_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('quota', 'captured_at'), name='quota_usage_snapshot_unique_per_day')],
            },
        ),
    ]
