# Generated by Django 6.0.5 on 2026-08-17 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_billing', '0005_quotausagesnapshot'),
        ('astrolift_identity', '0021_resync_system_roles_agent_task_send_input'),
        ('astrolift_registry', '0034_scope_repo_manifest_unique_to_organization'),
        ('astrolift_services', '0019_managedservice_update_operation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='costsnapshot',
            name='cost_snapshot_unique_per_day_scope',
        ),
        migrations.AddField(
            model_name='costsnapshot',
            name='managed_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_snapshots', to='astrolift_services.managedservice'),
        ),
        migrations.AddIndex(
            model_name='costsnapshot',
            index=models.Index(fields=['organization', 'managed_service', '-taken_at'], name='cost_org_msvc_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='costsnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'registered_app', 'managed_service_binding', 'managed_service', 'by', 'taken_at', 'source'), name='cost_snapshot_unique_per_day_scope'),
        ),
    ]
