# Generated by Django 6.0.5 on 2026-09-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_billing", "0006_remove_costsnapshot_cost_snapshot_unique_per_day_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quota",
            name="resource",
            field=models.CharField(
                choices=[
                    ("apps", "Apps"),
                    ("preview_envs", "Preview Envs"),
                    ("managed_services", "Managed Services"),
                    ("cpu", "Cpu"),
                    ("gpu", "Gpu"),
                    ("memory", "Memory"),
                    ("storage", "Storage"),
                    ("egress_gb", "Egress Gb"),
                    ("requests_per_month", "Requests Per Month"),
                ],
                max_length=32,
            ),
        ),
    ]
