# Generated by Django 6.0.5 on 2026-05-17 18:56

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrolift_identity', '0009_apitoken_last_used_ip_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('schema', models.JSONField(default=dict, help_text='JSON-Schema-like field tree consumed by the renderer.')),
                ('field_config', models.JSONField(blank=True, default=dict, help_text="Per-field UI knobs (placeholder, helper text) that aren't part of the JSON Schema.")),
                ('logic_rules', models.JSONField(blank=True, default=list, help_text='Declarative show/hide/calculate rules evaluated by the runtime renderer.')),
                ('scoring', models.JSONField(blank=True, default=dict, help_text='Optional per-field scoring map (e.g. quiz / risk scoring).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('form_type', models.CharField(default='generic', help_text='Tag for filtering / templating (e.g. survey, intake, quiz).', max_length=32)),
                ('is_public', models.BooleanField(default=False, help_text='When true, submissions may come from anonymous users via the public submit page.')),
                ('schema_version', models.IntegerField(default=1, help_text="Form-level schema version (independent of the row's tracking version). Bumped on publish so historical submissions can reference the schema they were filled against. Surfaced on the GraphQL surface as ``version`` for the FE.")),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('submission_count_cached', models.IntegerField(default=0, help_text='Denormalised submission count — updated in the submit / delete paths.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_definitions', to='astrolift_identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('form_version', models.IntegerField(help_text='Form version the submitter saw — snapshotted on submit.')),
                ('payload', models.JSONField(default=dict, help_text='Submitter responses keyed by field name.')),
                ('submitter_email', models.EmailField(blank=True, default='', help_text='Submitter email for anonymous public submissions; blank when authenticated.', max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged'), ('archived', 'Archived')], db_index=True, default='new', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='astrolift_forms.formdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='astrolift_identity.organization')),
                ('submitter', models.ForeignKey(blank=True, help_text='The authenticated submitter, or null for anonymous public submissions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='formdefinition',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='form_def_org_status_upd_idx'),
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'slug'), name='form_definition_unique_active_slug_per_org'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', '-submitted_at'], name='form_submission_form_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'status', '-submitted_at'], name='form_submission_form_status_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['organization', '-submitted_at'], name='form_submission_org_recent_idx'),
        ),
    ]
