# Generated by Django 6.0.5 on 2026-05-07 14:45

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('taken_at', models.DateField(db_index=True)),
                ('by', models.CharField(choices=[('workload', 'Workload'), ('managed_service', 'Managed Service'), ('egress', 'Egress'), ('storage', 'Storage'), ('other', 'Other')], max_length=32)),
                ('amount_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('source', models.CharField(choices=[('provider_estimate', 'Provider Estimate'), ('platform_meter', 'Platform Meter')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('scope_kind', models.CharField(choices=[('ORG', 'Org'), ('TEAM', 'Team'), ('PROJECT', 'Project')], max_length=16)),
                ('scope_id', models.BigIntegerField()),
                ('resource', models.CharField(choices=[('apps', 'Apps'), ('preview_envs', 'Preview Envs'), ('managed_services', 'Managed Services'), ('cpu', 'Cpu'), ('memory', 'Memory'), ('storage', 'Storage'), ('egress_gb', 'Egress Gb'), ('requests_per_month', 'Requests Per Month')], max_length=32)),
                ('hard_limit', models.DecimalField(decimal_places=4, max_digits=20)),
                ('soft_limit', models.DecimalField(decimal_places=4, max_digits=20)),
                ('current_usage', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('scope_kind', models.CharField(choices=[('ORG', 'Org'), ('TEAM', 'Team'), ('PROJECT', 'Project')], max_length=16)),
                ('scope_id', models.BigIntegerField()),
                ('amount_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=16)),
                ('alerts_at_pct', models.JSONField(blank=True, default=list)),
                ('current_spend_cents', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
