"""Service Availability Matrix (#21).

The availability matrix is a static catalog that describes:
- which driver roles are required for any cluster binding
  (cluster, ingress, dns, tls, secrets, identity, registry)
- which managed-service kinds + variants exist + which providers
  ship them
- whether each entry is shipping, deprecated, experimental, or planned

The matrix lives next to the plugin entry-point registry. It is the
source of truth for:
- capability negotiation (#18) — at cluster bind time, the control
  plane checks the desired plugin against the matrix to confirm
  every required role + every requested variant is provided
- CI verification (#26) — a green-the-build check confirms that
  every PLUGIN.drivers / PLUGIN.managed_service_drivers entry has
  a corresponding executable matrix entry; planned entries are roadmap
  metadata and do not satisfy capability negotiation

The matrix is intentionally code-defined (not YAML / JSON). That
keeps cross-driver invariants enforceable at import time + lets
type-checkers verify variant strings.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Status = Literal["ga", "preview", "deprecated", "experimental", "planned"]

_AWS_RELATIONAL_CACHE_ISSUE = "https://github.com/calliopeai/astrolift-app/issues/1283"
_AWS_DATA_SEARCH_ISSUE = "https://github.com/calliopeai/astrolift-app/issues/1284"
_AWS_EVENTING_ISSUE = "https://github.com/calliopeai/astrolift-app/issues/1285"
_AWS_PLATFORM_RESOURCES_ISSUE = "https://github.com/calliopeai/astrolift-app/issues/1286"
_CROSS_CLOUD_PARITY_ISSUE = "https://github.com/calliopeai/astrolift-app/issues/1287"


@dataclass(frozen=True)
class DriverEntry:
    """A driver role provided by a plugin."""

    role: str
    plugin_id: str
    variant: str | None = None
    status: Status = "ga"
    notes: str = ""


@dataclass(frozen=True)
class ManagedServiceEntry:
    """A managed-service (kind, variant) entry shipped by a plugin."""

    kind: str
    variant: str
    plugin_id: str
    status: Status = "ga"
    description: str = ""
    binding_envs: tuple[str, ...] = ()
    """Stable env-var names the binding emits (for docs + tests)."""
    issue_url: str = ""
    """Tracking issue for a planned or incomplete capability."""


# Driver roles every cluster MUST resolve at bind time. If the
# bound plugin doesn't ship one of these (and no delegation
# composition is registered), cluster registration fails.
REQUIRED_ROLES: tuple[str, ...] = (
    "cluster",
    "ingress",
    "dns",
    "tls",
    "secrets",
    "identity",
    "registry",
)


# Optional roles — drivers that the control plane can use when
# present but doesn't require for a working tenant cluster.
OPTIONAL_ROLES: tuple[str, ...] = (
    "log_stream",
    "metrics",
    "trace",
    "build",
    "object_store",
    "event",
)


@dataclass(frozen=True)
class AvailabilityMatrix:
    drivers: tuple[DriverEntry, ...] = ()
    managed_services: tuple[ManagedServiceEntry, ...] = ()

    def drivers_for_role(self, role: str) -> list[DriverEntry]:
        return [d for d in self.drivers if d.role == role]

    def plugins_for_kind(self, kind: str) -> list[ManagedServiceEntry]:
        return [m for m in self.managed_services if m.kind == kind]

    def variants_for_kind(self, kind: str) -> list[str]:
        return sorted({m.variant for m in self.managed_services if m.kind == kind})

    def has_role(self, *, plugin_id: str, role: str) -> bool:
        return any(d.plugin_id == plugin_id and d.role == role for d in self.drivers)

    def has_managed(
        self,
        *,
        plugin_id: str,
        kind: str,
        variant: str,
    ) -> bool:
        return any(
            m.plugin_id == plugin_id
            and m.kind == kind
            and m.variant == variant
            and m.status in {"ga", "preview", "experimental"}
            for m in self.managed_services
        )


# The canonical matrix. New driver / managed-service entries land
# here at the same time as their PLUGIN registration. CI (#26)
# enforces consistency.
MATRIX = AvailabilityMatrix(
    drivers=(
        # AWS plugin
        DriverEntry(role="cluster", plugin_id="aws"),
        DriverEntry(role="ingress", plugin_id="aws", variant="alb"),
        DriverEntry(role="dns", plugin_id="aws", variant="route53"),
        DriverEntry(role="tls", plugin_id="aws", variant="acm"),
        DriverEntry(role="secrets", plugin_id="aws", variant="secrets_manager"),
        DriverEntry(role="identity", plugin_id="aws", variant="irsa"),
        DriverEntry(role="registry", plugin_id="aws", variant="ecr"),
        DriverEntry(role="notification", plugin_id="aws", variant="sns"),
        # GCP plugin
        DriverEntry(role="cluster", plugin_id="gcp"),
        DriverEntry(role="ingress", plugin_id="gcp", variant="gce_ingress"),
        DriverEntry(role="ingress", plugin_id="gcp", variant="gateway_api"),
        DriverEntry(role="dns", plugin_id="gcp", variant="cloud_dns"),
        DriverEntry(role="tls", plugin_id="gcp", variant="gcp_managed_cert"),
        DriverEntry(role="secrets", plugin_id="gcp", variant="secret_manager"),
        DriverEntry(role="identity", plugin_id="gcp", variant="workload_identity"),
        DriverEntry(role="registry", plugin_id="gcp", variant="artifact_registry"),
        DriverEntry(role="notification", plugin_id="gcp", variant="fcm"),
        # Azure plugin
        DriverEntry(role="cluster", plugin_id="azure"),
        DriverEntry(role="ingress", plugin_id="azure", variant="agic"),
        DriverEntry(role="ingress", plugin_id="azure", variant="gateway_api"),
        DriverEntry(role="dns", plugin_id="azure", variant="azure_dns"),
        DriverEntry(role="tls", plugin_id="azure", variant="azure_managed_cert"),
        DriverEntry(role="tls", plugin_id="azure", variant="akv_referenced"),
        DriverEntry(role="secrets", plugin_id="azure", variant="key_vault"),
        DriverEntry(
            role="identity",
            plugin_id="azure",
            variant="federated_credentials",
        ),
        DriverEntry(role="registry", plugin_id="azure", variant="acr"),
        DriverEntry(role="notification", plugin_id="azure", variant="notification_hubs"),
        # k8s_native plugin
        DriverEntry(role="cluster", plugin_id="k8s_native"),
        DriverEntry(role="ingress", plugin_id="k8s_native", variant="nginx_ingress"),
        DriverEntry(role="ingress", plugin_id="k8s_native", variant="gateway_api"),
        DriverEntry(role="ingress", plugin_id="k8s_native", variant="traefik"),
        DriverEntry(role="ingress", plugin_id="k8s_native", variant="kong"),
        DriverEntry(role="ingress", plugin_id="k8s_native", variant="istio_gateway"),
        DriverEntry(role="dns", plugin_id="k8s_native", variant="external_dns"),
        DriverEntry(role="tls", plugin_id="k8s_native", variant="cert_manager"),
        DriverEntry(role="secrets", plugin_id="k8s_native", variant="vault"),
        DriverEntry(
            role="identity",
            plugin_id="k8s_native",
            variant="projected_sa_token",
        ),
        DriverEntry(role="registry", plugin_id="k8s_native", variant="generic_oci"),
        DriverEntry(role="registry", plugin_id="k8s_native", variant="quay"),
        DriverEntry(role="registry", plugin_id="k8s_native", variant="dockerhub"),
        DriverEntry(role="registry", plugin_id="k8s_native", variant="ghcr"),
        DriverEntry(role="registry", plugin_id="k8s_native", variant="harbor"),
        DriverEntry(role="notification", plugin_id="k8s_native", variant="webhook_smtp"),
    ),
    managed_services=(
        # AWS — MVP set; extended catalog tracked in #79
        ManagedServiceEntry(
            kind="object_store",
            variant="s3",
            plugin_id="aws",
            description="Amazon S3 with versioning + public-access block",
            binding_envs=("S3_BUCKET_NAME", "S3_REGION"),
        ),
        ManagedServiceEntry(
            kind="queue",
            variant="sqs",
            plugin_id="aws",
            description="Amazon SQS standard or FIFO queue",
            binding_envs=(
                "QUEUE_URL",
                "QUEUE_ARN_OR_ID",
                "QUEUE_NAME",
                "QUEUE_REGION",
                "SQS_QUEUE_URL",
                "SQS_QUEUE_ARN",
                "SQS_QUEUE_NAME",
                "AWS_REGION",
            ),
        ),
        # AWS — extended catalog (#79): entries mirror aws/plugin.py
        ManagedServiceEntry(
            kind="postgres",
            variant="rds",
            plugin_id="aws",
            description="Amazon RDS for PostgreSQL",
        ),
        ManagedServiceEntry(
            kind="mysql",
            variant="rds_mysql",
            plugin_id="aws",
            description="Amazon RDS for MySQL",
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="elasticache",
            plugin_id="aws",
            description="Amazon ElastiCache for Redis",
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="elasticache_valkey",
            plugin_id="aws",
            status="preview",
            description="Amazon ElastiCache node-based replication group for Valkey",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="kv_store",
            variant="dynamodb",
            plugin_id="aws",
            description="Amazon DynamoDB table",
        ),
        ManagedServiceEntry(
            kind="cdn",
            variant="cloudfront",
            plugin_id="aws",
            description="Amazon CloudFront distribution (static-site topology)",
        ),
        ManagedServiceEntry(
            kind="faas",
            variant="lambda",
            plugin_id="aws",
            description="AWS Lambda function",
        ),
        ManagedServiceEntry(
            kind="api_gateway",
            variant="http_api",
            plugin_id="aws",
            description="Amazon API Gateway HTTP API",
            binding_envs=(
                "API_GATEWAY_URL",
                "API_GATEWAY_ID",
                "API_GATEWAY_STAGE",
                "FAAS_INVOKE_URL",
                "AWS_REGION",
            ),
        ),
        ManagedServiceEntry(
            kind="search",
            variant="opensearch",
            plugin_id="aws",
            description="Amazon OpenSearch full-text domain",
        ),
        ManagedServiceEntry(
            kind="vector_index",
            variant="opensearch_vector",
            plugin_id="aws",
            description="Amazon OpenSearch k-NN vector index",
        ),
        ManagedServiceEntry(
            kind="time_series",
            variant="timestream",
            plugin_id="aws",
            description="Amazon Timestream database",
        ),
        ManagedServiceEntry(
            kind="email",
            variant="ses",
            plugin_id="aws",
            description="Amazon SES identity + configuration set",
        ),
        ManagedServiceEntry(
            kind="model_endpoint",
            variant="bedrock",
            plugin_id="aws",
            description="Amazon Bedrock model endpoint",
        ),
        # AWS roadmap entries stay visible in the cluster catalogue.  They are
        # not provisionable until an executable plugin driver replaces the
        # planned status.
        ManagedServiceEntry(
            kind="postgres",
            variant="aurora_postgres",
            plugin_id="aws",
            status="preview",
            description="Amazon Aurora PostgreSQL provisioned cluster",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="postgres",
            variant="aurora_postgres_serverless_v2",
            plugin_id="aws",
            status="preview",
            description="Amazon Aurora PostgreSQL Serverless v2 cluster",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mysql",
            variant="aurora_mysql",
            plugin_id="aws",
            status="preview",
            description="Amazon Aurora MySQL provisioned cluster",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mysql",
            variant="aurora_mysql_serverless_v2",
            plugin_id="aws",
            status="preview",
            description="Amazon Aurora MySQL Serverless v2 cluster",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="database_proxy",
            variant="rds_proxy",
            plugin_id="aws",
            status="preview",
            description="Amazon RDS Proxy",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="rds_sqlserver_express",
            plugin_id="aws",
            status="preview",
            description="Amazon RDS for SQL Server Express (development/small workloads)",
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="rds_sqlserver_web",
            plugin_id="aws",
            status="preview",
            description="Amazon RDS for SQL Server Web",
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="rds_sqlserver_standard",
            plugin_id="aws",
            status="preview",
            description="Amazon RDS for SQL Server Standard",
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="rds_sqlserver_enterprise",
            plugin_id="aws",
            status="preview",
            description="Amazon RDS for SQL Server Enterprise",
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="document_db",
            variant="documentdb",
            plugin_id="aws",
            status="preview",
            description="Amazon DocumentDB Mongo-compatible cluster",
            binding_envs=(
                "DOCDB_URI",
                "DOCDB_DB",
                "DOCDB_USER",
                "DOCDB_PASSWORD",
                "DOCDB_TLS",
                "DOCDB_RESOURCE_ARN",
            ),
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="document_db",
            variant="documentdb_serverless_v2",
            plugin_id="aws",
            status="preview",
            description="Amazon DocumentDB Serverless v2 Mongo-compatible cluster",
            binding_envs=(
                "DOCDB_URI",
                "DOCDB_DB",
                "DOCDB_USER",
                "DOCDB_PASSWORD",
                "DOCDB_TLS",
                "DOCDB_RESOURCE_ARN",
            ),
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="graph_db",
            variant="neptune_serverless",
            plugin_id="aws",
            status="preview",
            description="Amazon Neptune Serverless graph database",
            binding_envs=(
                "GRAPH_DB_URL",
                "GRAPH_DB_READER_URL",
                "GRAPH_DB_ENDPOINT",
                "GRAPH_DB_PORT",
                "GRAPH_DB_PROTOCOL",
                "GRAPH_DB_TLS",
                "GRAPH_DB_AUTH_MODE",
                "GRAPH_DB_REGION",
                "GRAPH_DB_RESOURCE_ARN",
            ),
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="graph_db",
            variant="neptune",
            plugin_id="aws",
            status="preview",
            description="Amazon Neptune provisioned graph database",
            binding_envs=(
                "GRAPH_DB_URL",
                "GRAPH_DB_READER_URL",
                "GRAPH_DB_ENDPOINT",
                "GRAPH_DB_PORT",
                "GRAPH_DB_PROTOCOL",
                "GRAPH_DB_TLS",
                "GRAPH_DB_AUTH_MODE",
                "GRAPH_DB_REGION",
                "GRAPH_DB_RESOURCE_ARN",
            ),
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="wide_column",
            variant="keyspaces",
            plugin_id="aws",
            status="preview",
            description="Amazon Keyspaces Cassandra-compatible table",
            binding_envs=(
                "WIDE_COLUMN_ENDPOINT",
                "WIDE_COLUMN_KEYSPACE",
                "WIDE_COLUMN_TABLE",
                "WIDE_COLUMN_REGION",
                "WIDE_COLUMN_PORT",
                "WIDE_COLUMN_AUTH_MODE",
                "WIDE_COLUMN_RESOURCE_ARN",
            ),
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="warehouse",
            variant="redshift_serverless",
            plugin_id="aws",
            status="preview",
            description="Amazon Redshift Serverless namespace and workgroup",
            binding_envs=(
                "WAREHOUSE_ENDPOINT",
                "WAREHOUSE_PORT",
                "WAREHOUSE_DATABASE",
                "WAREHOUSE_URL",
                "WAREHOUSE_CREDENTIALS_REF",
                "WAREHOUSE_ENGINE",
                "WAREHOUSE_DEPLOYMENT",
                "WAREHOUSE_AUTH_MODE",
                "WAREHOUSE_REGION",
                "WAREHOUSE_RESOURCE_ARN",
                "WAREHOUSE_WORKGROUP",
                "WAREHOUSE_NAMESPACE",
                "WAREHOUSE_TLS",
            ),
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="warehouse",
            variant="redshift",
            plugin_id="aws",
            status="preview",
            description="Amazon Redshift provisioned cluster",
            binding_envs=(
                "WAREHOUSE_ENDPOINT",
                "WAREHOUSE_PORT",
                "WAREHOUSE_DATABASE",
                "WAREHOUSE_URL",
                "WAREHOUSE_CREDENTIALS_REF",
                "WAREHOUSE_ENGINE",
                "WAREHOUSE_DEPLOYMENT",
                "WAREHOUSE_AUTH_MODE",
                "WAREHOUSE_REGION",
                "WAREHOUSE_RESOURCE_ARN",
                "WAREHOUSE_CLUSTER_ID",
                "WAREHOUSE_TLS",
            ),
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="elasticache_serverless_valkey",
            plugin_id="aws",
            status="preview",
            description="Amazon ElastiCache Serverless for Valkey",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="elasticache_serverless_redis",
            plugin_id="aws",
            status="preview",
            description="Amazon ElastiCache Serverless for Redis OSS",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="cache",
            variant="elasticache_serverless_memcached",
            plugin_id="aws",
            status="preview",
            description="Amazon ElastiCache Serverless for Memcached",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="cache",
            variant="elasticache_memcached",
            plugin_id="aws",
            status="preview",
            description="Amazon ElastiCache node-based Memcached cluster",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="memorydb",
            plugin_id="aws",
            status="preview",
            description="Amazon MemoryDB durable Valkey/Redis-compatible database",
            issue_url=_AWS_RELATIONAL_CACHE_ISSUE,
        ),
        ManagedServiceEntry(
            kind="search",
            variant="opensearch_serverless",
            plugin_id="aws",
            status="preview",
            description="Amazon OpenSearch Serverless search collection",
            binding_envs=("SEARCH_ENDPOINT", "SEARCH_INDEX_PREFIX"),
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="vector_index",
            variant="opensearch_serverless_vector",
            plugin_id="aws",
            status="preview",
            description="Amazon OpenSearch Serverless vector collection",
            binding_envs=(
                "VECTOR_ENDPOINT",
                "VECTOR_INDEX_NAME",
                "VECTOR_NAMESPACE",
            ),
            issue_url=_AWS_DATA_SEARCH_ISSUE,
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="efs",
            plugin_id="aws",
            status="preview",
            description="Amazon EFS filesystem and access point",
            binding_envs=(
                "FILESYSTEM_HANDLE",
                "FILESYSTEM_MOUNT_PATH",
                "FILESYSTEM_TLS",
                "FILESYSTEM_PROTOCOL",
                "FILESYSTEM_ENDPOINT",
                "FILESYSTEM_MOUNT_OPTIONS",
                "EFS_FILE_SYSTEM_ID",
                "EFS_ACCESS_POINT_ID",
                "AWS_REGION",
            ),
            issue_url=_AWS_PLATFORM_RESOURCES_ISSUE,
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="fsx_lustre",
            plugin_id="aws",
            status="preview",
            description="Amazon FSx for Lustre filesystem",
            binding_envs=(
                "FILESYSTEM_HANDLE",
                "FILESYSTEM_MOUNT_PATH",
                "FILESYSTEM_TLS",
                "FILESYSTEM_PROTOCOL",
                "FILESYSTEM_ENDPOINT",
                "FILESYSTEM_MOUNT_SOURCE",
                "FILESYSTEM_MOUNT_OPTIONS",
                "FSX_FILE_SYSTEM_ID",
                "FSX_FILE_SYSTEM_ARN",
                "FSX_FILE_SYSTEM_TYPE",
                "AWS_REGION",
            ),
            issue_url=_AWS_PLATFORM_RESOURCES_ISSUE,
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="fsx_openzfs",
            plugin_id="aws",
            status="preview",
            description="Amazon FSx for OpenZFS filesystem",
            binding_envs=(
                "FILESYSTEM_HANDLE",
                "FILESYSTEM_MOUNT_PATH",
                "FILESYSTEM_TLS",
                "FILESYSTEM_PROTOCOL",
                "FILESYSTEM_ENDPOINT",
                "FILESYSTEM_MOUNT_SOURCE",
                "FILESYSTEM_MOUNT_OPTIONS",
                "FSX_FILE_SYSTEM_ID",
                "FSX_FILE_SYSTEM_ARN",
                "FSX_FILE_SYSTEM_TYPE",
                "AWS_REGION",
            ),
            issue_url=_AWS_PLATFORM_RESOURCES_ISSUE,
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="fsx_windows",
            plugin_id="aws",
            status="preview",
            description="Amazon FSx for Windows File Server",
            binding_envs=(
                "FILESYSTEM_HANDLE",
                "FILESYSTEM_MOUNT_PATH",
                "FILESYSTEM_TLS",
                "FILESYSTEM_PROTOCOL",
                "FILESYSTEM_ENDPOINT",
                "FILESYSTEM_MOUNT_SOURCE",
                "FILESYSTEM_MOUNT_OPTIONS",
                "FSX_FILE_SYSTEM_ID",
                "FSX_FILE_SYSTEM_ARN",
                "FSX_FILE_SYSTEM_TYPE",
                "FILESYSTEM_USERNAME",
                "FILESYSTEM_PASSWORD",
                "AWS_REGION",
            ),
            issue_url=_AWS_PLATFORM_RESOURCES_ISSUE,
        ),
        ManagedServiceEntry(
            kind="topic",
            variant="sns_standard",
            plugin_id="aws",
            status="preview",
            description="Amazon SNS standard topic and subscriptions",
            binding_envs=(
                "TOPIC_ARN_OR_ID",
                "TOPIC_NAME",
                "TOPIC_REGION",
                "SNS_TOPIC_ARN",
                "SNS_TOPIC_NAME",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="topic",
            variant="sns_fifo",
            plugin_id="aws",
            status="preview",
            description="Amazon SNS FIFO topic and subscriptions",
            binding_envs=(
                "TOPIC_ARN_OR_ID",
                "TOPIC_NAME",
                "TOPIC_REGION",
                "SNS_TOPIC_ARN",
                "SNS_TOPIC_NAME",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="event_bus",
            variant="eventbridge",
            plugin_id="aws",
            status="preview",
            description="Amazon EventBridge custom bus, rules, and targets",
            binding_envs=(
                "EVENT_BUS_NAME",
                "EVENT_BUS_ARN",
                "EVENT_BUS_REGION",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="stream",
            variant="kinesis",
            plugin_id="aws",
            status="preview",
            description="Amazon Kinesis Data Stream",
            binding_envs=(
                "STREAM_NAME",
                "STREAM_ARN",
                "STREAM_ENDPOINT",
                "STREAM_REGION",
                "AWS_REGION",
                "KINESIS_STREAM_NAME",
                "KINESIS_STREAM_ARN",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="stream",
            variant="firehose",
            plugin_id="aws",
            status="preview",
            description="Amazon Data Firehose delivery stream",
            binding_envs=(
                "STREAM_NAME",
                "STREAM_ARN",
                "STREAM_ENDPOINT",
                "STREAM_REGION",
                "AWS_REGION",
                "FIREHOSE_DELIVERY_STREAM_NAME",
                "FIREHOSE_DELIVERY_STREAM_ARN",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="event_stream",
            variant="msk_serverless",
            plugin_id="aws",
            status="preview",
            description="Amazon MSK Serverless Kafka cluster",
            binding_envs=(
                "EVENT_STREAM_BROKERS",
                "EVENT_STREAM_USERNAME",
                "EVENT_STREAM_PASSWORD",
                "EVENT_STREAM_TLS",
                "EVENT_STREAM_AUTH_MECHANISM",
                "EVENT_STREAM_CLIENT_CERT",
                "EVENT_STREAM_CLIENT_KEY",
                "EVENT_STREAM_CA_CERT",
                "AWS_REGION",
                "MSK_CLUSTER_ARN",
                "MSK_CLUSTER_NAME",
                "MSK_BOOTSTRAP_BROKERS",
                "MSK_AUTH_MECHANISM",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="event_stream",
            variant="msk",
            plugin_id="aws",
            status="preview",
            description="Amazon MSK provisioned Kafka cluster",
            binding_envs=(
                "EVENT_STREAM_BROKERS",
                "EVENT_STREAM_USERNAME",
                "EVENT_STREAM_PASSWORD",
                "EVENT_STREAM_TLS",
                "EVENT_STREAM_AUTH_MECHANISM",
                "EVENT_STREAM_CLIENT_CERT",
                "EVENT_STREAM_CLIENT_KEY",
                "EVENT_STREAM_CA_CERT",
                "AWS_REGION",
                "MSK_CLUSTER_ARN",
                "MSK_CLUSTER_NAME",
                "MSK_BOOTSTRAP_BROKERS",
                "MSK_AUTH_MECHANISM",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mq",
            variant="amazon_mq_rabbitmq",
            plugin_id="aws",
            status="preview",
            description="Amazon MQ for RabbitMQ",
            binding_envs=(
                "MQ_ENDPOINT",
                "MQ_USERNAME",
                "MQ_PASSWORD",
                "MQ_PROTOCOL",
                "MQ_AUTH_STRATEGY",
                "AMAZON_MQ_BROKER_ID",
                "AMAZON_MQ_BROKER_ARN",
                "AMAZON_MQ_ENGINE_TYPE",
                "AMAZON_MQ_ENDPOINTS_JSON",
                "AMAZON_MQ_CONSOLE_URL",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mq",
            variant="amazon_mq_activemq",
            plugin_id="aws",
            status="preview",
            description="Amazon MQ for ActiveMQ",
            binding_envs=(
                "MQ_ENDPOINT",
                "MQ_USERNAME",
                "MQ_PASSWORD",
                "MQ_PROTOCOL",
                "MQ_AUTH_STRATEGY",
                "AMAZON_MQ_BROKER_ID",
                "AMAZON_MQ_BROKER_ARN",
                "AMAZON_MQ_ENGINE_TYPE",
                "AMAZON_MQ_ENDPOINTS_JSON",
                "AMAZON_MQ_CONSOLE_URL",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="api_gateway",
            variant="rest_api",
            plugin_id="aws",
            status="preview",
            description="Amazon API Gateway REST API",
            binding_envs=(
                "API_GATEWAY_URL",
                "API_GATEWAY_ID",
                "API_GATEWAY_STAGE",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="api_gateway",
            variant="websocket_api",
            plugin_id="aws",
            status="preview",
            description="Amazon API Gateway WebSocket API",
            binding_envs=(
                "API_GATEWAY_URL",
                "API_GATEWAY_ID",
                "API_GATEWAY_STAGE",
                "WEBSOCKET_URL",
                "WEBSOCKET_MANAGEMENT_URL",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="workflow_engine",
            variant="step_functions_standard",
            plugin_id="aws",
            status="preview",
            description="AWS Step Functions Standard state machine",
            binding_envs=(
                "WORKFLOW_ENGINE_ID",
                "WORKFLOW_ENGINE_ARN",
                "WORKFLOW_ENGINE_REGION",
                "WORKFLOW_ENGINE_TYPE",
                "STEP_FUNCTIONS_STATE_MACHINE_ARN",
                "STEP_FUNCTIONS_CONSOLE_URL",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="workflow_engine",
            variant="step_functions_express",
            plugin_id="aws",
            status="preview",
            description="AWS Step Functions Express state machine",
            binding_envs=(
                "WORKFLOW_ENGINE_ID",
                "WORKFLOW_ENGINE_ARN",
                "WORKFLOW_ENGINE_REGION",
                "WORKFLOW_ENGINE_TYPE",
                "STEP_FUNCTIONS_STATE_MACHINE_ARN",
                "STEP_FUNCTIONS_CONSOLE_URL",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        ManagedServiceEntry(
            kind="encryption_key",
            variant="kms",
            plugin_id="aws",
            status="preview",
            description="AWS KMS project key and aliases",
            binding_envs=(
                "ENCRYPTION_KEY_ID",
                "ENCRYPTION_KEY_ARN",
                "ENCRYPTION_KEY_ALIAS",
                "ENCRYPTION_KEY_SPEC",
                "ENCRYPTION_KEY_USAGE",
                "ENCRYPTION_KEY_MULTI_REGION",
                "KMS_KEY_ID",
                "KMS_KEY_ARN",
                "AWS_REGION",
            ),
            issue_url=_AWS_PLATFORM_RESOURCES_ISSUE,
        ),
        ManagedServiceEntry(
            kind="private_endpoint",
            variant="vpc_endpoint",
            plugin_id="aws",
            status="preview",
            description="AWS PrivateLink VPC endpoint",
            binding_envs=(
                "PRIVATE_ENDPOINT_ID",
                "PRIVATE_ENDPOINT_DNS",
                "PRIVATE_ENDPOINT_IPS",
                "PRIVATE_ENDPOINT_TYPE",
                "PRIVATE_ENDPOINT_SERVICE_NAME",
                "PRIVATE_ENDPOINT_DNS_NAME",
                "PRIVATE_ENDPOINT_DNS_NAMES",
                "PRIVATE_ENDPOINT_NETWORK_INTERFACE_IDS",
                "PRIVATE_ENDPOINT_PREFIX_LIST_ID",
                "VPC_ENDPOINT_ID",
                "VPC_ID",
                "AWS_REGION",
            ),
            issue_url=_AWS_PLATFORM_RESOURCES_ISSUE,
        ),
        ManagedServiceEntry(
            kind="observability",
            variant="cloudwatch",
            plugin_id="aws",
            status="preview",
            description="CloudWatch log group, alarms, and dashboard",
            binding_envs=(
                "OBSERVABILITY_PROVIDER",
                "LOG_GROUP",
                "METRICS_ENDPOINT",
                "DASHBOARD_URL",
                "CLOUDWATCH_LOG_GROUP",
                "CLOUDWATCH_LOG_GROUP_ARN",
                "CLOUDWATCH_LOGS_ENDPOINT",
                "CLOUDWATCH_DASHBOARD_NAME",
                "CLOUDWATCH_BUNDLE_ID",
                "AWS_REGION",
            ),
            issue_url=_AWS_PLATFORM_RESOURCES_ISSUE,
        ),
        ManagedServiceEntry(
            kind="sms",
            variant="sns_sms",
            plugin_id="aws",
            status="preview",
            description="Amazon SNS SMS project topic and direct-send binding",
            binding_envs=(
                "SMS_PROVIDER",
                "SMS_REGION",
                "SMS_FROM",
                "SMS_SENDER_ID",
                "SMS_ORIGINATION_NUMBER",
                "SMS_TYPE",
                "SMS_MAX_PRICE_USD",
                "SMS_ENTITY_ID",
                "SMS_TEMPLATE_ID",
                "SMS_DELIVERY_MODE",
                "SMS_TOPIC_ARN",
                "SMS_SANDBOX",
                "SNS_TOPIC_ARN",
                "AWS_REGION",
            ),
            issue_url=_AWS_EVENTING_ISSUE,
        ),
        # GCP
        ManagedServiceEntry(
            kind="object_store",
            variant="gcs",
            plugin_id="gcp",
            description="Google Cloud Storage bucket",
            binding_envs=("GCS_BUCKET_NAME", "GCS_BUCKET_URI", "GCP_PROJECT_ID"),
        ),
        ManagedServiceEntry(
            kind="queue",
            variant="pubsub",
            plugin_id="gcp",
            description="Pub/Sub topic + subscription pair",
            binding_envs=(
                "PUBSUB_TOPIC",
                "PUBSUB_SUBSCRIPTION",
                "GCP_PROJECT_ID",
            ),
        ),
        ManagedServiceEntry(
            kind="postgres",
            variant="cloudsql",
            plugin_id="gcp",
            description="Cloud SQL for PostgreSQL",
            binding_envs=(
                "POSTGRES_HOST",
                "POSTGRES_PORT",
                "POSTGRES_DB",
                "POSTGRES_USER",
                "POSTGRES_PASSWORD",
                "POSTGRES_SSL_MODE",
                "POSTGRES_MASTER_SECRET_REF",
                "DATABASE_URL",
            ),
        ),
        ManagedServiceEntry(
            kind="mysql",
            variant="cloudsql",
            plugin_id="gcp",
            description="Cloud SQL for MySQL",
            binding_envs=(
                "MYSQL_HOST",
                "MYSQL_PORT",
                "MYSQL_DB",
                "MYSQL_USER",
                "MYSQL_PASSWORD",
                "DATABASE_URL",
            ),
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="memorystore",
            plugin_id="gcp",
            description="Memorystore for Redis",
            binding_envs=(
                "REDIS_HOST",
                "REDIS_PORT",
                "REDIS_USER",
                "REDIS_PASSWORD",
                "REDIS_TLS",
                "REDIS_URL",
                "REDIS_AUTH_MODE",
                "REDIS_RESOURCE_ARN",
            ),
        ),
        ManagedServiceEntry(
            kind="kv_store",
            variant="bigtable",
            plugin_id="gcp",
            description="Cloud Bigtable instance",
        ),
        ManagedServiceEntry(
            kind="search",
            variant="gcp_elastic_cloud",
            plugin_id="gcp",
            status="planned",
            description="Elastic Cloud on GCP (stub driver)",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="vector_index",
            variant="vertex_matching_engine",
            plugin_id="gcp",
            description="Vertex AI Matching Engine index",
        ),
        ManagedServiceEntry(
            kind="time_series",
            variant="gcp_managed_prometheus",
            plugin_id="gcp",
            description="Google Cloud Managed Service for Prometheus",
        ),
        ManagedServiceEntry(
            kind="email",
            variant="gcp_thirdparty",
            plugin_id="gcp",
            status="planned",
            description="Third-party email on GCP (stub driver)",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="model_endpoint",
            variant="vertex_ai",
            plugin_id="gcp",
            description="Vertex AI model endpoint",
        ),
        ManagedServiceEntry(
            kind="postgres",
            variant="alloydb",
            plugin_id="gcp",
            description="AlloyDB for PostgreSQL cluster",
            binding_envs=(
                "POSTGRES_HOST",
                "POSTGRES_PORT",
                "POSTGRES_DB",
                "POSTGRES_USER",
                "POSTGRES_PASSWORD",
                "POSTGRES_SSL_MODE",
                "POSTGRES_MASTER_SECRET_REF",
                "DATABASE_URL",
                "ALLOYDB_CLUSTER",
                "ALLOYDB_INSTANCE",
                "ALLOYDB_HOST",
                "ALLOYDB_PORT",
            ),
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="cloudsql_sqlserver",
            plugin_id="gcp",
            description=(
                "Cloud SQL for SQL Server 2017-2025 Express/Web/Standard/Enterprise, "
                "including Enterprise Plus, PITR, HA, data cache, CMEK, exact backups, and restore"
            ),
            binding_envs=(
                "MSSQL_HOST",
                "MSSQL_PORT",
                "MSSQL_DB",
                "MSSQL_USER",
                "MSSQL_PASSWORD",
                "MSSQL_ENCRYPT",
                "DATABASE_URL",
                "GCP_CLOUDSQL_INSTANCE",
                "GCP_CLOUDSQL_CONNECTION_NAME",
            ),
        ),
        ManagedServiceEntry(
            kind="document_db",
            variant="firestore_native",
            plugin_id="gcp",
            description=(
                "Firestore Native database with Standard/Enterprise editions, PITR, "
                "CMEK, backup schedules, composite/vector/search indexes, TTL, export, and restore"
            ),
            binding_envs=(
                "DOCDB_URI",
                "DOCDB_DB",
                "DOCDB_AUTH_MODE",
                "DOCDB_TLS",
                "DOCDB_RESOURCE_ARN",
                "GCP_FIRESTORE_PROJECT",
                "GCP_FIRESTORE_DATABASE",
                "GCP_FIRESTORE_UID",
                "GCP_FIRESTORE_LOCATION",
                "GCP_FIRESTORE_EDITION",
                "GCP_FIRESTORE_CLIENT_API",
            ),
        ),
        ManagedServiceEntry(
            kind="graph_db",
            variant="spanner_graph",
            plugin_id="gcp",
            description=(
                "Cloud Spanner Graph on Enterprise or Enterprise Plus with GoogleSQL, "
                "GQL property graphs, autoscaling, CMEK, backups, restore, and IAM bindings"
            ),
            binding_envs=(
                "GRAPH_DB_URL",
                "GRAPH_DB_ENDPOINT",
                "GRAPH_DB_PROTOCOL",
                "GRAPH_DB_TLS",
                "GRAPH_DB_AUTH_MODE",
                "GRAPH_DB_REGION",
                "GRAPH_DB_RESOURCE_ARN",
                "GCP_SPANNER_PROJECT",
                "GCP_SPANNER_INSTANCE",
                "GCP_SPANNER_DATABASE",
                "GCP_SPANNER_GRAPH",
                "GCP_SPANNER_DIALECT",
            ),
        ),
        ManagedServiceEntry(
            kind="warehouse",
            variant="bigquery",
            plugin_id="gcp",
            description="BigQuery dataset, reservations, assignments, and capacity commitments",
            binding_envs=(
                "WAREHOUSE_ENDPOINT",
                "WAREHOUSE_DATABASE",
                "WAREHOUSE_URL",
                "WAREHOUSE_ENGINE",
                "WAREHOUSE_DEPLOYMENT",
                "WAREHOUSE_AUTH_MODE",
                "WAREHOUSE_REGION",
                "WAREHOUSE_RESOURCE_ARN",
                "WAREHOUSE_CLUSTER_ID",
                "GCP_BIGQUERY_PROJECT",
                "GCP_BIGQUERY_DATASET",
                "GCP_BIGQUERY_LOCATION",
                "GCP_BIGQUERY_RESERVATIONS",
            ),
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="memorystore_valkey",
            plugin_id="gcp",
            description=(
                "Memorystore for Valkey with PSC, IAM or token authentication, TLS, RDB/AOF persistence, "
                "scaling, CMEK, managed or custom CAs, ACL policies, managed backups, restore, "
                "and cross-instance replication"
            ),
            binding_envs=(
                "REDIS_HOST",
                "REDIS_PORT",
                "REDIS_USER",
                "REDIS_PASSWORD",
                "REDIS_TLS",
                "REDIS_URL",
                "REDIS_READER_URL",
                "REDIS_CA_CERT",
                "REDIS_AUTH_MODE",
                "REDIS_RESOURCE_ARN",
                "GCP_MEMORYSTORE_PROJECT",
                "GCP_MEMORYSTORE_REGION",
                "GCP_MEMORYSTORE_INSTANCE",
                "GCP_MEMORYSTORE_UID",
                "GCP_MEMORYSTORE_MODE",
                "GCP_MEMORYSTORE_ENGINE_VERSION",
                "GCP_MEMORYSTORE_ENDPOINTS",
                "GCP_MEMORYSTORE_SERVER_CA_MODE",
                "GCP_MEMORYSTORE_SERVER_CA_POOL",
                "GCP_MEMORYSTORE_ACL_POLICY",
                "GCP_MEMORYSTORE_ACL_POLICY_IN_SYNC",
            ),
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="filestore",
            plugin_id="gcp",
            description=(
                "Google Cloud Filestore with all public tiers, NFSv3/v4.1, PSC, "
                "CMEK, backups, snapshots, and replication"
            ),
            binding_envs=(
                "FILESYSTEM_HANDLE",
                "FILESYSTEM_MOUNT_PATH",
                "FILESYSTEM_TLS",
                "FILESYSTEM_PROTOCOL",
                "FILESYSTEM_ENDPOINT",
                "FILESYSTEM_EXPORT",
                "FILESYSTEM_MOUNT_OPTIONS",
                "FILESTORE_INSTANCE",
                "FILESTORE_SHARE",
                "FILESTORE_IP",
                "GCP_PROJECT_ID",
                "GCP_LOCATION",
            ),
        ),
        ManagedServiceEntry(
            kind="topic",
            variant="pubsub_topic",
            plugin_id="gcp",
            description="Pub/Sub topic and subscriptions",
            binding_envs=(
                "TOPIC_ARN_OR_ID",
                "TOPIC_NAME",
                "TOPIC_REGION",
                "PUBSUB_TOPIC",
                "PUBSUB_TOPIC_ID",
                "PUBSUB_SUBSCRIPTIONS",
                "PUBSUB_SUBSCRIPTION",
                "GCP_PROJECT_ID",
            ),
        ),
        ManagedServiceEntry(
            kind="event_bus",
            variant="eventarc",
            plugin_id="gcp",
            description=(
                "Eventarc Advanced shared bus, pipelines, enrollments, Google API sources, "
                "and Eventarc Standard triggers and partner channels"
            ),
            binding_envs=(
                "EVENT_BUS_NAME",
                "EVENT_BUS_ID",
                "EVENT_BUS_REGION",
                "EVENT_BUS_PUBLISH_URL",
                "EVENT_BUS_PROVIDER",
                "GOOGLE_CLOUD_PROJECT",
            ),
        ),
        ManagedServiceEntry(
            kind="event_stream",
            variant="managed_kafka",
            plugin_id="gcp",
            description=(
                "Google Managed Kafka clusters, topics, ACLs, consumer offsets, "
                "Schema Registry, Connect clusters, and connectors"
            ),
            binding_envs=(
                "EVENT_STREAM_BROKERS",
                "EVENT_STREAM_TLS",
                "EVENT_STREAM_AUTH_MECHANISM",
                "EVENT_STREAM_CLIENT_CERT",
                "EVENT_STREAM_CLIENT_KEY",
                "EVENT_STREAM_CA_CERT",
                "GCP_MANAGED_KAFKA_CLUSTER",
                "GCP_MANAGED_KAFKA_BOOTSTRAP",
                "GCP_MANAGED_KAFKA_SCHEMA_REGISTRY",
                "SCHEMA_REGISTRY_URL",
                "GOOGLE_CLOUD_PROJECT",
                "GOOGLE_CLOUD_REGION",
            ),
        ),
        ManagedServiceEntry(
            kind="faas",
            variant="cloud_functions_gen2",
            plugin_id="gcp",
            status="planned",
            description="Cloud Run functions (2nd gen)",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="api_gateway",
            variant="api_gateway",
            plugin_id="gcp",
            status="planned",
            description="Google Cloud API Gateway",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="workflow_engine",
            variant="workflows",
            plugin_id="gcp",
            status="planned",
            description="Google Cloud Workflows",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="cdn",
            variant="cloud_cdn",
            plugin_id="gcp",
            status="planned",
            description="Cloud CDN backend and cache policy",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="encryption_key",
            variant="cloud_kms",
            plugin_id="gcp",
            status="preview",
            description="Cloud KMS key ring and key",
            binding_envs=(
                "ENCRYPTION_KEY_ID",
                "ENCRYPTION_KEY_ARN",
                "ENCRYPTION_KEY_ALIAS",
                "ENCRYPTION_KEY_SPEC",
                "ENCRYPTION_KEY_USAGE",
                "ENCRYPTION_KEY_MULTI_REGION",
                "GCP_KMS_KEY_NAME",
                "GCP_KMS_KEY_RING",
                "GCP_KMS_LOCATION",
                "GCP_KMS_PROTECTION_LEVEL",
                "GCP_PROJECT_ID",
            ),
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="private_endpoint",
            variant="private_service_connect",
            plugin_id="gcp",
            status="planned",
            description="Private Service Connect endpoint",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="observability",
            variant="cloud_operations",
            plugin_id="gcp",
            status="planned",
            description="Cloud Logging, Monitoring, and alert policies",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        # Azure
        ManagedServiceEntry(
            kind="object_store",
            variant="blob",
            plugin_id="azure",
            description="Azure Blob Storage container",
            binding_envs=(
                "AZURE_STORAGE_ACCOUNT",
                "AZURE_BLOB_CONTAINER",
                "AZURE_BLOB_ENDPOINT",
            ),
        ),
        ManagedServiceEntry(
            kind="queue",
            variant="servicebus",
            plugin_id="azure",
            description="Service Bus queue with dead-lettering",
            binding_envs=(
                "SERVICEBUS_NAMESPACE",
                "SERVICEBUS_QUEUE",
                "SERVICEBUS_ENDPOINT",
            ),
        ),
        ManagedServiceEntry(
            kind="postgres",
            variant="azure_pg_flex",
            plugin_id="azure",
            description="Azure Database for PostgreSQL Flexible Server",
        ),
        ManagedServiceEntry(
            kind="mysql",
            variant="azure_mysql_flex",
            plugin_id="azure",
            description="Azure Database for MySQL Flexible Server",
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="azure_cache_redis",
            plugin_id="azure",
            description="Azure Cache for Redis",
        ),
        ManagedServiceEntry(
            kind="object_store",
            variant="azure_blob",
            plugin_id="azure",
            description="Azure Blob Storage container (managed-service catalog id)",
        ),
        ManagedServiceEntry(
            kind="queue",
            variant="azure_servicebus",
            plugin_id="azure",
            description="Azure Service Bus queue (managed-service catalog id)",
        ),
        ManagedServiceEntry(
            kind="kv_store",
            variant="cosmos",
            plugin_id="azure",
            description="Azure Cosmos DB (NoSQL) container",
        ),
        ManagedServiceEntry(
            kind="search",
            variant="azure_ai_search_fulltext",
            plugin_id="azure",
            description="Azure AI Search full-text index",
        ),
        ManagedServiceEntry(
            kind="vector_index",
            variant="azure_ai_search_vector",
            plugin_id="azure",
            description="Azure AI Search vector index",
        ),
        ManagedServiceEntry(
            kind="time_series",
            variant="azure_monitor_prometheus",
            plugin_id="azure",
            description="Azure Monitor managed Prometheus",
        ),
        ManagedServiceEntry(
            kind="email",
            variant="azure_acs",
            plugin_id="azure",
            description="Azure Communication Services email",
        ),
        ManagedServiceEntry(
            kind="model_endpoint",
            variant="azure_openai",
            plugin_id="azure",
            description="Azure OpenAI model deployment",
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="azure_sql_database_serverless",
            plugin_id="azure",
            status="planned",
            description="Azure SQL Database serverless",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="azure_sql_database_provisioned",
            plugin_id="azure",
            status="planned",
            description="Azure SQL Database provisioned compute",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="azure_sql_elastic_pool",
            plugin_id="azure",
            status="planned",
            description="Azure SQL elastic pool",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="azure_sql_managed_instance",
            plugin_id="azure",
            status="planned",
            description="Azure SQL Managed Instance",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="azure_managed_redis",
            plugin_id="azure",
            status="planned",
            description="Azure Managed Redis",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="document_db",
            variant="cosmos_mongodb",
            plugin_id="azure",
            status="planned",
            description="Azure Cosmos DB for MongoDB",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="graph_db",
            variant="cosmos_gremlin",
            plugin_id="azure",
            status="planned",
            description="Azure Cosmos DB for Apache Gremlin",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="wide_column",
            variant="cosmos_cassandra",
            plugin_id="azure",
            status="planned",
            description="Azure Cosmos DB for Apache Cassandra",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="warehouse",
            variant="synapse_serverless",
            plugin_id="azure",
            status="planned",
            description="Azure Synapse serverless SQL pool",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="azure_files",
            plugin_id="azure",
            status="planned",
            description="Azure Files share",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="azure_netapp_files",
            plugin_id="azure",
            status="planned",
            description="Azure NetApp Files volume",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="topic",
            variant="service_bus_topic",
            plugin_id="azure",
            status="planned",
            description="Azure Service Bus topic and subscriptions",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="event_bus",
            variant="event_grid",
            plugin_id="azure",
            status="planned",
            description="Azure Event Grid topic and subscriptions",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="stream",
            variant="event_hubs",
            plugin_id="azure",
            status="planned",
            description="Azure Event Hubs namespace and event hub",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="event_stream",
            variant="event_hubs_kafka",
            plugin_id="azure",
            status="planned",
            description="Azure Event Hubs Kafka endpoint",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="faas",
            variant="azure_functions",
            plugin_id="azure",
            status="planned",
            description="Azure Functions application",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="api_gateway",
            variant="api_management",
            plugin_id="azure",
            status="planned",
            description="Azure API Management",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="workflow_engine",
            variant="logic_apps",
            plugin_id="azure",
            status="planned",
            description="Azure Logic Apps workflow",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="cdn",
            variant="front_door",
            plugin_id="azure",
            status="planned",
            description="Azure Front Door and CDN endpoint",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="sms",
            variant="communication_services_sms",
            plugin_id="azure",
            status="planned",
            description="Azure Communication Services SMS",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="encryption_key",
            variant="key_vault_key",
            plugin_id="azure",
            status="planned",
            description="Azure Key Vault key",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="private_endpoint",
            variant="private_link",
            plugin_id="azure",
            status="planned",
            description="Azure Private Link endpoint",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="observability",
            variant="azure_monitor",
            plugin_id="azure",
            status="planned",
            description="Azure Monitor logs, metrics, and alerts",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        # k8s_native (operator-backed)
        ManagedServiceEntry(
            kind="postgres",
            variant="cnpg",
            plugin_id="k8s_native",
            description="CloudNativePG-backed Postgres cluster",
            binding_envs=(
                "POSTGRES_HOST",
                "POSTGRES_PORT",
                "POSTGRES_DB",
                "POSTGRES_USER",
                "POSTGRES_PASSWORD",
            ),
        ),
        ManagedServiceEntry(
            kind="redis",
            variant="operator",
            plugin_id="k8s_native",
            description="Bitnami Redis operator with primary + replicas",
            binding_envs=("REDIS_HOST", "REDIS_PORT", "REDIS_PASSWORD"),
        ),
        ManagedServiceEntry(
            kind="mysql",
            variant="operator",
            plugin_id="k8s_native",
            description=("Percona XtraDB Cluster (default) / MariaDB / Oracle MySQL operator-backed cluster"),
            binding_envs=(
                "MYSQL_HOST",
                "MYSQL_PORT",
                "MYSQL_DB",
                "MYSQL_USER",
                "MYSQL_PASSWORD",
            ),
        ),
        ManagedServiceEntry(
            kind="document_db",
            variant="mongodb_operator",
            plugin_id="k8s_native",
            description="Percona Server for MongoDB operator",
            binding_envs=(
                "DOCDB_URI",
                "DOCDB_DB",
                "DOCDB_USER",
                "DOCDB_PASSWORD",
            ),
        ),
        ManagedServiceEntry(
            kind="event_stream",
            variant="kafka_strimzi",
            plugin_id="k8s_native",
            description="Strimzi-managed Kafka cluster (KRaft)",
            binding_envs=(
                "EVENT_STREAM_BROKERS",
                "EVENT_STREAM_USERNAME",
                "EVENT_STREAM_PASSWORD",
                "EVENT_STREAM_TLS",
            ),
        ),
        ManagedServiceEntry(
            kind="event_stream",
            variant="nats",
            plugin_id="k8s_native",
            description="NATS StatefulSet (with optional JetStream)",
            binding_envs=("EVENT_STREAM_BROKERS", "EVENT_STREAM_TLS"),
        ),
        ManagedServiceEntry(
            kind="queue",
            variant="rabbitmq_operator",
            plugin_id="k8s_native",
            description="RabbitMQ Cluster Operator-backed cluster",
            binding_envs=(
                "RABBITMQ_HOST",
                "RABBITMQ_PORT",
                "RABBITMQ_USER",
                "RABBITMQ_PASSWORD",
            ),
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="nfs_csi",
            plugin_id="k8s_native",
            description="NFS CSI driver-backed RWX PVC",
            binding_envs=(
                "FILESYSTEM_HANDLE",
                "FILESYSTEM_MOUNT_PATH",
                "FILESYSTEM_TLS",
            ),
        ),
        ManagedServiceEntry(
            kind="object_store",
            variant="seaweedfs_operator",
            plugin_id="k8s_native",
            status="preview",
            description="SeaweedFS Operator bucket and bucket-scoped S3 IAM identity",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
            binding_envs=(
                "BUCKET_NAME",
                "BUCKET_REGION",
                "BUCKET_ENDPOINT",
                "BUCKET_PREFIX",
                "AWS_ACCESS_KEY_ID",
                "AWS_SECRET_ACCESS_KEY",
                "AWS_S3_FORCE_PATH_STYLE",
            ),
        ),
        ManagedServiceEntry(
            kind="object_store",
            variant="minio_operator",
            plugin_id="k8s_native",
            status="deprecated",
            description="Retired community MinIO Operator (catalogue visibility only)",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="object_store",
            variant="minio_aistor_operator",
            plugin_id="k8s_native",
            status="planned",
            description="Commercial MinIO AIStor Operator tenant",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="object_store",
            variant="s3_compatible_existing",
            plugin_id="k8s_native",
            status="planned",
            description="Adopt an existing S3-compatible endpoint and credential bundle",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="mssql",
            variant="sqlserver_express",
            plugin_id="k8s_native",
            status="preview",
            description="SQL Server 2025 Express StatefulSet with durable PVC and encrypted TDS",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
            binding_envs=(
                "MSSQL_HOST",
                "MSSQL_PORT",
                "MSSQL_DB",
                "MSSQL_USER",
                "MSSQL_PASSWORD",
                "MSSQL_ENCRYPT",
                "MSSQL_TRUST_SERVER_CERTIFICATE",
                "DATABASE_URL",
            ),
        ),
        ManagedServiceEntry(
            kind="search",
            variant="opensearch_operator",
            plugin_id="k8s_native",
            status="preview",
            description="OpenSearch Kubernetes Operator cluster with tenant-scoped credentials",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
            binding_envs=(
                "SEARCH_ENDPOINT",
                "SEARCH_USER",
                "SEARCH_PASSWORD",
                "SEARCH_INDEX_PREFIX",
                "SEARCH_TLS_VERIFY",
            ),
        ),
        ManagedServiceEntry(
            kind="vector_index",
            variant="opensearch_operator_vector",
            plugin_id="k8s_native",
            status="preview",
            description="OpenSearch Operator k-NN index with explicit HNSW mapping",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
            binding_envs=(
                "VECTOR_ENDPOINT",
                "VECTOR_INDEX_NAME",
                "VECTOR_USERNAME",
                "VECTOR_PASSWORD",
                "VECTOR_TLS_VERIFY",
            ),
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="rook_cephfs",
            plugin_id="k8s_native",
            status="preview",
            description="Rook CephFS consumer-local RWX filesystem claims",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
            binding_envs=(
                "FILESYSTEM_HANDLE",
                "FILESYSTEM_MOUNT_PATH",
            ),
        ),
        ManagedServiceEntry(
            kind="filesystem",
            variant="storage_class_pvc",
            plugin_id="k8s_native",
            status="preview",
            description="Consumer-local StorageClass-backed persistent volume template",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
            binding_envs=(
                "FILESYSTEM_HANDLE",
                "FILESYSTEM_MOUNT_PATH",
            ),
        ),
        ManagedServiceEntry(
            kind="event_bus",
            variant="knative_eventing",
            plugin_id="k8s_native",
            status="planned",
            description="Knative Eventing broker and triggers",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="faas",
            variant="knative_service",
            plugin_id="k8s_native",
            status="preview",
            description="Knative Serving function with scale-to-zero and revision traffic control",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
            binding_envs=(
                "FUNCTION_NAME",
                "FUNCTION_ARN",
                "FUNCTION_URL",
                "FUNCTION_REGION",
            ),
        ),
        ManagedServiceEntry(
            kind="api_gateway",
            variant="gateway_api",
            plugin_id="k8s_native",
            status="planned",
            description="Kubernetes Gateway API resources",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="workflow_engine",
            variant="argo_workflows",
            plugin_id="k8s_native",
            status="planned",
            description="Argo Workflows installation and namespace binding",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="model_endpoint",
            variant="kserve",
            plugin_id="k8s_native",
            status="planned",
            description="KServe inference service",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
        ManagedServiceEntry(
            kind="observability",
            variant="kube_prometheus_stack",
            plugin_id="k8s_native",
            status="planned",
            description="Prometheus, Alertmanager, and Grafana stack",
            issue_url=_CROSS_CLOUD_PARITY_ISSUE,
        ),
    ),
)


__all__ = [
    "MATRIX",
    "OPTIONAL_ROLES",
    "REQUIRED_ROLES",
    "AvailabilityMatrix",
    "DriverEntry",
    "ManagedServiceEntry",
    "Status",
]
