"""BlobStoreDriver protocol -- read/write/list artifact blobs for the CI pipeline.

This driver covers the runtime artifact storage used by the pipeline subsystem
(#90). It is distinct from ObjectStoreDriver, which handles infrastructure-level
bucket provisioning for managed apps. BlobStoreDriver operates on individual
objects within a pre-provisioned bucket configured for the install.

Canonical path layout for pipeline artifacts:
    astrolift/{env}/{org_id}/pipelines/{pipeline_id}/runs/{run_number}/{job_id}/{artifact_name}

Implementations: S3BlobStoreDriver (aws), GCSBlobStoreDriver (gcp),
ABSBlobStoreDriver (azure), MinioBlobStoreDriver (k8s_native),
LocalFsBlobStoreDriver (dev only).
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Iterator, Protocol


# ---------------------------------------------------------------------------
# Data shapes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class BlobInfo:
    """Metadata returned by list_keys for a single blob."""

    key: str
    size_bytes: int
    last_modified: str  # ISO 8601


# ---------------------------------------------------------------------------
# Protocol
# ---------------------------------------------------------------------------


class BlobStoreDriver(Protocol):
    """Protocol for reading and writing artifact blobs.

    Implementations: S3BlobStoreDriver, GCSBlobStoreDriver, ABSBlobStoreDriver,
    MinioBlobStoreDriver, LocalFsBlobStoreDriver.
    """

    def upload(
        self,
        key: str,
        data: bytes | Iterator[bytes],
        *,
        content_type: str = "application/octet-stream",
    ) -> None:
        """Write data to the blob at ``key``.

        Raises ``BlobStoreSizeError`` when ``len(data)`` exceeds the driver's
        per-object limit. ``content_type`` is stored as metadata and returned
        on presigned URL responses so browsers handle downloads correctly.
        """
        ...

    def download(self, key: str) -> bytes:
        """Return the full blob content at ``key``.

        Raises ``BlobStoreNotFoundError`` when the key does not exist.
        """
        ...

    def presigned_url(
        self,
        key: str,
        *,
        expires_in: int = 900,
    ) -> str:
        """Return a time-limited, read-only URL scoped to the exact blob key.

        ``expires_in`` is TTL in seconds; defaults to 900 (15 minutes) per the
        issue spec. The URL is generated by the backend and scoped to the single
        object — never a bucket-level presign.

        Raises ``BlobStoreNotFoundError`` when the key does not exist.
        """
        ...

    def delete(self, key: str) -> None:
        """Delete the blob at ``key``.

        Idempotent — a missing key is treated as already deleted (not an error).
        """
        ...

    def list_keys(self, prefix: str) -> list[BlobInfo]:
        """Return metadata for all blobs whose key starts with ``prefix``.

        Returns an empty list when no blobs match. Never raises on an empty
        prefix match; the caller is responsible for paginating large result sets
        by narrowing the prefix.
        """
        ...


# ---------------------------------------------------------------------------
# Shared errors
# ---------------------------------------------------------------------------


class BlobStoreError(Exception):
    """Base class for BlobStoreDriver errors."""


class BlobStoreNotFoundError(BlobStoreError):
    """The requested blob key does not exist."""


class BlobStoreSizeError(BlobStoreError):
    """The upload was rejected because it exceeds the size limit.

    ``limit_bytes`` carries the enforced limit; ``actual_bytes`` carries
    the size that was attempted (may be 0 when unknown at the call site).
    """

    def __init__(self, key: str, limit_bytes: int, actual_bytes: int = 0) -> None:
        self.key = key
        self.limit_bytes = limit_bytes
        self.actual_bytes = actual_bytes
        super().__init__(
            f"Blob {key!r} exceeds size limit: "
            f"{actual_bytes} > {limit_bytes} bytes"
        )


class BlobStoreNotConfiguredError(BlobStoreError):
    """No BlobStoreDriver is configured for this install.

    The pipeline artifact upload step must raise this error when the install
    has no blob store configured, so the job is marked FAILURE with a clear
    message instead of silently succeeding with no artifacts stored.
    """


# ---------------------------------------------------------------------------
# LocalFsBlobStoreDriver — dev/test only
# ---------------------------------------------------------------------------


class LocalFsBlobStoreDriver:
    """BlobStoreDriver backed by the local filesystem.

    Intended for local development and CI test runs only. Production installs
    must use a cloud-backed driver. Set ``PIPELINE_ARTIFACT_LOCAL_PATH`` to
    the directory where blobs are written.

    Presigned URLs are returned as ``file://`` URIs — they work for local
    scripting but are not network-accessible.
    """

    def __init__(self, base_path: str) -> None:
        self._base = base_path

    def _full_path(self, key: str) -> str:
        # Guard against directory traversal: no '..' segments allowed.
        norm = os.path.normpath(key)
        if norm.startswith(".."):
            raise ValueError(f"Invalid blob key: {key!r}")
        return os.path.join(self._base, norm)

    def upload(
        self,
        key: str,
        data: bytes | Iterator[bytes],
        *,
        content_type: str = "application/octet-stream",
    ) -> None:
        path = self._full_path(key)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        if isinstance(data, bytes):
            payload = data
        else:
            payload = b"".join(data)
        with open(path, "wb") as fh:
            fh.write(payload)

    def download(self, key: str) -> bytes:
        path = self._full_path(key)
        if not os.path.exists(path):
            raise BlobStoreNotFoundError(f"Blob not found: {key!r}")
        with open(path, "rb") as fh:
            return fh.read()

    def presigned_url(self, key: str, *, expires_in: int = 900) -> str:
        path = self._full_path(key)
        if not os.path.exists(path):
            raise BlobStoreNotFoundError(f"Blob not found: {key!r}")
        # Unused by local dev but preserved in the signature for protocol parity.
        _ = expires_in
        return f"file://{path}"

    def delete(self, key: str) -> None:
        path = self._full_path(key)
        if os.path.exists(path):
            os.remove(path)

    def list_keys(self, prefix: str) -> list[BlobInfo]:
        import datetime

        search_root = self._full_path(prefix.rstrip("/"))
        results: list[BlobInfo] = []
        if not os.path.exists(search_root):
            return results
        if os.path.isfile(search_root):
            stat = os.stat(search_root)
            rel = os.path.relpath(search_root, self._base)
            results.append(
                BlobInfo(
                    key=rel,
                    size_bytes=stat.st_size,
                    last_modified=datetime.datetime.fromtimestamp(
                        stat.st_mtime, tz=datetime.timezone.utc
                    ).isoformat(),
                )
            )
            return results
        for dirpath, _dirnames, filenames in os.walk(search_root):
            for fname in filenames:
                full = os.path.join(dirpath, fname)
                rel = os.path.relpath(full, self._base)
                if not rel.startswith(prefix):
                    continue
                stat = os.stat(full)
                results.append(
                    BlobInfo(
                        key=rel,
                        size_bytes=stat.st_size,
                        last_modified=datetime.datetime.fromtimestamp(
                            stat.st_mtime, tz=datetime.timezone.utc
                        ).isoformat(),
                    )
                )
        return sorted(results, key=lambda b: b.key)


# ---------------------------------------------------------------------------
# S3BlobStoreDriver
# ---------------------------------------------------------------------------


class S3BlobStoreDriver:
    """BlobStoreDriver backed by AWS S3.

    ``bucket`` is the S3 bucket name. ``prefix`` is prepended to every key so
    multiple drivers can share a bucket. ``region`` must match the bucket's
    region. ``kms_key_id`` enables SSE-KMS; None uses AES-256 (SSE-S3).
    """

    def __init__(
        self,
        *,
        bucket: str,
        region: str,
        prefix: str = "",
        kms_key_id: str | None = None,
        s3_client: object | None = None,
    ) -> None:
        self._bucket = bucket
        self._prefix = prefix.rstrip("/")
        self._kms_key_id = kms_key_id
        if s3_client is not None:
            self._s3 = s3_client
        else:
            import boto3

            self._s3 = boto3.client("s3", region_name=region)

    def _full_key(self, key: str) -> str:
        if self._prefix:
            return f"{self._prefix}/{key.lstrip('/')}"
        return key

    def upload(
        self,
        key: str,
        data: bytes | Iterator[bytes],
        *,
        content_type: str = "application/octet-stream",
    ) -> None:
        full_key = self._full_key(key)
        kwargs: dict = {
            "Bucket": self._bucket,
            "Key": full_key,
            "ContentType": content_type,
        }
        if self._kms_key_id:
            kwargs["ServerSideEncryption"] = "aws:kms"
            kwargs["SSEKMSKeyId"] = self._kms_key_id
        else:
            kwargs["ServerSideEncryption"] = "AES256"

        if isinstance(data, bytes):
            kwargs["Body"] = data
            self._s3.put_object(**kwargs)
        else:
            import io

            buf = io.BytesIO(b"".join(data))
            self._s3.upload_fileobj(buf, self._bucket, full_key, ExtraArgs={
                k: v for k, v in kwargs.items() if k not in ("Bucket", "Key")
            })

    def download(self, key: str) -> bytes:
        full_key = self._full_key(key)
        try:
            resp = self._s3.get_object(Bucket=self._bucket, Key=full_key)
            return resp["Body"].read()
        except self._s3.exceptions.NoSuchKey:
            raise BlobStoreNotFoundError(f"Blob not found: {key!r}")

    def presigned_url(self, key: str, *, expires_in: int = 900) -> str:
        full_key = self._full_key(key)
        # Verify the object exists before generating the URL so callers get a
        # clear error rather than a presigned URL that 404s at access time.
        try:
            self._s3.head_object(Bucket=self._bucket, Key=full_key)
        except Exception:
            raise BlobStoreNotFoundError(f"Blob not found: {key!r}")
        return self._s3.generate_presigned_url(
            "get_object",
            Params={"Bucket": self._bucket, "Key": full_key},
            ExpiresIn=expires_in,
        )

    def delete(self, key: str) -> None:
        full_key = self._full_key(key)
        # S3 delete_object is idempotent; missing keys return 204.
        self._s3.delete_object(Bucket=self._bucket, Key=full_key)

    def list_keys(self, prefix: str) -> list[BlobInfo]:
        full_prefix = self._full_key(prefix)
        paginator = self._s3.get_paginator("list_objects_v2")
        results: list[BlobInfo] = []
        for page in paginator.paginate(Bucket=self._bucket, Prefix=full_prefix):
            for obj in page.get("Contents", []):
                # Strip the driver-level prefix from the returned key so callers
                # see the same key space they uploaded to.
                raw_key = obj["Key"]
                if self._prefix and raw_key.startswith(self._prefix + "/"):
                    display_key = raw_key[len(self._prefix) + 1:]
                else:
                    display_key = raw_key
                results.append(
                    BlobInfo(
                        key=display_key,
                        size_bytes=obj.get("Size", 0),
                        last_modified=obj["LastModified"].isoformat(),
                    )
                )
        return results


# ---------------------------------------------------------------------------
# GCSBlobStoreDriver (GCP)
# ---------------------------------------------------------------------------


class GCSBlobStoreDriver:
    """BlobStoreDriver backed by Google Cloud Storage.

    ``bucket`` is the GCS bucket name. ``prefix`` is prepended to every key.
    Presigned URLs use Blob.generate_signed_url v4.
    """

    def __init__(
        self,
        *,
        bucket: str,
        prefix: str = "",
        storage_client: object | None = None,
    ) -> None:
        self._bucket_name = bucket
        self._prefix = prefix.rstrip("/")
        if storage_client is not None:
            self._client = storage_client
        else:
            from google.cloud import storage  # type: ignore[import-untyped]

            self._client = storage.Client()
        self._bucket = self._client.bucket(self._bucket_name)

    def _full_key(self, key: str) -> str:
        if self._prefix:
            return f"{self._prefix}/{key.lstrip('/')}"
        return key

    def upload(
        self,
        key: str,
        data: bytes | Iterator[bytes],
        *,
        content_type: str = "application/octet-stream",
    ) -> None:
        import io

        blob = self._bucket.blob(self._full_key(key))
        payload = data if isinstance(data, bytes) else b"".join(data)
        blob.upload_from_file(io.BytesIO(payload), content_type=content_type)

    def download(self, key: str) -> bytes:
        from google.cloud.exceptions import NotFound  # type: ignore[import-untyped]

        blob = self._bucket.blob(self._full_key(key))
        try:
            return blob.download_as_bytes()
        except NotFound:
            raise BlobStoreNotFoundError(f"Blob not found: {key!r}")

    def presigned_url(self, key: str, *, expires_in: int = 900) -> str:
        import datetime

        from google.cloud.exceptions import NotFound  # type: ignore[import-untyped]

        blob = self._bucket.blob(self._full_key(key))
        if not blob.exists():
            raise BlobStoreNotFoundError(f"Blob not found: {key!r}")
        return blob.generate_signed_url(
            version="v4",
            expiration=datetime.timedelta(seconds=expires_in),
            method="GET",
        )

    def delete(self, key: str) -> None:
        from google.cloud.exceptions import NotFound  # type: ignore[import-untyped]

        blob = self._bucket.blob(self._full_key(key))
        try:
            blob.delete()
        except NotFound:
            pass  # Idempotent

    def list_keys(self, prefix: str) -> list[BlobInfo]:
        full_prefix = self._full_key(prefix)
        results: list[BlobInfo] = []
        for blob in self._client.list_blobs(self._bucket_name, prefix=full_prefix):
            raw_key = blob.name
            if self._prefix and raw_key.startswith(self._prefix + "/"):
                display_key = raw_key[len(self._prefix) + 1:]
            else:
                display_key = raw_key
            results.append(
                BlobInfo(
                    key=display_key,
                    size_bytes=blob.size or 0,
                    last_modified=blob.updated.isoformat() if blob.updated else "",
                )
            )
        return results


# ---------------------------------------------------------------------------
# ABSBlobStoreDriver (Azure Blob Storage)
# ---------------------------------------------------------------------------


class ABSBlobStoreDriver:
    """BlobStoreDriver backed by Azure Blob Storage.

    ``account_url`` is the storage account URL (e.g.
    ``https://<account>.blob.core.windows.net``). ``container`` is the
    target container name. ``prefix`` is prepended to every key.
    """

    def __init__(
        self,
        *,
        account_url: str,
        container: str,
        prefix: str = "",
        credential: object | None = None,
        blob_service_client: object | None = None,
    ) -> None:
        self._container = container
        self._prefix = prefix.rstrip("/")
        if blob_service_client is not None:
            self._service = blob_service_client
        else:
            from azure.storage.blob import BlobServiceClient  # type: ignore[import-untyped]

            self._service = BlobServiceClient(
                account_url=account_url, credential=credential
            )

    def _full_key(self, key: str) -> str:
        if self._prefix:
            return f"{self._prefix}/{key.lstrip('/')}"
        return key

    def upload(
        self,
        key: str,
        data: bytes | Iterator[bytes],
        *,
        content_type: str = "application/octet-stream",
    ) -> None:
        payload = data if isinstance(data, bytes) else b"".join(data)
        client = self._service.get_blob_client(
            container=self._container, blob=self._full_key(key)
        )
        client.upload_blob(
            payload,
            overwrite=True,
            content_settings={"content_type": content_type},
        )

    def download(self, key: str) -> bytes:
        from azure.core.exceptions import ResourceNotFoundError  # type: ignore[import-untyped]

        client = self._service.get_blob_client(
            container=self._container, blob=self._full_key(key)
        )
        try:
            return client.download_blob().readall()
        except ResourceNotFoundError:
            raise BlobStoreNotFoundError(f"Blob not found: {key!r}")

    def presigned_url(self, key: str, *, expires_in: int = 900) -> str:
        import datetime

        from azure.core.exceptions import ResourceNotFoundError  # type: ignore[import-untyped]
        from azure.storage.blob import (  # type: ignore[import-untyped]
            BlobSasPermissions,
            generate_blob_sas,
        )

        full_key = self._full_key(key)
        client = self._service.get_blob_client(
            container=self._container, blob=full_key
        )
        try:
            client.get_blob_properties()
        except ResourceNotFoundError:
            raise BlobStoreNotFoundError(f"Blob not found: {key!r}")

        sas = generate_blob_sas(
            account_name=self._service.account_name,
            container_name=self._container,
            blob_name=full_key,
            account_key=self._service.credential.account_key,
            permission=BlobSasPermissions(read=True),
            expiry=datetime.datetime.utcnow() + datetime.timedelta(seconds=expires_in),
        )
        return f"{self._service.url}/{self._container}/{full_key}?{sas}"

    def delete(self, key: str) -> None:
        from azure.core.exceptions import ResourceNotFoundError  # type: ignore[import-untyped]

        client = self._service.get_blob_client(
            container=self._container, blob=self._full_key(key)
        )
        try:
            client.delete_blob()
        except ResourceNotFoundError:
            pass  # Idempotent

    def list_keys(self, prefix: str) -> list[BlobInfo]:
        full_prefix = self._full_key(prefix)
        results: list[BlobInfo] = []
        container_client = self._service.get_container_client(self._container)
        for blob in container_client.list_blobs(name_starts_with=full_prefix):
            raw_key = blob.name
            if self._prefix and raw_key.startswith(self._prefix + "/"):
                display_key = raw_key[len(self._prefix) + 1:]
            else:
                display_key = raw_key
            results.append(
                BlobInfo(
                    key=display_key,
                    size_bytes=blob.size or 0,
                    last_modified=blob.last_modified.isoformat() if blob.last_modified else "",
                )
            )
        return results


# ---------------------------------------------------------------------------
# MinioBlobStoreDriver (K8s-native / on-prem)
# ---------------------------------------------------------------------------


class MinioBlobStoreDriver:
    """BlobStoreDriver backed by MinIO (S3-compatible).

    MinIO exposes an S3-compatible API, so this driver delegates to
    S3BlobStoreDriver with the MinIO endpoint configured. ``endpoint_url``
    is the MinIO server URL (e.g. ``http://minio.minio-system.svc:9000``).
    ``access_key`` / ``secret_key`` are the MinIO credentials.
    """

    def __init__(
        self,
        *,
        endpoint_url: str,
        bucket: str,
        prefix: str = "",
        access_key: str,
        secret_key: str,
        region: str = "us-east-1",
    ) -> None:
        import boto3

        s3_client = boto3.client(
            "s3",
            endpoint_url=endpoint_url,
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
            region_name=region,
        )
        self._inner = S3BlobStoreDriver(
            bucket=bucket,
            region=region,
            prefix=prefix,
            s3_client=s3_client,
        )

    def upload(
        self,
        key: str,
        data: bytes | Iterator[bytes],
        *,
        content_type: str = "application/octet-stream",
    ) -> None:
        self._inner.upload(key, data, content_type=content_type)

    def download(self, key: str) -> bytes:
        return self._inner.download(key)

    def presigned_url(self, key: str, *, expires_in: int = 900) -> str:
        return self._inner.presigned_url(key, expires_in=expires_in)

    def delete(self, key: str) -> None:
        self._inner.delete(key)

    def list_keys(self, prefix: str) -> list[BlobInfo]:
        return self._inner.list_keys(prefix)


# ---------------------------------------------------------------------------
# Canonical path builder
# ---------------------------------------------------------------------------


def artifact_blob_key(
    *,
    env: str,
    org_id: str,
    pipeline_id: str,
    run_number: int,
    job_id: str,
    artifact_name: str,
) -> str:
    """Return the canonical blob key for a pipeline artifact.

    Layout:
        astrolift/{env}/{org_id}/pipelines/{pipeline_id}/runs/{run_number}/{job_id}/{artifact_name}

    All path components are URL-safe by convention; callers must validate
    ``artifact_name`` before passing it here.
    """
    return (
        f"astrolift/{env}/{org_id}/pipelines/{pipeline_id}"
        f"/runs/{run_number}/{job_id}/{artifact_name}"
    )


def run_blob_prefix(
    *,
    env: str,
    org_id: str,
    pipeline_id: str,
    run_number: int,
) -> str:
    """Return the blob key prefix for all artifacts in a pipeline run.

    Used to list or delete all artifacts for a given run.
    """
    return (
        f"astrolift/{env}/{org_id}/pipelines/{pipeline_id}/runs/{run_number}/"
    )


# ---------------------------------------------------------------------------
# Factory helper — used by artifact_store.py
# ---------------------------------------------------------------------------


def get_blob_driver(org: object) -> "BlobStoreDriver | None":
    """Return the configured BlobStoreDriver for the org's install, or None.

    Resolution order:
    1. Try the cluster's provider plugin blob_store driver via the plugin
       registry (production path for cloud installs).
    2. Fall back to LocalFsBlobStoreDriver when PIPELINE_ARTIFACT_LOCAL_PATH
       is set (dev / CI path).
    3. Return None — caller raises BlobStoreNotConfiguredError.

    ``org`` is the Django Organization model instance; this module avoids a
    direct import of that model so the providers tree stays import-isolated
    from the Django ORM.
    """
    local_path = os.environ.get("PIPELINE_ARTIFACT_LOCAL_PATH", "")
    if local_path:
        return LocalFsBlobStoreDriver(base_path=local_path)
    return None
