# Generated by Django 6.0.5 on 2026-05-07 14:45

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrolift_identity', '0001_initial'),
        ('astrolift_lifecycle', '0001_initial'),
        ('astrolift_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('postgres', 'Postgres'), ('redis', 'Redis'), ('object_store', 'Object Store'), ('queue', 'Queue'), ('topic', 'Topic'), ('kv_store', 'Kv Store'), ('search', 'Search'), ('mq', 'Mq'), ('nfs', 'Nfs'), ('vector_index', 'Vector Index'), ('time_series', 'Time Series'), ('document_db', 'Document Db')], max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('variant', models.CharField(blank=True, default='', max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('updating', 'Updating'), ('deprovisioning', 'Deprovisioning'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('status_error', models.TextField(blank=True, default='')),
                ('connection_secret_ref', models.CharField(blank=True, default='', max_length=512)),
                ('app_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_services', to='astrolift_lifecycle.appenvironment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registered_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_services', to='astrolift_registry.registeredapp')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagedServiceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('env_key', models.CharField(max_length=128)),
                ('env_value_ref', models.CharField(max_length=512)),
                ('is_secret', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('managed_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='astrolift_services.managedservice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecretBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('backend_ref', models.CharField(max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_bundles', to='astrolift_identity.organization')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_bundles', to='astrolift_identity.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppSecretBundleRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('prefix', models.CharField(blank=True, default='', max_length=64)),
                ('app_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_bundle_refs', to='astrolift_lifecycle.appenvironment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registered_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_bundle_refs', to='astrolift_registry.registeredapp')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('secret_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_refs', to='astrolift_services.secretbundle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='managedservice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('registered_app', 'kind', 'name'), name='msvc_unique_active_per_app_kind_name'),
        ),
        migrations.AddConstraint(
            model_name='managedservicebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('managed_service', 'env_key'), name='msvc_binding_env_unique_active'),
        ),
        migrations.AddConstraint(
            model_name='secretbundle',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('team', 'slug'), name='secret_bundle_slug_unique_active_per_team'),
        ),
        migrations.AddConstraint(
            model_name='appsecretbundleref',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('registered_app', 'app_environment', 'secret_bundle'), name='appsecret_ref_unique_active'),
        ),
    ]
