export const routeLabels: Record<string, string> = {
  dashboard: "Dashboard",
  table: "Products",
  form: "User management",
  settings: "Settings",
  general: "General",
  team: "Team",
  billing: "Billing",
  playground: "Playground",
  history: "History",
  starred: "Starred",
  models: "Models",
  genesis: "Genesis",
  explorer: "Explorer",
  quantum: "Quantum",
  hooks: "Hooks",
  secured: "Secured page",
  documentation: "Documentation",
  introduction: "Introduction",
  "get-started": "Get Started",
  tutorials: "Tutorials",
  changelog: "Changelog",
  forms: "Form Engine",
  submit: "Fill Out",
  workflows: "Workflows",
  builder: "Builder",
  new: "Create New",
};
