import type { ModelConnectionRequestFieldsFragment } from "@/graphql/__generated__/operations";
import type { ModelConnectionRequestProps } from "./ModelConnectionRequestScreen";
import type { ModelConnectionPolicyProps } from "./ModelConnectionPolicyPanel";
export const connectionRequestRow: ModelConnectionRequestFieldsFragment = {
  id: "request-one",
  version: 2,
  status: "PENDING",
  organizationId: "org",
  modelDeploymentId: "shared-model",
  appId: "app-storefront",
  appEnvironmentId: "env-staging",
  clusterId: "cluster-one",
  providerId: "provider-one",
  alias: "chat",
  modelName: "Qwen production",
  appName: "Storefront",
  environmentName: "staging",
  requesterUsername: "owner@example.test",
  policyVersion: "policy-revision",
  requiredApprovals: 2,
  approvalCount: 0,
  canApprove: false,
  canReject: false,
  canCancel: true,
  canFinalize: false,
  subscriptionId: null,
  createdAt: "2026-10-03T12:00:00Z",
  decidedAt: null,
  finalizedAt: null,
};
export const connectionRequestProps: ModelConnectionRequestProps = {
  scopeKey: "owner:org:request",
  row: connectionRequestRow,
  loading: false,
  stale: false,
  error: null,
  supported: true,
  supportError: null,
  onRetry: () => {},
  onRetrySupport: () => {},
  onSubmit: async () => ({ accepted: true, row: connectionRequestRow }),
  onAccepted: async () => {},
};
export const connectionPolicyProps: ModelConnectionPolicyProps = {
  scopeKey: "owner:org:policy",
  restriction: false,
  policy: {
    id: "policy-one",
    version: 3,
    mode: "REQUIRE_APPROVAL",
    requiredApprovals: 2,
    allowSelfApproval: false,
  },
  loading: false,
  stale: false,
  error: null,
  supported: true,
  supportError: null,
  canEdit: true,
  onRetry: () => {},
  onRetrySupport: () => {},
  onSubmit: async (input) => ({
    accepted: true,
    policy: { ...input.policy, ...input.draft, version: 4 },
  }),
  onAccepted: async () => {},
};
