import type { SharedModelDetailScreenProps } from "./SharedModelDetailScreen";
export const sharedModelDetailProps: SharedModelDetailScreenProps = {
  model: {
    id: "shared-model",
    version: 5,
    name: "Qwen production",
    organizationId: "org",
    clusterId: "cluster-one",
    providerId: "provider-one",
    clusterSlug: "production",
    clusterName: "Production",
    sourceKind: "huggingface",
    localArtifactId: null,
    localArtifactVersion: null,
    localManifestSha256: null,
    modelRepo: "Qwen/Qwen3-8B",
    revisionSha: "a".repeat(40),
    computeMode: "gpu",
    subscriptionsEnabled: true,
    runtimeSupported: true,
    runtimeReason: null,
    status: "active",
    reason: null,
    ready: true,
    readinessObservedAt: "2026-09-30T15:30:00Z",
    readinessGeneration: 8,
    desiredSubscriptionRevision: 3,
    appliedSubscriptionRevision: 3,
    operationId: "operation-model-123",
    operationStartedAt: "2026-09-30T15:25:00Z",
    operationCompletedAt: "2026-09-30T15:30:00Z",
    desiredResources: {
      cpuRequest: "2",
      memoryRequest: "8Gi",
      gpuCount: 1,
      replicas: 1,
      cpuKvCacheGiB: null,
    },
    appliedResources: {
      cpuRequest: "2",
      memoryRequest: "8Gi",
      gpuCount: 1,
      replicas: 1,
      cpuKvCacheGiB: null,
    },
  },
  loading: false,
  stale: false,
  error: null,
  onRetry: () => {},
  subscriptions: null,
  observations: null,
  prompt: null,
};
