"""Render docs/campaign_spend.md from the certification spend ledger (#1417).

Run via ``make campaign-spend`` from backend/providers. The rendered report is
committed so the spend decision is reviewable in a diff: a PR that classifies a
variant, or adds a pricing path, moves the coverage numbers next to the code
that moved them.

``render()`` is importable so the drift test can compare the committed file
against a fresh render without shelling out, the same contract as
``scripts/coverage_matrix.py``.
"""

from __future__ import annotations

from pathlib import Path

from _cert.spend import (
    CAMPAIGN_SIZE,
    PASSES,
    Meter,
    Priceability,
    all_spend,
    bookings,
    campaign_slug,
    cluster_demand,
    dominant_bookings,
    exposures,
    priceability_counts,
    stranded_burn,
    window,
)

OUTPUT = Path(__file__).resolve().parents[1] / "docs" / "campaign_spend.md"

_METER_LABEL = {
    Meter.HOURLY_FLOOR: "hourly floor",
    Meter.FIXED_FLOOR: "fixed floor",
    Meter.PER_REQUEST: "per request",
    Meter.CLUSTER: "cluster capacity",
    Meter.UNKNOWN: "**unknown**",
}

_PRICEABILITY_LABEL = {
    Priceability.EXACT: "exact",
    Priceability.APPROXIMATE: "approximate",
    Priceability.NO_ESTIMATOR: "none",
    Priceability.NOT_A_CLOUD_SKU: "n/a (in-cluster)",
}


def _hours(value: float) -> str:
    return f"{value:,.1f}"


def _header() -> list[str]:
    counts = priceability_counts()
    total_bookings = sum(counts.values())
    total = exposures()[-1]
    return [
        "# Certification Campaign Spend",
        "",
        "Generated by `make campaign-spend` (backend/providers/scripts/campaign_spend.py)",
        "from `_cert/spend.py` -- do not hand-edit.",
        "",
        f"The estimate #1417 has been waiting on, for the spec 43 campaign `{campaign_slug()}`:",
        "the happy path on three clouds plus the 69-cell per-kind grid, each cell run",
        f"through the full lifecycle cycle {PASSES}x because the campaign's own definition of",
        "GREEN requires an unattended second run (spec 43 §0.1 step 7).",
        "",
        "## Read this first",
        "",
        f"**{total_bookings} of {total_bookings} bookings are unpriced in dollars.** Cost figures come from the",
        "cloud's live pricing API and never from a table in this repository",
        "(`_sdk/cost.py`). Nothing is vendored or cached in the tree and this report is",
        "generated offline, so it prices nothing and says so per booking rather than",
        "filling the gap with a plausible number.",
        "",
        f"**{total.unknown} of {total_bookings} bookings have no billing class at all.** `_cert/billing.py` classifies",
        "AWS preview variants only. Every GCP and Azure variant, and every AWS variant",
        "the campaign actually books on the happy path, raises `UnclassifiedVariant`.",
        "That is not a reporting gap -- `check_may_run` refuses to provision an",
        "unclassified variant, so the campaign cannot start against most of its own grid",
        "regardless of what any estimate says.",
        "",
        "**The most useful thing here is the shopping list.** Every cell books",
        f"`size={CAMPAIGN_SIZE}` (the manifests declare no size and the provision activity",
        "defaults it), and each driver resolves that to a concrete capacity in code. The",
        "per-cell table below names it. Multiply by a live unit price and the estimate is",
        "finished; that multiplication is the only step this report cannot do.",
        "",
    ]


def _what_a_real_number_needs() -> list[str]:
    counts = priceability_counts()
    return [
        "## What a real number requires",
        "",
        "In order, cheapest first. The first two need no cloud account.",
        "",
        "1. **Classify the grid in `_cert/billing.py`.** A table edit, offline, no",
        "   credentials. Until it lands, the spend gate blocks the campaign and this",
        "   report cannot say which cells dominate -- the question #1417 is actually",
        "   asking. This is the blocking item.",
        "2. **Fix the estimators that over-count.** `_sdk/cost_skus.py` resolves one",
        "   catalog row per billable dimension and refuses on ambiguity. GCP's Cloud SQL",
        "   path uses it; the AWS and Azure estimators still sum whatever their filter",
        f"   returns, which is why {counts[Priceability.APPROXIMATE]} bookings are marked approximate not exact",
        "   (#1318). An approximate estimate is what a class C pre-flight would log today,",
        "   and #1417 decision 2 makes that log the thing that unlocks the spend.",
        "3. **Map the variants that have no estimator.** Azure's",
        "   `SERVICE_NAME_BY_VARIANT` still keys on `flexible_server`, `cache`, `cosmos`",
        "   and `files`, none of which exist in the availability matrix, and on `blob` and",
        "   `servicebus` where the campaign books the `azure_blob` / `azure_servicebus`",
        "   aliases. No Azure cell in the grid resolves a pricing path.",
        "4. **Run the estimator with credentials**, once, per cell, before provisioning",
        "   anything. That is the only step that produces dollars.",
        "",
    ]


def _window_section() -> list[str]:
    win = window()
    return [
        "## The metered window",
        "",
        "How long a cell holds a resource, bounded by the harness's own declared",
        "timeouts. These are **ceilings, not expectations**: a cell that provisions in",
        "four minutes bills for four minutes. A ceiling is the right shape for an",
        "approval, because the approval has to cover the bad day.",
        "",
        "| Step | Ceiling | Composed from |",
        "| --- | --- | --- |",
        f"| BUILDOUT | {win.buildout_s / 60:,.0f} min | two `provision_poll` waits (app, then services)"
        " plus one deploy |",
        f"| UPDATE | {win.update_s / 60:,.0f} min | three deploys: forward, rollback, forward again |",
        f"| TEARDOWN | {win.teardown_s / 60:,.0f} min | one `teardown_poll` wait, floored by the"
        " 5 min deregister grace |",
        f"| **one pass** | **{win.cycle_hours:,.2f} h** | steps 1-6 of the lifecycle cycle |",
        f"| **one cell** | **{win.campaign_hours:,.2f} h** | both passes, because GREEN requires the second |",
        "",
        "Read from `LifecycleRunner.provision_poll` / `.teardown_poll` /",
        "`.include_rollback` and `CliPlatformClient.timeout_s` rather than restated, so",
        "retuning a timeout moves this table. The five HTTP probes in VERIFY-UP and",
        "VERIFY-UPD are bounded at 60s each and omitted: 5 min against a 5 h ceiling is",
        "below the resolution of anything this report decides.",
        "",
    ]


def _exposure_section() -> list[str]:
    win = window()
    out = [
        "## Exposure, per cloud and in total",
        "",
        "Resource-hours, not dollars: the hours are known and the rate is not. Counts",
        "are bookings (a per-kind cell books one managed service, a happy-path cell",
        "books four), and hours already include both passes.",
        "",
        "| | Cells | Bookings | Hourly floor | Fixed floor | Per request | Cluster | Unknown"
        " | Metered hours | Unknown ceiling |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for item in exposures():
        out.append(
            f"| {item.label} | {item.cells} | {item.bookings} | {item.hourly_floor} | "
            f"{item.fixed_floor} | {item.per_request} | {item.cluster} | **{item.unknown}** | "
            f"{_hours(item.hours(win))} | {_hours(item.unknown_hours(win))} |"
        )
    total = exposures()[-1]
    out += [
        "",
        f"**Metered hours** covers only the {total.time_metered} bookings whose shape is known -- and every",
        "one of them is on AWS. A tri-cloud campaign whose entire quantifiable metered",
        "exposure sits on one cloud is not a costed campaign; it is a costed third of",
        "one.",
        "",
        f"**Unknown ceiling** is what the {total.unknown} unclassified bookings would add if every one of",
        "them turned out to meter hourly. It is the size of the ignorance, not an",
        "estimate of the cost, and folding it into a single total would produce exactly",
        "the confident wrong number this report exists to avoid.",
        "",
        "Two categories are excluded from both columns on purpose. Per-request bookings",
        "cost nothing measurable: the campaign publishes a handful of messages through",
        "the fixture's `/selftest`. Cluster-capacity bookings are pods on a tenant",
        "cluster that bills for the campaign's whole wall clock whether the cell runs or",
        "not, so charging them to the cell would double-count a floor already paid.",
        "",
    ]
    return out


def _dominant_section() -> list[str]:
    win = window()
    dominant = dominant_bookings()
    total = exposures()[-1]
    out = [
        "## Which cells dominate",
        "",
        "By construction the hourly-floor bookings are the whole decision: they are the",
        "only ones whose cost moves when the campaign runs long, runs twice, or fails to",
        "tear down. Everything else is either flat or free.",
        "",
        f"{len(dominant)} bookings are known to sit on an hourly floor:",
        "",
        "| Cloud | Kind | Variant | Books at `small` | Why hourly |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in sorted(dominant, key=lambda b: (b.cloud, b.kind)):
        units = ", ".join(f"`{name}` = {value}" for name, value in item.units) or "-"
        out.append(f"| {item.cloud} | `{item.kind}` | `{item.variant}` | {units} | {item.meter_reason} |")
    out += [
        "",
        f"**This list is not the answer, and the gap is the finding.** {total.unknown} bookings have no",
        "billing class, and the ones a reader would expect to dominate are inside that",
        "group: RDS, ElastiCache, OpenSearch, Cloud SQL, Memorystore, Azure Postgres",
        "Flexible, Cosmos, Azure Cache for Redis. Naming them as hourly here would mean",
        "asserting a billing shape that `_cert/billing.py` has not reviewed, which is the",
        "same shortcut that module refuses to take when it declines to sweep an",
        "unclassified variant into class A. The ranking arrives when the table does.",
        "",
        "### The lever, once the ranking exists",
        "",
        f"Each cell runs {PASSES}x, so the hourly-floor set is charged twice: {_hours(win.cycle_hours)} h per pass,",
        f"{_hours(win.campaign_hours)} h per cell. Two levers, neither free:",
        "",
        "- **Run the expensive cells once.** This is the obvious saving and it is not a",
        "  saving: REPRODUCE is what certifies a cell, so dropping it downgrades that cell",
        "  to uncertified rather than making a certified one cheaper. Defensible only for",
        "  a variant with no evidence of demand, which is decision 4's argument applied",
        "  per cell instead of per class.",
        "- **Shrink the window.** The ceiling is dominated by UPDATE's three deploys.",
        "  `LifecycleRunner.include_rollback=False` removes two of them and cuts the",
        f"  per-cell ceiling from {_hours(win.campaign_hours)} h to "
        f"{_hours((win.buildout_s + win.update_s / 3 + win.teardown_s) / 3600 * PASSES)} h, at the cost of not",
        "  exercising rollback. The campaign exists partly to exercise rollback.",
        "",
    ]
    return out


def _stranded_section() -> list[str]:
    burn = stranded_burn()
    demand = cluster_demand()
    return [
        "## The cost of leaving it running",
        "",
        "The campaign's financial risk is not the run. A run is bounded by the window",
        "above and stops. A teardown that fails is unbounded: it bills until somebody",
        "notices, and the thing that makes somebody notice is the orphan scanner",
        "(`_cert/orphans/`). This is that number, and it is why the scanner is not",
        "cleanup hygiene.",
        "",
        "If the entire grid were stranded -- every distinct booking left provisioned:",
        "",
        "| Meter | Bookings | Accrues while stranded |",
        "| --- | ---: | --- |",
        f"| hourly floor | {burn.hourly_floor} | yes, {burn.hourly_floor * 24} resource-hours per day |",
        f"| fixed floor | {burn.fixed_floor} | yes, small and flat |",
        f"| cluster capacity | {burn.cluster} | yes, as pods on a cluster already billing |",
        f"| per request | {burn.per_request} | no; idle costs nothing |",
        f"| **unknown** | **{burn.unknown}** | **cannot say** |",
        "",
        f"**{burn.resource_hours_per_day} resource-hours per day** accrue from the bookings whose shape is known,",
        f"and up to **{burn.unknown_hours_per_day} more** from the {burn.unknown} whose shape is not. A week unnoticed",
        "multiplies both by seven. Against that, one cell's entire certified lifecycle",
        "is under ten hours.",
        "",
        "Two properties of this tree make the stranded case more likely than it sounds,",
        "both already recorded on #1471: the campaign tag never reaches a resource",
        "because `_provision_sync` builds its `ProvisionSpec` without `tags=`, and two",
        "GCP drivers drop `spec.tags` even when populated. A scanner that cannot see a",
        "resource reports clean, which is the failure mode that turns a bounded run into",
        "an unbounded bill.",
        "",
        "### What the campaign puts on the clusters",
        "",
        "Aggregate pod requests across every committed manifest, per cloud:",
        "",
        "| Cloud | Replicas | CPU requested | Memory requested |",
        "| --- | ---: | ---: | ---: |",
        *[f"| {d.cloud} | {d.replicas} | {d.vcpu:,.1f} vCPU | {d.memory_gib:,.2f} GiB |" for d in demand],
        "",
        "Small on purpose -- the fixture is a web app, not a benchmark. The contrast is",
        "the point: a tenant cluster is an hourly floor that dwarfs what the campaign",
        "puts on it, so it costs what it costs whether the grid runs fast or slow.",
        "",
        "These are the manifests' own workload pods only. An in-cluster managed service",
        "places pods of its own, sized by the driver rather than by the manifest, and",
        "not all of them are small. Those show up per booking in the table at the end,",
        "under `Books at`, and are not summed here.",
        "",
    ]


def _floor_section() -> list[str]:
    return [
        "## The floor this ledger does not cover",
        "",
        "Spec 43 §4.2 stands up a control plane on each cloud through the installer",
        "agent and registers a tenant cluster per cloud before the first cell runs. Those",
        "six things bill for the campaign's entire wall-clock, not per cell, and they are",
        "almost certainly the largest line on the bill.",
        "",
        "They are absent here because nothing in this tree describes their shape. The",
        "installer targets live in another repository, and the `compute:node_hour`",
        "estimator that would price a cluster's nodes has no caller in this repository",
        "and no control-plane equivalent at all. Estimating them from this side would be",
        "guessing, so the ledger reports the per-cell exposure it can derive and names",
        "this as the missing term rather than quietly omitting it.",
        "",
        "Practical consequence for the decision: campaign spend is roughly",
        "`(fixed floor per hour) x (wall-clock hours) + (per-cell exposure above)`. The",
        "second term is bounded and reported; the first is unbounded in wall-clock, which",
        "is the argument for spec 43's own instruction to tear down at the end of each",
        "day's run rather than at the end of the campaign.",
        "",
    ]


def _priceability_section() -> list[str]:
    counts = priceability_counts()
    total = sum(counts.values())
    return [
        "## Pricing coverage",
        "",
        "What the existing machinery would return per booking if it were run with",
        "credentials. None of these is a price; they rank what a live run would get back.",
        "",
        "| Verdict | Bookings | Meaning |",
        "| --- | ---: | --- |",
        f"| exact | {counts[Priceability.EXACT]} | a SKU plan resolves one catalog row per billable dimension |",
        f"| approximate | {counts[Priceability.APPROXIMATE]} | the estimator sums whatever its filter"
        " returns; over-counts by construction (#1318) |",
        f"| none | {counts[Priceability.NO_ESTIMATOR]} | the cloud's estimator has no entry for this variant |",
        f"| n/a (in-cluster) | {counts[Priceability.NOT_A_CLOUD_SKU]} | no managed-service SKU exists;"
        " it is cluster capacity |",
        "",
        f"{counts[Priceability.EXACT]} of {total} bookings would come back with a number worth acting on, all of them",
        "Cloud SQL, which is the one variant family `gcp/cost_plans.py` covers. Spec 43",
        "§4.3 says a cell the preview cannot price is a finding rather than a rounding",
        "error; on those terms this table is a list of findings.",
        "",
    ]


def _cell_table() -> list[str]:
    out = [
        "## Every booking",
        "",
        f"One row per managed service the campaign provisions, at `size={CAMPAIGN_SIZE}`. `Books at` is",
        "read from the driver's own size table, so it is what will actually be created.",
        "",
        "| Cell | Cloud | Kind | Variant | Meter | Pricing | Books at `small` |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for cell in all_spend():
        for item in cell.bookings:
            units = ", ".join(f"`{name}` = {value}" for name, value in item.units) or "-"
            in_cluster = " (in-cluster)" if item.plugin_id != item.cloud else ""
            out.append(
                f"| `{cell.identifier}` | {item.cloud} | `{item.kind}` | `{item.variant}`{in_cluster} | "
                f"{_METER_LABEL[item.meter]} | {_PRICEABILITY_LABEL[item.priceability]} | {units} |"
            )
    out.append("")
    return out


def _unclassified_section() -> list[str]:
    unclassified = sorted(
        {(b.cloud, b.kind, b.variant) for b in bookings() if b.meter is Meter.UNKNOWN},
    )
    out = [
        "## Bookings with no billing class",
        "",
        "The blocking list. Each of these raises `UnclassifiedVariant` from",
        "`_cert.billing.check_may_run`, so the campaign refuses to provision it -- by",
        'design, because an unclassified variant must not inherit "runs freely".',
        "Classifying them is an offline table edit and it is the next thing #1417 needs.",
        "",
        "| Cloud | Kind | Variant |",
        "| --- | --- | --- |",
    ]
    out += [f"| {cloud} | `{kind}` | `{variant}` |" for cloud, kind, variant in unclassified]
    out.append("")
    return out


def render() -> str:
    sections = [
        *_header(),
        *_what_a_real_number_needs(),
        *_window_section(),
        *_exposure_section(),
        *_dominant_section(),
        *_stranded_section(),
        *_priceability_section(),
        *_floor_section(),
        *_unclassified_section(),
        *_cell_table(),
    ]
    return "\n".join(sections)


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(OUTPUT.parents[2])}")


if __name__ == "__main__":
    main()
