"""Render docs/managed_service_coverage.md from the availability matrix.

Run via ``make coverage-matrix`` from backend/providers. The rendered table is
committed so the portability answer is reviewable in a diff: a PR that adds a
kind to one cloud shows the new hole next to the code that opened it.

``render()`` is importable so the drift test can compare the committed file
against a fresh render without shelling out.
"""

from __future__ import annotations

from pathlib import Path

from _sdk.coverage import CLOUDS, COLUMNS, IN_CLUSTER, OPT_IN_TIER, KindCoverage, coverage, gaps
from _sdk.coverage_gaps import CLASSIFICATIONS, DECLARED_GAPS

OUTPUT = Path(__file__).resolve().parents[1] / "docs" / "managed_service_coverage.md"

_HEADINGS = {
    "aws": "AWS",
    "gcp": "GCP",
    "azure": "Azure",
    IN_CLUSTER: "In-cluster (k8s_native)",
}

_EMPTY = "-"


def _cell(row: KindCoverage, plugin_id: str) -> str:
    cell = row.cell(plugin_id)
    if cell.executable:
        parts = [f"`{v}`" for v in cell.executable]
        parts += [f"`{v}` (deprecated)" for v in cell.deprecated]
        return ", ".join(parts)
    if cell.planned:
        return ", ".join(f"planned: `{v}`" for v in cell.planned)
    if cell.deprecated:
        return ", ".join(f"`{v}` (deprecated)" for v in cell.deprecated)
    return _EMPTY


def _kind(row: KindCoverage) -> str:
    """Opt-in rows are marked in place: their empty cells are a catalogue
    choice, and unmarked they read as unowned work."""
    return f"`{row.kind}` (opt-in)" if row.kind in OPT_IN_TIER else f"`{row.kind}`"


def render() -> str:
    rows = coverage()
    computed = gaps()
    on_every_cloud = [r for r in rows if r.is_cloud_portable]
    reachable = [r for r in rows if r.is_portable]
    gap_kinds = sorted({kind for kind, _ in computed})
    opt_in = ", ".join(f"`{kind}`" for kind in sorted(OPT_IN_TIER))

    out: list[str] = [
        "# Managed-Service Cross-Cloud Coverage",
        "",
        "Generated by `make coverage-matrix` (backend/providers/scripts/coverage_matrix.py)",
        "from `_sdk/availability.py` -- do not hand-edit.",
        "",
        "Executable means status `ga`, `preview`, or `experimental`: a binding can be",
        "provisioned from it today. `planned` is roadmap metadata and `deprecated` is on",
        "its way out; neither counts as coverage.",
        "",
        "A kind is a portability gap when another cloud already ships it, no in-cluster",
        "variant covers the rest, and the kind is part of the default catalogue. An",
        "in-cluster variant is parity everywhere at once, so a kind that has one is",
        "reachable wherever Astrolift is installed. Opt-in kinds, marked in the table,",
        "are outside the default catalogue: their drivers work, they are just not part",
        "of the guaranteed cross-cloud surface, so their empty cells are not gaps.",
        "Every gap that is left must appear in the ledger below or the guard test",
        "(`tests/_sdk/test_coverage_ledger.py`) fails.",
        "",
        f"Opt-in kinds: {opt_in}.",
        "",
        f"{len(rows)} kinds; {len(on_every_cloud)} executable on all three public clouds;",
        f"{len(reachable)} reachable on every cloud once in-cluster variants count;",
        f"{len(computed)} gaps across {len(gap_kinds)} kinds.",
        "",
        "## Coverage",
        "",
        "| Kind | " + " | ".join(_HEADINGS[c] for c in COLUMNS) + " |",
        "| --- | " + " | ".join("---" for _ in COLUMNS) + " |",
    ]
    for row in rows:
        cells = " | ".join(_cell(row, plugin_id) for plugin_id in COLUMNS)
        out.append(f"| {_kind(row)} | {cells} |")

    out += [
        "",
        "## Declared gaps",
        "",
        "Each row explains one hole above. The reference is the tracking issue.",
        "",
        "| Kind | Cloud | Classification | Reference |",
        "| --- | --- | --- | --- |",
    ]
    for gap in sorted(DECLARED_GAPS, key=lambda g: (g.kind, CLOUDS.index(g.cloud))):
        reference = gap.reference or _EMPTY
        out.append(f"| `{gap.kind}` | {gap.cloud} | `{gap.classification}` | {reference} |")

    out += ["", "### Classifications", ""]
    out += [f"- `{name}` -- {description}" for name, description in CLASSIFICATIONS.items()]
    out.append("")
    return "\n".join(out)


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(OUTPUT.parents[2])}")


if __name__ == "__main__":
    main()
