"""Temporal activities — durable, idempotent units of work.

Each activity is a thin wrapper around a platform model + driver
call. Activities resolve the relevant provider plugin (cluster,
secrets, dns, registry, managed-service) on entry and dispatch
through the canonical ``astrolift_drivers.registry`` interface so
workflow code stays free of Django + driver imports.
"""

from astrolift_workflows.activities.app_deregister import (
    delete_app_source_webhook,
    list_app_secret_targets,
    revoke_app_secret_bundle_refs,
)
from astrolift_workflows.activities.app_lifecycle import (
    apply_manifests,
    create_promotion_deployment,
    create_rollback_deployment,
    delete_preview_namespace,
    health_check,
    mark_app_provisioning,
    mark_app_ready,
    mark_deploying,
    mark_preview_building,
    mark_preview_failed,
    mark_preview_running,
    mark_preview_torn_down,
    mark_running,
    poll_rollout,
    pre_flight,
    provision_managed_services_initial,
    provision_namespace,
    provision_preview_namespace,
    provision_registry_repo,
    render_manifests,
    update_secrets,
    wait_dns,
)
from astrolift_workflows.activities.app_teardown import (
    delete_app_namespaces,
    list_app_managed_service_ids,
    mark_app_deregistered,
    mark_app_tearing_down,
    revoke_app_deploy_tokens,
    soft_delete_app_records,
)
from astrolift_workflows.activities.capability_deprovision import (
    deprovision_app_certificate,
    deprovision_app_dns_record,
    deprovision_app_identity_role,
    deprovision_app_ingress,
    deprovision_app_registry_repo,
)
from astrolift_workflows.activities.cluster_decommission_cleanup import (
    cleanup_cluster_acm_certs,
    cleanup_cluster_dns_records,
    cleanup_cluster_ecr_repos,
    cleanup_cluster_irsa_roles,
)
from astrolift_workflows.activities.cluster_management import (
    apply_platform_rbac,
    ensure_cluster_drained,
    mark_decommissioned,
    mark_decommissioning,
    mark_error,
    mark_managed,
    mark_managing,
    probe_capabilities,
    provision_secrets_backend,
    remove_platform_rbac,
    run_preflight_job,
    teardown_cluster_infra,
    verify_reachability,
)
from astrolift_workflows.activities.cron_deploy import dispatch_cron_deploys
from astrolift_workflows.activities.custom_domain import (
    ensure_platform_managed_records,
    issue_custom_domain_certificate,
    probe_required_records,
    transition_domain_status,
)
from astrolift_workflows.activities.dev_environment import (
    mark_dev_environment_failed,
    provision_dev_environment,
    sync_dev_environment_files,
)
from astrolift_workflows.activities.install_prereqs import (
    install_cluster_prereqs,
    record_cluster_bootstrap_run,
)
from astrolift_workflows.activities.managed_service_lifecycle import (
    deprovision_managed_service,
    finalize_managed_service_deletion,
    mark_managed_service_deprovisioning,
)
from astrolift_workflows.activities.provision_managed_domain import (
    mark_managed_domain_active,
    poll_cert_issuance,
    provision_dns_zone,
    register_managed_domain_row,
    reissue_cert,
    request_wildcard_cert_for_zone,
)
from astrolift_workflows.activities.migration import (
    apply_to_target_cluster,
    drain_source_cluster,
    poll_rollout_on_target,
    switch_app_env_binding,
    validate_migration_target,
)
from astrolift_workflows.activities.scheduled import (
    capture_platform_cost_snapshot,
    detect_drift,
    expire_pending_approval_deployments,
    gc_stale_previews,
    poll_scheduled_job_runs,
    prune_audit_log,
    prune_stale_sessions,
    reconcile_cluster_capabilities,
    reheal_webhook_subscriptions,
)
from astrolift_workflows.activities.secret_rotation import (
    bounce_workloads_consuming_bundle,
    delete_secret_from_cluster,
    list_active_secret_bundle_targets,
    list_bundles_due_for_refresh,
    refresh_secret_bundle_in_cluster,
)

__all__ = [
    "apply_manifests",
    "apply_platform_rbac",
    "apply_to_target_cluster",
    "bounce_workloads_consuming_bundle",
    "capture_platform_cost_snapshot",
    "cleanup_cluster_acm_certs",
    "cleanup_cluster_dns_records",
    "cleanup_cluster_ecr_repos",
    "cleanup_cluster_irsa_roles",
    "create_promotion_deployment",
    "create_rollback_deployment",
    "delete_app_namespaces",
    "delete_app_source_webhook",
    "delete_preview_namespace",
    "delete_secret_from_cluster",
    "deprovision_app_certificate",
    "deprovision_app_dns_record",
    "deprovision_app_identity_role",
    "deprovision_app_ingress",
    "deprovision_app_registry_repo",
    "deprovision_managed_service",
    "detect_drift",
    "dispatch_cron_deploys",
    "drain_source_cluster",
    "ensure_cluster_drained",
    "ensure_platform_managed_records",
    "expire_pending_approval_deployments",
    "finalize_managed_service_deletion",
    "gc_stale_previews",
    "health_check",
    "install_cluster_prereqs",
    "record_cluster_bootstrap_run",
    "issue_custom_domain_certificate",
    "list_active_secret_bundle_targets",
    "list_app_managed_service_ids",
    "list_app_secret_targets",
    "list_bundles_due_for_refresh",
    "mark_app_deregistered",
    "mark_app_provisioning",
    "mark_app_ready",
    "mark_app_tearing_down",
    "mark_decommissioned",
    "mark_decommissioning",
    "mark_deploying",
    "mark_dev_environment_failed",
    "mark_error",
    "mark_managed",
    "mark_managed_domain_active",
    "mark_managed_service_deprovisioning",
    "mark_managing",
    "mark_preview_building",
    "mark_preview_failed",
    "mark_preview_running",
    "mark_preview_torn_down",
    "mark_running",
    "poll_cert_issuance",
    "poll_rollout",
    "poll_rollout_on_target",
    "poll_scheduled_job_runs",
    "pre_flight",
    "probe_capabilities",
    "probe_required_records",
    "provision_dev_environment",
    "provision_dns_zone",
    "provision_managed_services_initial",
    "provision_namespace",
    "provision_preview_namespace",
    "provision_registry_repo",
    "provision_secrets_backend",
    "prune_audit_log",
    "prune_stale_sessions",
    "reconcile_cluster_capabilities",
    "refresh_secret_bundle_in_cluster",
    "register_managed_domain_row",
    "reissue_cert",
    "reheal_webhook_subscriptions",
    "remove_platform_rbac",
    "render_manifests",
    "request_wildcard_cert_for_zone",
    "revoke_app_deploy_tokens",
    "revoke_app_secret_bundle_refs",
    "run_preflight_job",
    "soft_delete_app_records",
    "switch_app_env_binding",
    "sync_dev_environment_files",
    "teardown_cluster_infra",
    "transition_domain_status",
    "update_secrets",
    "validate_migration_target",
    "verify_reachability",
    "wait_dns",
]
