"""Temporal activities — durable, idempotent units of work.

Each activity is a thin wrapper around a platform model + driver
call. Activities resolve the relevant provider plugin (cluster,
secrets, dns, registry, managed-service) on entry and dispatch
through the canonical ``astrolift_drivers.registry`` interface so
workflow code stays free of Django + driver imports.
"""

from astrolift_workflows.activities.agent_box_reap import reap_agent_boxes_tick
from astrolift_workflows.activities.alert_eval import evaluate_alerts_tick
from astrolift_workflows.activities.app_deregister import (
    delete_app_source_webhook,
    list_app_secret_targets,
    revoke_app_secret_bundle_refs,
)
from astrolift_workflows.activities.app_lifecycle import (
    apply_manifests,
    create_promotion_deployment,
    create_rollback_deployment,
    delete_preview_namespace,
    emit_preview_torn_down_event,
    health_check,
    load_preview_teardown_state,
    mark_app_provisioning,
    mark_app_ready,
    mark_deploying,
    mark_failed,
    mark_preview_building,
    mark_preview_failed,
    mark_preview_running,
    mark_preview_torn_down,
    mark_running,
    poll_rollout,
    pre_flight,
    provision_managed_services_initial,
    provision_namespace,
    provision_preview_namespace,
    provision_registry_repo,
    render_manifests,
    resync_manifest_for_deploy,
    update_secrets,
    wait_dns,
)
from astrolift_workflows.activities.app_teardown import (
    abort_in_flight_deploys,
    delete_app_namespaces,
    list_app_managed_service_ids,
    mark_app_deregistered,
    mark_app_tearing_down,
    revoke_app_deploy_tokens,
    soft_delete_app_records,
)
from astrolift_workflows.activities.build_image import (
    build_image,
    fetch_app_build_strategy,
)
from astrolift_workflows.activities.capability_deprovision import (
    deprovision_app_certificate,
    deprovision_app_dns_record,
    deprovision_app_identity_role,
    deprovision_app_ingress,
    deprovision_app_registry_repo,
)
from astrolift_workflows.activities.cert_expiry import check_cert_expiry_tick
from astrolift_workflows.activities.ci_workflow_resync import resync_ci_workflows_tick
from astrolift_workflows.activities.cluster_decommission_cleanup import (
    cleanup_cluster_acm_certs,
    cleanup_cluster_dns_records,
    cleanup_cluster_ecr_repos,
    cleanup_cluster_irsa_roles,
)
from astrolift_workflows.activities.cluster_management import (
    apply_platform_rbac,
    ensure_cluster_drained,
    mark_decommissioned,
    mark_decommissioning,
    mark_error,
    mark_managed,
    mark_managing,
    probe_capabilities,
    provision_secrets_backend,
    remove_platform_rbac,
    run_preflight_job,
    teardown_cluster_infra,
    verify_reachability,
)
from astrolift_workflows.activities.cron_deploy import (
    dispatch_agent_crons,
    dispatch_agent_loops,
    dispatch_cron_deploys,
    dispatch_scale_ticks,
    reconcile_agent_deployments,
)
from astrolift_workflows.activities.custom_domain import (
    ensure_platform_managed_records,
    issue_custom_domain_certificate,
    probe_required_records,
    transition_domain_status,
)
from astrolift_workflows.activities.dev_environment import (
    mark_dev_environment_failed,
    provision_dev_environment,
    sync_dev_environment_files,
)
from astrolift_workflows.activities.faas import (
    ensure_faas_services,
)
from astrolift_workflows.activities.install_prereqs import (
    install_cluster_prereqs,
    record_cluster_bootstrap_run,
)
from astrolift_workflows.activities.managed_service_lifecycle import (
    check_managed_service_ready,
    deprovision_managed_service,
    finalize_managed_service_deletion,
    finalize_managed_service_provision,
    finalize_managed_service_update,
    mark_managed_service_deprovisioning,
    mark_managed_service_failed,
    mark_managed_service_provisioning,
    provision_managed_service,
    update_managed_service,
)
from astrolift_workflows.activities.migration import (
    apply_to_target_cluster,
    drain_source_cluster,
    poll_rollout_on_target,
    switch_app_env_binding,
    validate_migration_target,
)
from astrolift_workflows.activities.pipeline_job_spawn import (
    cancel_pipeline_job,
    mark_job_run_cancelled,
    mark_job_run_failed,
    mark_pipeline_run_failed,
    mark_pipeline_run_running,
    mark_pipeline_run_success,
    poll_pipeline_job,
    spawn_pipeline_job,
)
from astrolift_workflows.activities.provision_managed_domain import (
    mark_managed_domain_active,
    poll_cert_issuance,
    provision_dns_zone,
    register_managed_domain_row,
    reissue_cert,
    request_wildcard_cert_for_zone,
    validate_ns_delegation,
)
from astrolift_workflows.activities.run_status_reconcile import reconcile_runs_tick
from astrolift_workflows.activities.scheduled import (
    capture_platform_cost_snapshot,
    capture_quota_usage_snapshot,
    detect_drift,
    expire_pending_approval_deployments,
    gc_stale_previews,
    poll_scheduled_job_runs,
    prune_audit_log,
    prune_stale_sessions,
    reconcile_cluster_capabilities,
    reheal_webhook_subscriptions,
)
from astrolift_workflows.activities.secret_rotation import (
    bounce_workloads_consuming_bundle,
    delete_secret_from_cluster,
    list_active_secret_bundle_targets,
    list_bundles_due_for_refresh,
    refresh_secret_bundle_in_cluster,
)
from astrolift_workflows.activities.static_site import (
    delete_static_dns_records,
    ensure_cloudfront_cert,
    ensure_static_dns,
    ensure_static_site_services,
    sync_static_assets,
)
from astrolift_workflows.activities.uptime import probe_uptime_tick
from astrolift_workflows.activities.workflow_stage_activities import (
    aggregate_fan_out,
    create_nested_workflow_run,
    create_stage_execution,
    dispatch_agent_for_stage,
    get_workflow_stages,
    load_agent_run_outcome,
    mark_workflow_run,
    poll_agent_run_status,
    record_human_gate_decision,
    record_nested_workflow_start,
    snapshot_checkpoint,
    update_stage_execution,
)
from astrolift_workflows.activities.workload_identity import (
    ensure_workload_identity,
)

__all__ = [
    "abort_in_flight_deploys",
    "aggregate_fan_out",
    "apply_manifests",
    "apply_platform_rbac",
    "apply_to_target_cluster",
    "bounce_workloads_consuming_bundle",
    "build_image",
    "cancel_pipeline_job",
    "capture_platform_cost_snapshot",
    "capture_quota_usage_snapshot",
    "check_cert_expiry_tick",
    "check_managed_service_ready",
    "cleanup_cluster_acm_certs",
    "cleanup_cluster_dns_records",
    "cleanup_cluster_ecr_repos",
    "cleanup_cluster_irsa_roles",
    "create_nested_workflow_run",
    "create_promotion_deployment",
    "create_rollback_deployment",
    "create_stage_execution",
    "delete_app_namespaces",
    "delete_app_source_webhook",
    "delete_preview_namespace",
    "delete_secret_from_cluster",
    "delete_static_dns_records",
    "emit_preview_torn_down_event",
    "deprovision_app_certificate",
    "deprovision_app_dns_record",
    "deprovision_app_identity_role",
    "deprovision_app_ingress",
    "deprovision_app_registry_repo",
    "deprovision_managed_service",
    "detect_drift",
    "dispatch_agent_crons",
    "dispatch_agent_for_stage",
    "dispatch_agent_loops",
    "dispatch_cron_deploys",
    "dispatch_scale_ticks",
    "drain_source_cluster",
    "ensure_cloudfront_cert",
    "ensure_cluster_drained",
    "ensure_faas_services",
    "ensure_platform_managed_records",
    "ensure_static_dns",
    "ensure_static_site_services",
    "ensure_workload_identity",
    "evaluate_alerts_tick",
    "expire_pending_approval_deployments",
    "fetch_app_build_strategy",
    "finalize_managed_service_deletion",
    "finalize_managed_service_provision",
    "finalize_managed_service_update",
    "gc_stale_previews",
    "get_workflow_stages",
    "health_check",
    "install_cluster_prereqs",
    "issue_custom_domain_certificate",
    "list_active_secret_bundle_targets",
    "list_app_managed_service_ids",
    "list_app_secret_targets",
    "list_bundles_due_for_refresh",
    "load_preview_teardown_state",
    "load_agent_run_outcome",
    "mark_app_deregistered",
    "mark_app_provisioning",
    "mark_app_ready",
    "mark_app_tearing_down",
    "mark_decommissioned",
    "mark_decommissioning",
    "mark_deploying",
    "mark_dev_environment_failed",
    "mark_error",
    "mark_failed",
    "mark_job_run_cancelled",
    "mark_job_run_failed",
    "mark_managed",
    "mark_managed_domain_active",
    "mark_managed_service_deprovisioning",
    "mark_managed_service_failed",
    "mark_managed_service_provisioning",
    "mark_managing",
    "mark_pipeline_run_failed",
    "mark_pipeline_run_running",
    "mark_pipeline_run_success",
    "mark_preview_building",
    "mark_preview_failed",
    "mark_preview_running",
    "mark_preview_torn_down",
    "mark_running",
    "mark_workflow_run",
    "poll_agent_run_status",
    "poll_cert_issuance",
    "poll_pipeline_job",
    "poll_rollout",
    "poll_rollout_on_target",
    "poll_scheduled_job_runs",
    "pre_flight",
    "probe_capabilities",
    "probe_required_records",
    "probe_uptime_tick",
    "provision_dev_environment",
    "provision_dns_zone",
    "provision_managed_service",
    "provision_managed_services_initial",
    "provision_namespace",
    "provision_preview_namespace",
    "provision_registry_repo",
    "provision_secrets_backend",
    "prune_audit_log",
    "prune_stale_sessions",
    "reap_agent_boxes_tick",
    "reconcile_agent_deployments",
    "reconcile_cluster_capabilities",
    "reconcile_runs_tick",
    "record_cluster_bootstrap_run",
    "record_human_gate_decision",
    "record_nested_workflow_start",
    "refresh_secret_bundle_in_cluster",
    "register_managed_domain_row",
    "reheal_webhook_subscriptions",
    "reissue_cert",
    "remove_platform_rbac",
    "render_manifests",
    "request_wildcard_cert_for_zone",
    "resync_ci_workflows_tick",
    "resync_manifest_for_deploy",
    "revoke_app_deploy_tokens",
    "revoke_app_secret_bundle_refs",
    "run_preflight_job",
    "snapshot_checkpoint",
    "soft_delete_app_records",
    "spawn_pipeline_job",
    "switch_app_env_binding",
    "sync_dev_environment_files",
    "sync_static_assets",
    "teardown_cluster_infra",
    "transition_domain_status",
    "update_managed_service",
    "update_secrets",
    "update_stage_execution",
    "validate_migration_target",
    "validate_ns_delegation",
    "verify_reachability",
    "wait_dns",
]
