"""Wayfinding index: routes an operator can actually reach (#1101).

The retrieval half of the read-only help bubble. Two jobs, and only one of
them could have been done client-side:

1. **Parse the route dictionary.** `frontend/ROUTES.md` is generated by
   `npm run routes:dict` and CI regenerates and diffs it, so it cannot go
   stale unnoticed. That gate is what makes grounding an assistant in it
   safe -- the epic contains a live example of the alternative, an
   `/administration/cost` deep link to a console deleted in `7134d125`.

2. **Filter by entitlement, server-side.** This is the part that makes the
   feature trustworthy rather than a generic doc search, and the part that
   cannot be bundled: a client-side filter is a suggestion, not a
   guarantee. Pointing someone at a screen they cannot open is worse than
   saying nothing, because they will believe the tool over the 403.

Deliberately no embeddings. 194 routes and a handful of doc pages fit in a
prompt; a vector store here would be infrastructure bought to solve a
retrieval problem this corpus does not have.
"""

from __future__ import annotations

import functools
import pathlib
import re
from dataclasses import dataclass

# A packaged copy of `frontend/ROUTES.md`, shipped inside the backend.
#
# Not read from the frontend package, because it is not there at runtime:
# the backend image contains `backend/` only, so a path reaching up to a
# sibling `frontend/` resolves to nothing in every deployed environment
# while working perfectly on a developer's checkout. That is the worst
# available failure mode -- the assistant would answer "I can't see any
# screens" in production and be flawless locally.
#
# The copy is kept honest by `test_the_packaged_dictionary_matches_the_
# frontend`, which runs wherever the frontend package is present (CI has
# the full checkout) and fails on any divergence. Same shape as the
# existing `npm run routes:dict && git diff --exit-code` gate: a generated
# artifact plus a check that it is current, rather than trust.
ROUTES_MD = pathlib.Path(__file__).resolve().parent.parent / "data" / "routes.md"

FRONTEND_ROUTES_MD = pathlib.Path(__file__).resolve().parents[2].parent / "frontend" / "ROUTES.md"
"""Where the source lives on a full checkout. Used only by the drift test."""

_ROW = re.compile(r"^\|\s*`(?P<route>[^`]+)`\s*\|\s*(?P<kind>[^|]+)\|(?P<rest>.*)$")

# Which module each top-level route segment belongs to, mirroring the
# sidebar's module switcher. A segment absent from this map carries no
# entitlement and is visible to every authenticated viewer -- the dashboard,
# documentation and account pages, matching `PaletteEntry.module`'s
# convention on the frontend.
_SEGMENT_MODULE: dict[str, str] = {
    "apps": "apps",
    "agents": "agents",
    "workflows": "workflows",
    "administration": "admin",
    "clusters": "admin",
    "providers": "admin",
    "billing": "admin",
}


@dataclass(frozen=True, slots=True)
class Route:
    path: str
    kind: str
    nav_home: str
    notes: str
    module: str | None

    @property
    def is_page(self) -> bool:
        """Redirects are not destinations.

        A redirect is a thin alias, so pointing someone at one sends them
        somewhere the answer did not name -- and the dictionary already
        records where it lands.
        """
        return self.kind.strip().startswith("page")


def module_for(route: str) -> str | None:
    segment = route.strip("/").split("/", 1)[0].lower()
    return _SEGMENT_MODULE.get(segment)


@functools.lru_cache(maxsize=1)
def load_routes() -> tuple[Route, ...]:
    """Parse the route dictionary. Cached: the file changes at build time,
    never at request time.

    Returns empty rather than raising when the file is absent -- the
    backend is deployed without the frontend package in some images, and a
    help bubble that 500s is worse than one that reports nothing to find.
    """
    try:
        text = ROUTES_MD.read_text()
    except OSError:
        return ()

    out: list[Route] = []
    for line in text.splitlines():
        match = _ROW.match(line)
        if match is None:
            continue
        route = match.group("route").strip()
        if not route.startswith("/"):
            # The header separator row (`| --- | --- |`) and any prose
            # table that happens to use backticks.
            continue
        rest = [c.strip() for c in match.group("rest").split("|")]
        out.append(
            Route(
                path=route,
                kind=match.group("kind").strip(),
                nav_home=rest[0] if rest else "",
                notes=rest[1] if len(rest) > 1 else "",
                module=module_for(route),
            )
        )
    return tuple(out)


def visible_routes(viewer_modules: dict[str, bool]) -> tuple[Route, ...]:
    """Routes ``viewer_modules`` can reach.

    ``viewer_modules`` maps module key -> can_view, as
    `core.permissions.module_entitlements` computes it. A module absent
    from the map is treated as **not viewable**, which is the safe reading:
    an incomplete manifest must not widen what the assistant offers.

    Routes with no module are always included -- the dashboard,
    documentation and account pages carry no entitlement, matching the
    frontend's own convention.
    """
    out = []
    for route in load_routes():
        if not route.is_page:
            continue
        if route.module is not None and not viewer_modules.get(route.module, False):
            continue
        out.append(route)
    return tuple(out)


def index_for_prompt(routes: tuple[Route, ...], *, limit: int = 200) -> str:
    """The routes as a compact block for a model prompt.

    Truncation is reported in the text rather than silently applied: an
    assistant that has seen 200 of 400 routes and does not say so answers
    "there is no such screen" with unearned confidence.
    """
    lines = [f"{r.path}\t{r.nav_home or 'no nav entry'}\t{r.notes}".rstrip() for r in routes[:limit]]
    if len(routes) > limit:
        lines.append(f"... and {len(routes) - limit} more routes not listed here")
    return "\n".join(lines)
