# Generated by Django 6.0.5 on 2026-05-08 13:31

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrolift_identity', '0003_identityprovider_display_name'),
        ('astrolift_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('github_oauth_app', 'Github Oauth App'), ('github_app_install', 'Github App Install'), ('github_pat', 'Github Pat'), ('gitlab_oauth_app', 'Gitlab Oauth App'), ('gitlab_pat', 'Gitlab Pat'), ('bitbucket_oauth_app', 'Bitbucket Oauth App'), ('bitbucket_pat', 'Bitbucket Pat'), ('gitea_oauth_app', 'Gitea Oauth App'), ('gitea_pat', 'Gitea Pat')], max_length=32)),
                ('display_name', models.CharField(blank=True, default='', help_text='Operator-friendly label shown in the UI.', max_length=200)),
                ('account_login', models.CharField(blank=True, default='', max_length=200)),
                ('installation_id', models.CharField(blank=True, default='', max_length=64)),
                ('api_base_url', models.URLField(blank=True, default='')),
                ('secret_backend_kind', models.CharField(default='local_fernet', max_length=32)),
                ('secret_ciphertext', models.BinaryField(blank=True, default=b'')),
                ('oauth_client_id', models.CharField(blank=True, default='', max_length=256)),
                ('oauth_redirect_uri', models.CharField(blank=True, default='', max_length=512)),
                ('repo_visibility_scopes', models.JSONField(blank=True, default=list)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='astrolift_identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'is_active'], name='astrolift_s_organiz_b6136c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'kind', 'account_login'), name='scm_conn_unique_per_org_kind_login')],
            },
        ),
        migrations.CreateModel(
            name='SshDeployKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('public_key', models.TextField()),
                ('fingerprint_sha256', models.CharField(db_index=True, max_length=128)),
                ('secret_backend_kind', models.CharField(default='local_fernet', max_length=32)),
                ('private_key_ciphertext', models.BinaryField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_deploy_keys', to='astrolift_identity.organization')),
                ('registered_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssh_deploy_keys', to='astrolift_registry.registeredapp')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'registered_app'], name='astrolift_s_organiz_ce3aea_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'fingerprint_sha256'), name='ssh_key_unique_per_org_fingerprint')],
            },
        ),
    ]
