# Generated by Django 6.0.5 on 2026-05-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_scm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconnection',
            name='parent_oauth_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tokens', to='astrolift_scm.sourceconnection'),
        ),
        migrations.AddField(
            model_name='sourceconnection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourceconnection',
            name='kind',
            field=models.CharField(choices=[('github_oauth_app', 'Github Oauth App'), ('github_oauth_user', 'Github Oauth User'), ('github_app_install', 'Github App Install'), ('github_pat', 'Github Pat'), ('gitlab_oauth_app', 'Gitlab Oauth App'), ('gitlab_oauth_user', 'Gitlab Oauth User'), ('gitlab_pat', 'Gitlab Pat'), ('bitbucket_oauth_app', 'Bitbucket Oauth App'), ('bitbucket_oauth_user', 'Bitbucket Oauth User'), ('bitbucket_pat', 'Bitbucket Pat'), ('gitea_oauth_app', 'Gitea Oauth App'), ('gitea_oauth_user', 'Gitea Oauth User'), ('gitea_pat', 'Gitea Pat')], max_length=32),
        ),
    ]
