# Generated by Django 6.0.5 on 2026-05-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_scm', '0002_sourceconnection_parent_oauth_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconnection',
            name='webhook_last_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceconnection',
            name='webhook_secret_backend_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sourceconnection',
            name='webhook_secret_ciphertext',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
