# Generated by Django 6.0.5 on 2026-05-08 17:51

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_lifecycle', '0003_append_only_triggers'),
        ('astrolift_scm', '0003_sourceconnection_webhook_last_received_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('delivery_id', models.CharField(db_index=True, max_length=128)),
                ('host_event', models.CharField(blank=True, default='', max_length=64)),
                ('repo_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('head_sha', models.CharField(blank=True, default='', max_length=128)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='astrolift_scm.sourceconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('triggered_deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_webhook_delivery', to='astrolift_lifecycle.deployment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['connection', '-created_at'], name='wh_delivery_conn_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'delivery_id'), name='webhook_delivery_unique_per_connection')],
            },
        ),
    ]
