# Generated by Django 6.0.5 on 2026-05-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_scm', '0004_webhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconnection',
            name='is_orphaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourceconnection',
            name='orphaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceconnection',
            name='orphaned_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
