# Generated by Django 6.0.5 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_scm', '0005_sourceconnection_is_orphaned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconnection',
            name='oauth_client_secret_backend_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sourceconnection',
            name='oauth_client_secret_ciphertext',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
