# Generated by Django 6.0.5 on 2026-05-14 01:27

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0007_organizationallowlisteddomain'),
        ('astrolift_scm', '0006_sourceconnection_oauth_client_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScmWebhookInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('repo_full_name', models.CharField(max_length=255)),
                ('hook_id', models.CharField(blank=True, default='', max_length=64)),
                ('webhook_url', models.URLField(blank=True, default='', max_length=1024)),
                ('provider_short_circuited', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scm_webhook_installations', to='astrolift_identity.organization')),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_installations', to='astrolift_scm.sourceconnection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'source_connection'], name='astrolift_s_organiz_c3b671_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('source_connection', 'repo_full_name'), name='scm_webhook_install_unique_active')],
            },
        ),
    ]
