# Generated by Django 6.0.5 on 2026-05-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_scm', '0007_scm_webhook_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconnection',
            name='reauth_required',
            field=models.BooleanField(default=False),
        ),
    ]
