# Generated by Django 6.0.5 on 2026-05-07 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrolift_clusters', '0001_initial'),
        ('astrolift_identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manageddomain',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_domains', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='manageddomain',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managedservicecatalogentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='managedservicecatalogentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managedservicecatalogentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerplugin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='providerplugin',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerplugin',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managedservicecatalogentry',
            name='provider_plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to='astrolift_clusters.providerplugin'),
        ),
        migrations.AddField(
            model_name='providerpluginconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='providerpluginconfig',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerpluginconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_plugin_configs', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='providerpluginconfig',
            name='provider_plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='astrolift_clusters.providerplugin'),
        ),
        migrations.AddField(
            model_name='providerpluginconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantcluster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='tenantcluster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantcluster',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_clusters', to='astrolift_identity.organization'),
        ),
        migrations.AddField(
            model_name='tenantcluster',
            name='provider_plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='astrolift_clusters.providerplugin'),
        ),
        migrations.AddField(
            model_name='tenantcluster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='manageddomain',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('zone',), name='managed_domain_zone_unique_active'),
        ),
        migrations.AddConstraint(
            model_name='providerplugin',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='provider_plugin_slug_unique_active'),
        ),
        migrations.AddConstraint(
            model_name='managedservicecatalogentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('provider_plugin', 'kind', 'variant'), name='catalog_entry_unique_active'),
        ),
        migrations.AddConstraint(
            model_name='managedservicecatalogentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default_for_kind', True)), fields=('provider_plugin', 'kind'), name='catalog_entry_one_default_per_kind'),
        ),
        migrations.AddIndex(
            model_name='providerpluginconfig',
            index=models.Index(fields=['organization', 'provider_plugin'], name='ppconfig_org_plugin_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantcluster',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='tenant_cluster_slug_unique_active'),
        ),
    ]
