"""Pipeline artifact store — blob driver resolution and upload/download helpers.

This module bridges the pipeline subsystem to the provider SDK BlobStoreDriver
(#90). It does not own the blob storage implementation; the driver is resolved
from the install's provider plugin registry or, in dev, from the
PIPELINE_ARTIFACT_LOCAL_PATH env var.

Usage
-----
At job completion the runner calls ``upload_artifact``; the download URL for
an artifact is generated by ``presigned_download_url`` from the GraphQL
resolver.

On installs with no blob store configured, ``upload_artifact`` raises
``BlobStoreNotConfiguredError`` so the job is marked FAILURE with a clear
error message (per #90 acceptance criteria) rather than silently discarding
the artifact bytes.

Path layout (all keys are absolute within the configured bucket/prefix):
    astrolift/{env}/{org_id}/pipelines/{pipeline_id}/runs/{run_number}/{job_id}/{artifact_name}

Size limits (#90):
    Per artifact:   500 MB hard limit (enforced here before the upload attempt)
    Per run:        2 GB soft limit   (enforced by the run-completion handler in
                                       the Temporal workflow; not enforced here)
"""

from __future__ import annotations

import logging
import os

from providers._sdk.blob_store import (
    BlobInfo,
    BlobStoreDriver,
    BlobStoreNotConfiguredError,
    BlobStoreSizeError,
    LocalFsBlobStoreDriver,
    artifact_blob_key,
    run_blob_prefix,
)

logger = logging.getLogger("astrolift.pipelines.artifact_store")

# 500 MB per-artifact hard limit (bytes). Callers supply the size before the
# upload attempt so the spawner can fail the job early without streaming data.
PER_ARTIFACT_SIZE_LIMIT = 500 * 1024 * 1024


def _get_blob_driver(org: object) -> BlobStoreDriver:
    """Return the BlobStoreDriver for ``org``'s install, or raise.

    Resolution order:
    1. The install's configured Django S3 bucket. AWS installs already use
       this bucket for platform-owned media and run with a task role, so it
       is also the right home for platform-owned artifacts and agent
       payloads. ``AWS_S3_ENDPOINT_URL`` is honoured, so this reaches MinIO,
       SeaweedFS, Ceph RGW and GCS's S3-compatible API as well.
    2. PIPELINE_ARTIFACT_LOCAL_PATH env var — returns LocalFsBlobStoreDriver.
       Only active in local dev and CI.
    3. Raises BlobStoreNotConfiguredError.

    A per-org provider-plugin step stood ahead of these and was never
    reachable; see ``core.blob_store_resolution`` and #1610.

    ``org`` is the Django Organization model instance (not imported here so
    the providers tree remains import-isolated from the Django ORM).
    """
    # Step 1 — the install's platform-owned S3 bucket. What stood ahead of
    # this was a lookup of `astrolift_drivers.registry.get_driver_for_org`,
    # which is defined nowhere, guarded by an `except ImportError` whose
    # comment claimed the module was "not yet wired". The module is wired;
    # only the name was missing, so the per-org branch was never taken
    # (#1610).
    from core.blob_store_resolution import driver_for_org

    driver = driver_for_org(org, purpose="pipeline artifact store")
    if driver is not None:
        return driver

    # Step 2 — local filesystem fallback.
    local_path = os.environ.get("PIPELINE_ARTIFACT_LOCAL_PATH", "")
    if local_path:
        logger.debug("Using LocalFsBlobStoreDriver at %s", local_path)
        return LocalFsBlobStoreDriver(base_path=local_path)

    # Step 3 — no driver available.
    raise BlobStoreNotConfiguredError(
        "No blob store is configured for this install. "
        "Configure the install storage bucket or a blob_store provider driver, "
        "or set PIPELINE_ARTIFACT_LOCAL_PATH for local development."
    )


def upload_artifact(
    *,
    org: object,
    env: str,
    pipeline_id: str,
    run_number: int,
    job_id: str,
    artifact_name: str,
    data: bytes,
    content_type: str = "application/octet-stream",
) -> str:
    """Upload artifact bytes and return the canonical blob key.

    Enforces the 500 MB per-artifact hard limit; raises ``BlobStoreSizeError``
    before attempting the upload when exceeded.

    Raises:
        BlobStoreNotConfiguredError — no driver available for this install.
        BlobStoreSizeError — data exceeds PER_ARTIFACT_SIZE_LIMIT.
    """
    actual = len(data)
    if actual > PER_ARTIFACT_SIZE_LIMIT:
        key = artifact_blob_key(
            env=env,
            org_id=str(getattr(org, "id", "unknown")),
            pipeline_id=pipeline_id,
            run_number=run_number,
            job_id=job_id,
            artifact_name=artifact_name,
        )
        raise BlobStoreSizeError(
            key=key,
            limit_bytes=PER_ARTIFACT_SIZE_LIMIT,
            actual_bytes=actual,
        )

    org_id = str(getattr(org, "id", "unknown"))
    key = artifact_blob_key(
        env=env,
        org_id=org_id,
        pipeline_id=pipeline_id,
        run_number=run_number,
        job_id=job_id,
        artifact_name=artifact_name,
    )
    driver = _get_blob_driver(org)
    driver.upload(key, data, content_type=content_type)
    logger.info(
        "artifact uploaded",
        extra={
            "org_id": org_id,
            "pipeline_id": pipeline_id,
            "run_number": run_number,
            "job_id": job_id,
            "artifact_name": artifact_name,
            "size_bytes": actual,
            "key": key,
        },
    )
    return key


def presigned_download_url(
    *,
    org: object,
    blob_key: str,
    expires_in: int = 900,
) -> str:
    """Return a presigned read-only URL for the artifact blob at ``blob_key``.

    TTL defaults to 15 minutes (900 s) per the issue spec. Audit logging of
    the ``artifact.downloaded`` event is the caller's responsibility (the
    GraphQL resolver calls this and owns the audit emit).

    Raises:
        BlobStoreNotConfiguredError — no driver available.
        BlobStoreNotFoundError — blob_key does not exist.
    """
    driver = _get_blob_driver(org)
    return driver.presigned_url(blob_key, expires_in=expires_in)


def delete_run_artifacts(
    *,
    org: object,
    env: str,
    pipeline_id: str,
    run_number: int,
) -> int:
    """Delete all artifact blobs for a pipeline run. Returns the count deleted.

    Called when a PipelineRun is hard-deleted (#90). Deletion is idempotent —
    missing blobs are silently skipped. Returns the number of blobs deleted.

    Raises:
        BlobStoreNotConfiguredError — no driver available.
    """
    org_id = str(getattr(org, "id", "unknown"))
    prefix = run_blob_prefix(
        env=env,
        org_id=org_id,
        pipeline_id=pipeline_id,
        run_number=run_number,
    )
    driver = _get_blob_driver(org)
    blobs: list[BlobInfo] = driver.list_keys(prefix)
    for blob in blobs:
        driver.delete(blob.key)
    logger.info(
        "run artifacts deleted",
        extra={
            "org_id": org_id,
            "pipeline_id": pipeline_id,
            "run_number": run_number,
            "count": len(blobs),
        },
    )
    return len(blobs)


def list_run_artifacts(
    *,
    org: object,
    env: str,
    pipeline_id: str,
    run_number: int,
) -> list[BlobInfo]:
    """List artifact blobs for a pipeline run.

    Returns an empty list when no artifacts exist or the driver is not
    configured. Callers should handle BlobStoreNotConfiguredError explicitly
    if they need to distinguish "not configured" from "no artifacts".
    """
    org_id = str(getattr(org, "id", "unknown"))
    prefix = run_blob_prefix(
        env=env,
        org_id=org_id,
        pipeline_id=pipeline_id,
        run_number=run_number,
    )
    driver = _get_blob_driver(org)
    return driver.list_keys(prefix)
