# Generated by Django 6.0.5 on 2026-05-07 14:45

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrolift_clusters', '0002_initial'),
        ('astrolift_identity', '0001_initial'),
        ('astrolift_lifecycle', '0001_initial'),
        ('astrolift_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_kind', models.CharField(max_length=32)),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor_display', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=8)),
                ('target_kind', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_slug', models.CharField(blank=True, default='', max_length=255)),
                ('target_parent_chain', models.JSONField(blank=True, default=list)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('request_ip', models.CharField(blank=True, default='', max_length=64)),
                ('request_user_agent', models.TextField(blank=True, default='')),
                ('request_session_age_seconds', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('reasoning', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='astrolift_identity.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-occurred_at', 'action'], name='audit_org_time_action_idx'), models.Index(fields=['actor_kind', 'actor_id'], name='audit_actor_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='astrolift_identity.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='astrolift_identity.project')),
                ('registered_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='astrolift_registry.registeredapp')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='astrolift_identity.team')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-occurred_at', 'event_type'], name='event_org_time_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('deploy_pending_approval', 'Deploy Pending Approval'), ('deploy_failed', 'Deploy Failed'), ('invitation', 'Invitation'), ('quota_warning', 'Quota Warning'), ('webhook_delivery_failed', 'Webhook Delivery Failed'), ('system', 'System')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=512)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astrolift_notifications', to='astrolift_identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astrolift_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'read_at'], name='notif_user_unread_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('url', models.URLField()),
                ('secret_hash', models.CharField(max_length=128)),
                ('events', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_status', models.IntegerField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='astrolift_identity.organization')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_subscriptions', to='astrolift_identity.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'is_active'], name='webhook_org_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('workflow_kind', models.CharField(db_index=True, max_length=128)),
                ('workflow_id', models.CharField(max_length=255)),
                ('run_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('timed_out', 'Timed Out')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_actor_token_kind', models.CharField(blank=True, default='', max_length=32)),
                ('trigger_actor_token_id', models.BigIntegerField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('failure', models.JSONField(blank=True, null=True)),
                ('app_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='astrolift_lifecycle.appenvironment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='astrolift_identity.organization')),
                ('registered_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='astrolift_registry.registeredapp')),
                ('trigger_actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_workflow_runs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-started_at'], name='wfr_org_started_idx')],
                'constraints': [models.UniqueConstraint(fields=('workflow_id', 'run_id'), name='workflowrun_id_unique')],
            },
        ),
        migrations.CreateModel(
            name='WorkloadIdentityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('role_arn', models.CharField(max_length=512)),
                ('service_account', models.CharField(max_length=255)),
                ('namespace', models.CharField(max_length=128)),
                ('issuer_url', models.URLField(blank=True, default='')),
                ('audience', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registered_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_identity_roles', to='astrolift_registry.registeredapp')),
                ('tenant_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_identity_roles', to='astrolift_clusters.tenantcluster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('registered_app', 'tenant_cluster', 'service_account', 'namespace'), name='wir_unique_active_per_app_cluster_sa_ns')],
            },
        ),
    ]
