# Generated by Django 6.0.5 on 2026-05-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_operations', '0003_append_only_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksubscription',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='disabled_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
