# Generated by Django 6.0.5 on 2026-05-09 22:02

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0006_organization_obs_retention'),
        ('astrolift_operations', '0005_webhooksubscription_registered_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('target', models.CharField(choices=[('app', 'App'), ('env', 'Env'), ('workload', 'Workload'), ('global', 'Global')], default='app', max_length=16)),
                ('target_id', models.CharField(blank=True, default='', help_text='Slug or guid of the target object. Empty when target=global.', max_length=128)),
                ('predicate', models.JSONField(blank=True, default=dict, help_text="Free-form predicate definition. Today carries a 'metric' / 'comparator' / 'threshold' / 'duration' shape that the evaluator translates to PromQL; the JSON shape lets future predicates land without a schema migration.")),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('critical', 'Critical')], default='warn', max_length=16)),
                ('notify_channels', models.JSONField(blank=True, default=list, help_text="List of {kind: 'slack'|'email'|'webhook', ref: ...} entries. Routing fan-out reads this at fire time.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='astrolift_identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('fired_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('critical', 'Critical')], default='warn', max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alert_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='astrolift_identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='astrolift_operations.alertrule')),
            ],
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'is_active'], name='alert_rule_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['target', 'target_id'], name='alert_rule_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'name'), name='alert_rule_name_unique_active_per_org'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['rule', '-fired_at'], name='alert_event_rule_fired_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['organization', '-fired_at'], name='alert_event_org_fired_idx'),
        ),
    ]
