# Generated by Django 6.0.5 on 2026-05-17 21:36
#
# Originally shipped #490's per-cloud NotificationDriver SDK with
# CreateModel for DeviceRegistration / NotificationDelivery /
# NotificationProfile. #476/#499 landed in parallel and also created
# DeviceRegistration (with a slightly different shape) in
# 0011_device_registration_and_preference. #519 reconciles both.
#
# The reconciled layout:
#
# * 0011_device_registration_and_preference is the canonical source
#   for DeviceRegistration + NotificationPreference. Its shape is
#   what the live models in ``models/device_registration.py`` +
#   ``models/notification_preference.py`` describe (device_token=512,
#   web_push platform choice, enrolled_session FK, stale_at, driver
#   slug column).
# * This migration (0010) now only creates NotificationDelivery +
#   NotificationProfile -- the two models that the parallel #490
#   work contributed. It depends on 0011 so the DeviceRegistration
#   FK target exists at apply time.
#
# The migration filename + position number are preserved so that
# any environment that has already applied an earlier copy of this
# file keeps the migration recorded in django_migrations; the
# operations were narrowed to a subset that's idempotent against
# fresh databases (NotificationDelivery + NotificationProfile didn't
# exist in #476/#499's path).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_identity", "0011_merge_20260517_1933"),
        ("astrolift_operations", "0011_device_registration_and_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True
                    ),
                ),
                ("event_type", models.CharField(blank=True, default="", max_length=128)),
                ("driver_name", models.CharField(db_index=True, max_length=32)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("push", "Push notification"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("webhook", "Webhook"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("target_address", models.CharField(blank=True, default="", max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("delivered", "Delivered"),
                            ("queued", "Queued (async)"),
                            ("failed", "Failed"),
                            ("unsupported", "Unsupported channel"),
                            ("rate_limited", "Rate limited"),
                            ("invalid_token", "Invalid device token"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, default="", max_length=255)),
                ("error", models.TextField(blank=True, default="")),
                ("retriable", models.BooleanField(default=False)),
                ("payload_excerpt", models.CharField(blank=True, default="", max_length=512)),
                ("delivered_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="astrolift_operations.deviceregistration",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="astrolift_notification_deliveries",
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="astrolift_notification_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True
                    ),
                ),
                ("driver", models.CharField(max_length=32)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("retention_delivery_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="astrolift_notification_profiles",
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["organization", "-delivered_at"], name="delivery_org_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["user", "-delivered_at"], name="delivery_user_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationprofile",
            index=models.Index(fields=["organization", "is_active"], name="notif_profile_org_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                fields=("organization",),
                name="notification_profile_one_active_per_org",
            ),
        ),
    ]
