# Generated by Django 6.0.5 on 2026-05-31 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_operations', '0016_workflowrun_current_stage_execution'),
        ('workflows', '0002_workflow_patterns_and_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogexport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditexport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='current_stage_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowstageexecution'),
        ),
    ]
