# Generated by Django 6.0.5 on 2026-08-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_operations', '0020_workflowrun_nested_lineage'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksubscription',
            name='consecutive_failed_reheals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='last_reheal_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
