# Generated by Django 6.0.5 on 2026-08-23 21:46

import core.fields.uuid_v7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0029_organization_audit_export_enabled'),
        ('astrolift_operations', '0021_webhooksubscription_consecutive_failed_reheals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('object_key', models.CharField(max_length=1024)),
                ('row_count', models.IntegerField(default=0)),
                ('byte_count', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('covered_through', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_archives', to='astrolift_identity.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='astrolift_o_organiz_c8a5fb_idx')],
            },
        ),
    ]
