"""The hold table `is_held` never had (#1602 step 2).

`observability_retention.is_held()` takes a sequence of holds and applies
the match rules. Nothing ever built that sequence -- no table, no query, no
row -- so the hold half of the policy was correct logic with no input.

Landing before the eviction driver deliberately. Holds are how an operator
says "an incident is live, do not delete this window yet"; shipping
eviction first would mean the first activation deletes data an incident is
actively depending on, with nothing available to stop it.

Purely additive: one new table, nothing touched on any existing one.
"""

# Generated by Django 6.0.5 on 2026-08-25 19:48

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0030_organization_image_signing_policy'),
        ('astrolift_operations', '0023_retention_sweep_gate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservabilityRetentionHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('stream', models.CharField(choices=[('log', 'Log'), ('metric_raw', 'Metric Raw'), ('metric_rollup', 'Metric Rollup'), ('trace', 'Trace'), ('*', 'Any')], default='*', help_text="Which stream this holds, or '*' for all of them.", max_length=16)),
                ('starts_at', models.DateTimeField(help_text='Start of the held window, inclusive.')),
                ('ends_at', models.DateTimeField(help_text='End of the held window, inclusive. A hold does not auto-expire the way an AlertMute TTL does -- it bounds a window of *data*, not a window of time in which the hold applies, so a hold over last Tuesday stays relevant indefinitely.')),
                ('resource_kind', models.CharField(blank=True, default='', help_text="Scopes the hold, e.g. 'App'. Empty means any.", max_length=64)),
                ('resource_id', models.CharField(blank=True, default='', help_text='Scopes the hold with resource_kind. Empty means any.', max_length=64)),
                ('reason', models.TextField(blank=True, default='', help_text='Why the window is held. Blank-tolerant on the column and required by the mutation, matching AlertMute: a hold nobody can explain is a hold nobody will dare release.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observability_retention_holds', to='astrolift_identity.organization')),
                ('placed_by', models.ForeignKey(blank=True, help_text="Who placed it. Distinct from BaseCoreModel.created_by, which tracks the row writer; this is semantically the hold's owner.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observability_retention_holds_placed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'ends_at'], name='obs_ret_hold_org_ends_idx')],
            },
        ),
    ]
