# Generated by Django 6.0.5 on 2026-09-23 15:23

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_clusters', '0016_node_archs_list'),
        ('astrolift_identity', '0033_resync_system_roles_zentinelle'),
        ('astrolift_operations', '0024_observabilityretentionhold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZentinelleConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('revoked', 'Revoked'), ('disconnected', 'Disconnected')], default='connected', max_length=16)),
                ('zentinelle_install_id', models.CharField(blank=True, default='', help_text="Zentinelle's id for this install (AstroliftInstall).", max_length=64)),
                ('tenant_ids', models.JSONField(blank=True, default=list, help_text='Zentinelle tenants the enrollment code scoped this install to.')),
                ('credential_backend_kind', models.CharField(default='local_fernet', max_length=32)),
                ('credential_ciphertext', models.BinaryField(blank=True, default=b'')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zentinelle_connections', to='astrolift_identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZentinelleClusterGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('zentinelle_cluster_id', models.CharField(help_text="The id Zentinelle knows the cluster by: the TenantCluster guid, also the gateway's ZENTINELLE_CLUSTER_ID.", max_length=128)),
                ('gateway_name', models.CharField(blank=True, default='', max_length=255)),
                ('gateway_enabled', models.BooleanField(default=True, help_text="Whether this cluster's gateway should run. Deployed only while ZENTINELLE_GATEWAY_ENABLED is on.")),
                ('gateway_deployed', models.BooleanField(default=False, help_text='Whether the gateway Deployment and Service were applied and not removed since.')),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('credential_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='', help_text='Why the last operation on this cluster failed; empty after one succeeds.')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zentinelle_gateways', to='astrolift_clusters.tenantcluster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_gateways', to='astrolift_operations.zentinelleconnection')),
            ],
        ),
        migrations.AddConstraint(
            model_name='zentinelleconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization',), name='zentinelle_connection_one_live_per_org'),
        ),
        migrations.AddConstraint(
            model_name='zentinelleclustergateway',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cluster',), name='zentinelle_gateway_one_live_per_cluster'),
        ),
    ]
