# Generated by Django 6.0.5 on 2026-09-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_operations", "0026_workflowrun_trigger_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="temporal_history_expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("terminated", "Terminated"),
                    ("timed_out", "Timed Out"),
                    ("expired", "History expired"),
                ],
                default="running",
                max_length=16,
            ),
        ),
    ]
