# Generated by Django 6.0.5 on 2026-10-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_operations", "0028_user_privacy_projection"),
    ]

    operations = [
        migrations.AddField(
            model_name="applogexport",
            name="source_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
