# Generated by Django 6.0.5 on 2026-10-05 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def refuse_retained_history(apps, schema_editor):
    history = apps.get_model("astrolift_operations", "InstallAlertMailTest")
    if history._base_manager.using(schema_editor.connection.alias).exists():
        raise RuntimeError("Retained install alert mail history prevents rollback.")


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_identity", "0041_merge_agent_enforcement_scim_groups"),
        ("astrolift_operations", "0029_preview_log_export_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallAlertMailTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("event_kind", models.CharField(max_length=64)),
                ("source_sha256", models.CharField(max_length=64)),
                ("sender", models.EmailField(max_length=254)),
                ("recipient", models.EmailField(max_length=254)),
                ("status", models.CharField(default="reserved", max_length=16)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "requester", "created_at"],
                        name="alert_mail_org_actor_time",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "request_id"),
                        name="alert_mail_org_request_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["reserved", "sent", "accepted", "failed", "unknown"],
                            )
                        ),
                        name="alert_mail_status_known",
                    ),
                ],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_retained_history),
    ]
