# Generated by Django 6.0.5 on 2026-05-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0002_system_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
