# Generated by Django 6.0.5 on 2026-05-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0004_resync_system_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_user_profile_edit',
            field=models.BooleanField(default=True),
        ),
    ]
