# Generated by Django 6.0.5 on 2026-05-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0010_identityprovider_activation_audit'),
        ('astrolift_identity', '0010_organization_onboarding_completed_at'),
        ('astrolift_identity', '0010_resync_system_roles_forms'),
    ]

    operations = [
    ]
