# Generated by Django 6.0.5 on 2026-08-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0024_organization_default_resource_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pipeline_definition_mode',
            field=models.CharField(choices=[('snapshot', 'Snapshot per run'), ('shared', 'Shared across runs')], default='snapshot', max_length=16),
        ),
    ]
