# Generated by Django 6.0.5 on 2026-08-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0025_organization_pipeline_definition_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='residency_allowed_regions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
