# Generated by Django 6.0.5 on 2026-08-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0026_organization_appearance_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='managed_service_isolation_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
