# Generated by Django 6.0.5 on 2026-08-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0028_organization_residency_allowed_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='audit_export_enabled',
            field=models.BooleanField(default=False, help_text="Write audit events past this org's retention window to the install's blob store as hash-chained JSONL. Does not delete anything: the append-only trigger still refuses DELETE (see #1594)."),
        ),
    ]
