# Generated by Django 6.0.5 on 2026-08-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0029_organization_audit_export_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image_signing_policy',
            field=models.JSONField(blank=True, default=dict, help_text='Image signature verification. Empty or {"enforcement": "disabled"} verifies nothing. \'optional\' warns on unsigned or unrecognised signers; \'required\' blocks. Needs at least one allowed signer to be anything but disabled.'),
        ),
    ]
