# Generated by Django 6.0.5 on 2026-09-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_identity", "0034_resync_system_roles_stock_catalogue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmodule",
            name="key",
            field=models.CharField(
                choices=[
                    ("chat_studio_integration", "Chat Studio Integration"),
                    ("agent_live_attach", "Agent Live Attach"),
                    ("chat_studio_agent_runs", "Chat Studio Agent Runs"),
                ],
                max_length=64,
            ),
        ),
    ]
