# Generated by Django 6.0.5 on 2026-09-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_identity", "0037_member_idp_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="restricted_settings_default",
            field=models.CharField(
                choices=[("show", "Show read-only"), ("hide", "Hide")], default="show", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="app_view",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="appearance",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The person's own partial appearance, validated by core.appearance.",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="fleet_view",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="flow_particles",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="home_layout",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Home layout key (spec 44 §4.3). Empty means the default from access.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="home_layout_asked",
            field=models.BooleanField(
                default=False,
                help_text="The first-sign-in layout question was answered, so it is not asked again.",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="motion",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="restricted_settings",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Settings the person cannot change: show or hide. Empty follows the org default.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="workflow_view",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
