# Generated by Django 6.0.5 on 2026-09-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_identity", "0039_role_duplicated_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmodule",
            name="key",
            field=models.CharField(
                choices=[
                    ("chat_studio_integration", "Chat Studio Integration"),
                    ("agent_live_attach", "Agent Live Attach"),
                    ("agent_policy_enforcement", "Agent Policy Enforcement"),
                    ("chat_studio_agent_runs", "Chat Studio Agent Runs"),
                ],
                max_length=64,
            ),
        ),
    ]
