# Generated by Django 6.0.5 on 2026-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_services', '0008_email_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsecretmetadata',
            name='environment_name',
            field=models.CharField(blank=True, default='', help_text="Environment scope for the metadata row. Empty string means 'applies to every environment that surfaces this key' — used when the operator sets metadata before any per-env override has been authored.", max_length=64),
        ),
        migrations.AlterField(
            model_name='appsecretmetadata',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Operator-declared rotation deadline. Null means 'no declared expiry' — most app-level literals are evergreen. When this field is within 14 days the FE renders a 'rotate now' badge.", null=True),
        ),
        migrations.AlterField(
            model_name='appsecretmetadata',
            name='scope',
            field=models.CharField(default='all', help_text="Audience scope for this secret row. 'all' = every environment (default); 'production' = non-preview envs only; 'preview' = any active preview env; 'preview:<branch>' = one specific preview branch. Resolution-time filtering drops rows whose scope doesn't match the env being queried.", max_length=48),
        ),
        migrations.AlterField(
            model_name='appsecretmetadata',
            name='set_at',
            field=models.DateTimeField(blank=True, help_text="Last time the metadata row was authored / refreshed. Distinct from the underlying secret's audit-log set timestamp — this tracks metadata edits, not value writes.", null=True),
        ),
        migrations.AlterField(
            model_name='appsecretmetadata',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('cli', 'Cli'), ('env_paste', 'Env Paste'), ('bundle', 'Bundle'), ('managed_service', 'Managed Service')], default='web', help_text="Where the most-recent write originated. 'web' is the default for rows created via the GraphQL set/rotate mutation; CLI / .env paste / bundle / managed-service writers populate the other values when they call setAppSecretMetadata explicitly.", max_length=24),
        ),
    ]
