# Generated by Django 6.0.5 on 2026-08-18 23:33

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_lifecycle", "0029_previewenvironment_pin"),
        ("astrolift_services", "0019_managedservice_update_operation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkloadIdentityGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("provider_plugin_slug", models.CharField(max_length=64)),
                (
                    "identity_role_name",
                    models.CharField(
                        help_text="Identity the assignment binds (the UAMI / IAM role name).",
                        max_length=128,
                    ),
                ),
                ("role_definition_id", models.CharField(max_length=128)),
                ("role_name", models.CharField(blank=True, default="", max_length=128)),
                ("scope", models.TextField()),
                (
                    "assignment_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider-side name of the assignment; deterministic, so an operator can find the exact object in the portal. Empty when the attempt never got far enough to derive one.",
                        max_length=128,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why the grant is not applied. Empty once it is.",
                    ),
                ),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "app_environment",
                    models.ForeignKey(
                        help_text="The environment whose workload identity carries the assignment. A project-owned service attached to several environments is granted once per identity, and each can be in a different state.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_identity_grants",
                        to="astrolift_lifecycle.appenvironment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "managed_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_identity_grants",
                        to="astrolift_services.managedservice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["app_environment", "state"],
                        name="wi_grant_env_state_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=(
                            "managed_service",
                            "app_environment",
                            "role_definition_id",
                            "scope",
                        ),
                        name="wi_grant_unique_active_per_binding_scope",
                    )
                ],
            },
        ),
    ]
