# Generated by Django 6.0.5 on 2026-08-18 23:37

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_identity', '0023_resync_system_roles_managed_service_adopt'),
        ('astrolift_services', '0019_managedservice_update_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedResourceAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('guid', core.fields.uuid_v7.UUIDv7Field(db_index=True, default=core.fields.uuid_v7.uuid7, editable=False, unique=True)),
                ('actor_display', models.CharField(blank=True, default='', max_length=254)),
                ('cloud', models.CharField(default='azure', max_length=32)),
                ('resource_id', models.TextField()),
                ('surface', models.CharField(blank=True, default='', max_length=64)),
                ('classification', models.CharField(choices=[('unmanaged', 'No Astrolift marker'), ('unstamped', 'Platform-created, no managed-service id'), ('foreign_owner', 'Belonged to another managed service'), ('already_owned', 'Already carried this identity')], max_length=32)),
                ('prior_markers', models.JSONField(blank=True, default=dict)),
                ('prior_managed_by', models.CharField(blank=True, default='', max_length=128)),
                ('prior_managed_service_id', models.CharField(blank=True, default='', max_length=128)),
                ('prior_binding_id', models.CharField(blank=True, default='', max_length=128)),
                ('acknowledged_prior_owner', models.CharField(blank=True, default='', max_length=128)),
                ('reason', models.TextField()),
                ('stamped_markers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('adopted', 'Adopted'), ('refused', 'Refused'), ('failed', 'Failed')], default='adopted', max_length=32)),
                ('error', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_resource_adoptions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('managed_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_adoptions', to='astrolift_services.managedservice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_resource_adoptions', to='astrolift_identity.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-created_at'], name='astrolift_s_organiz_992b79_idx'), models.Index(fields=['prior_managed_service_id'], name='astrolift_s_prior_m_47a867_idx')],
            },
        ),
    ]
