# Generated by Django 6.0.5 on 2026-08-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_services', '0021_merge_0020_adoption_0020_workload_identity_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedservice',
            name='isolation',
            field=models.CharField(blank=True, choices=[('shared', 'shared'), ('dedicated', 'dedicated')], default='', max_length=16),
        ),
    ]
