# Generated by Django 6.0.5 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_services", "0022_managedservice_isolation"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedservice",
            name="manifest_managed",
            field=models.BooleanField(
                default=False,
                help_text="True when astrolift.toml, rather than an imperative mutation, owns this row.",
            ),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="bind_workloads",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Manifest workload selectors; ['*'] exposes the binding to every workload.",
            ),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="deletion_policy",
            field=models.CharField(
                choices=[("retain", "retain"), ("delete", "delete")],
                default="retain",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="lifecycle_policy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Typed manifest retention, backup, and restore intent plus explicit delete confirmation.",
            ),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="manifest_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="workload_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Manifest workload selectors for this consumer; ['*'] means every workload.",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="managedservice",
            name="msvc_unique_active_per_app_kind_name",
        ),
        migrations.AddConstraint(
            model_name="managedservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(registered_app__isnull=False, deleted_at__isnull=True),
                fields=("registered_app", "app_environment", "kind", "name"),
                name="msvc_unique_active_per_app_env_kind_name",
            ),
        ),
    ]
