# Generated by Django 6.0.5 on 2026-09-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_services', '0024_attachment_slice_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretchangeproposal',
            name='op',
            field=models.CharField(choices=[('set', 'Set'), ('delete', 'Delete'), ('attach_bundle', 'Attach Bundle'), ('detach_bundle', 'Detach Bundle'), ('set_metadata', 'Set Metadata')], max_length=32),
        ),
    ]
