# Generated by Django 6.0.5 on 2026-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolift_services', '0025_alter_secretchangeproposal_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsecretmetadata',
            name='scope',
            field=models.CharField(blank=True, default='all', help_text="Audience scope for this secret row. 'all' = every environment (default); 'production' = non-preview envs only; 'preview' = any active preview env; 'preview:<branch>' = one specific preview branch. Resolution-time filtering drops rows whose scope doesn't match the env being queried. Null on a per-environment row: the row follows the key's app-wide scope.", max_length=48, null=True),
        ),
    ]
