# Generated by Django 6.0.5 on 2026-09-30 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_agents", "0044_merge_managed_runtime_and_main"),
        ("astrolift_clusters", "0020_tenantcluster_edge_access_rules"),
        ("astrolift_identity", "0041_merge_agent_enforcement_scim_groups"),
        ("astrolift_lifecycle", "0045_deployment_run_history"),
        ("astrolift_registry", "0042_registeredapp_edge_access"),
        ("astrolift_services", "0027_appsecretmetadata_follow_matching_app_wide_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="managedservice",
            name="msvc_exactly_one_owner_scope",
        ),
        migrations.RemoveConstraint(
            model_name="managedserviceattachment",
            name="msvc_attachment_unique_app_env",
        ),
        migrations.AddField(
            model_name="managedservice",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Explicit tenant owner only for a cluster-owned vLLM model.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cluster_model_deployments",
                to="astrolift_identity.organization",
            ),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="subscription_revision",
            field=models.PositiveBigIntegerField(default=0, db_default=0),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="applied_revision",
            field=models.PositiveBigIntegerField(default=0, db_default=0),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="binding_alias",
            field=models.CharField(blank=True, default="", db_default="", max_length=32),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="credential_ref",
            field=models.CharField(blank=True, default="", db_default="", max_length=512),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="desired_enabled",
            field=models.BooleanField(default=True, db_default=True),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="desired_revision",
            field=models.PositiveBigIntegerField(default=0, db_default=0),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="model_subscription",
            field=models.BooleanField(default=False, db_default=False),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="reconcile_error",
            field=models.CharField(blank=True, default="", db_default="", max_length=256),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="reconcile_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedserviceattachment",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("active", "active"),
                    ("revoking", "revoking"),
                    ("revoked", "revoked"),
                    ("failed", "failed"),
                ],
                default="active",
                db_default="active",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="managedservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("app_environment__isnull", False),
                        ("organization__isnull", True),
                        ("project__isnull", True),
                        ("registered_app__isnull", False),
                        ("tenant_cluster__isnull", True),
                    ),
                    models.Q(
                        ("app_environment__isnull", True),
                        ("organization__isnull", True),
                        ("project__isnull", False),
                        ("registered_app__isnull", True),
                        ("tenant_cluster__isnull", False),
                    ),
                    models.Q(
                        ("app_environment__isnull", True),
                        ("kind", "model_endpoint"),
                        ("organization__isnull", False),
                        ("project__isnull", True),
                        ("registered_app__isnull", True),
                        ("tenant_cluster__isnull", False),
                        ("variant", "vllm"),
                    ),
                    _connector="OR",
                ),
                name="msvc_exactly_one_owner_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("organization__isnull", False)),
                fields=("organization", "tenant_cluster", "kind", "name"),
                name="msvc_unique_active_cluster_model",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedserviceattachment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("app_environment__isnull", False),
                    ("deleted_at__isnull", True),
                    ("model_subscription", False),
                ),
                fields=("managed_service", "app_environment"),
                name="msvc_attachment_unique_app_env",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedserviceattachment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("model_subscription", True)),
                fields=("app_environment", "binding_alias"),
                name="msvc_model_alias_unique_app_env",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedserviceattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("model_subscription", False),
                    models.Q(
                        ("agent_environment_spec__isnull", True),
                        ("app_environment__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="msvc_model_subscription_app_env",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedserviceattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("model_subscription", False),
                    ("binding_alias__regex", "^[a-z][a-z0-9_]{0,31}$"),
                    _connector="OR",
                ),
                name="msvc_model_subscription_alias",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedserviceattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(("applied_revision__lte", models.F("desired_revision"))),
                name="msvc_subscription_revision_order",
            ),
        ),
    ]
