# Generated by Django 6.0.5 on 2026-09-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_services", "0028_cluster_model_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedservice",
            name="applied_subscription_revision",
            field=models.PositiveBigIntegerField(default=0, db_default=0),
        ),
    ]
