# Generated by Django 6.0.5 on 2026-09-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_services", "0029_applied_model_subscription_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedservice",
            name="model_ready_auth_revision",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="model_ready_generation",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="model_ready_observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
