# Generated by Django 6.0.5 on 2026-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrolift_services", "0030_shared_model_readiness_observations"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedservice",
            name="model_operation_cluster_guid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="model_operation_provider_guid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="model_ready_provider_guid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
