# Generated by Django 6.0.5 on 2026-09-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_services", "0031_shared_model_operation_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedservice",
            name="model_ready_backend_ref",
            field=models.CharField(blank=True, default="", db_default="", max_length=512),
        ),
    ]
