# Generated by Django 6.0.5 on 2026-10-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_services", "0032_shared_model_observed_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedservice",
            name="provider_cleanup_receipt",
            field=models.JSONField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="managedservice",
            name="provider_placement_identity",
            field=models.JSONField(blank=True, default=None, editable=False, null=True),
        ),
    ]
