# Generated by Django 6.0.5 on 2026-10-04 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_clusters", "0022_reviewed_log_collector"),
        ("astrolift_identity", "0042_team_membership_actions"),
        ("astrolift_lifecycle", "0045_deployment_run_history"),
        ("astrolift_registry", "0042_registeredapp_edge_access"),
        ("astrolift_services", "0036_model_connection_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="managedservice",
            name="msvc_exactly_one_owner_scope",
        ),
        migrations.AlterField(
            model_name="managedservice",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Explicit tenant owner for a cluster-owned model or existing native connection.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cluster_model_deployments",
                to="astrolift_identity.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("app_environment__isnull", False),
                        ("organization__isnull", True),
                        ("project__isnull", True),
                        ("registered_app__isnull", False),
                        ("tenant_cluster__isnull", True),
                    ),
                    models.Q(
                        ("app_environment__isnull", True),
                        ("organization__isnull", True),
                        ("project__isnull", False),
                        ("registered_app__isnull", True),
                        ("tenant_cluster__isnull", False),
                    ),
                    models.Q(
                        ("app_environment__isnull", True),
                        ("kind", "model_endpoint"),
                        ("organization__isnull", False),
                        ("project__isnull", True),
                        ("registered_app__isnull", True),
                        ("tenant_cluster__isnull", False),
                        models.Q(
                            ("variant", "vllm"),
                            models.Q(
                                ("config__existing_connection_only", True),
                                ("config__has_keys", ["existing_connection_only", "model_source"]),
                                ("config__model_source", "bedrock"),
                                ("variant", "bedrock"),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="msvc_exactly_one_owner_scope",
            ),
        ),
    ]
