# Generated by Django 6.0.5 on 2026-10-04 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def refuse_retained_journal_rollback(apps, schema_editor):
    journal = apps.get_model("astrolift_services", "GCPWorkloadIdentityJournal")
    if journal._base_manager.using(schema_editor.connection.alias).exists():
        raise RuntimeError("GCP_IDENTITY_JOURNAL_ROLLBACK_REQUIRES_EMPTY_LEDGER")


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_clusters", "0022_reviewed_log_collector"),
        ("astrolift_identity", "0042_team_membership_actions"),
        ("astrolift_registry", "0042_registeredapp_edge_access"),
        ("astrolift_services", "0037_native_bedrock_connection_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GCPWorkloadIdentityJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("target_snapshot", models.JSONField()),
                ("target_sha256", models.CharField(max_length=64)),
                ("context_sha256", models.CharField(max_length=64)),
                ("ledger", models.JSONField()),
                ("ledger_sha256", models.CharField(max_length=64)),
                ("operation_id", models.UUIDField()),
                ("reservation_nonce", models.UUIDField()),
                ("generation", models.PositiveBigIntegerField(db_default=1, default=1)),
                ("desired_revision", models.PositiveBigIntegerField()),
                (
                    "observed_revision",
                    models.PositiveBigIntegerField(db_default=0, default=0),
                ),
                ("desired_union_sha256", models.CharField(max_length=64)),
                ("authority_reference_sha256", models.CharField(max_length=64)),
                ("workflow_id", models.CharField(max_length=200)),
                ("execution_id", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved"),
                            ("UNSENT", "Unsent"),
                            ("SENT", "Sent"),
                            ("UNKNOWN", "Unknown"),
                            ("OBSERVED", "Observed"),
                        ],
                        db_default="RESERVED",
                        default="RESERVED",
                        max_length=16,
                    ),
                ),
                ("submissions", models.JSONField(db_default={}, default=dict)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "provider_plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.providerplugin",
                    ),
                ),
                (
                    "registered_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_registry.registeredapp",
                    ),
                ),
                (
                    "tenant_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.tenantcluster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("registered_app", "tenant_cluster"),
                        name="gcp_identity_journal_live_owner",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("generation__gte", 1)),
                        name="gcp_identity_journal_generation_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("desired_revision__gte", 1)),
                        name="gcp_identity_journal_revision_positive",
                    ),
                ],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_retained_journal_rollback),
    ]
