# Generated by Django 6.0.5 on 2026-10-04 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def refuse_retained_preparation_rollback(apps, schema_editor):
    for name in ("GCPGKEPreparationJournal", "GCPGKEPreparationOperation"):
        model = apps.get_model("astrolift_services", name)
        if model._base_manager.using(schema_editor.connection.alias).exists():
            raise RuntimeError("GCP_PREPARATION_ROLLBACK_REQUIRES_EMPTY_HISTORY")


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_clusters", "0022_reviewed_log_collector"),
        ("astrolift_identity", "0042_team_membership_actions"),
        ("astrolift_registry", "0042_registeredapp_edge_access"),
        ("astrolift_services", "0038_gcp_workload_identity_journal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GCPGKEPreparationJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("target_snapshot", models.JSONField()),
                ("target_sha256", models.CharField(max_length=64)),
                ("preparation_sha256", models.CharField(max_length=64)),
                ("context_sha256", models.CharField(max_length=64)),
                ("ledger", models.JSONField()),
                ("ledger_sha256", models.CharField(max_length=64)),
                ("operation_id", models.UUIDField()),
                ("reservation_nonce", models.UUIDField()),
                ("generation", models.PositiveBigIntegerField(db_default=1, default=1)),
                ("desired_revision", models.PositiveBigIntegerField()),
                (
                    "prepared_revision",
                    models.PositiveBigIntegerField(db_default=0, default=0),
                ),
                (
                    "observed_revision",
                    models.PositiveBigIntegerField(db_default=0, default=0),
                ),
                ("accepted_union_template_sha256", models.CharField(max_length=64)),
                (
                    "derived_native_union_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("authority_reference_sha256", models.CharField(max_length=64)),
                ("workflow_id", models.CharField(max_length=200)),
                ("execution_id", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved"),
                            ("UNSENT", "Unsent"),
                            ("SENT", "Sent"),
                            ("UNKNOWN", "Unknown"),
                            ("PREPARED", "Prepared"),
                            ("OBSERVED", "Observed"),
                        ],
                        db_default="RESERVED",
                        default="RESERVED",
                        max_length=16,
                    ),
                ),
                ("submissions", models.JSONField(db_default={}, default=dict)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "provider_plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.providerplugin",
                    ),
                ),
                (
                    "registered_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_registry.registeredapp",
                    ),
                ),
                (
                    "tenant_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.tenantcluster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GCPGKEPreparationOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("operation_id", models.UUIDField(unique=True)),
                ("reservation_nonce", models.UUIDField()),
                ("generation", models.PositiveBigIntegerField()),
                ("desired_revision", models.PositiveBigIntegerField()),
                ("accepted_union_template", models.JSONField()),
                ("accepted_union_template_sha256", models.CharField(max_length=64)),
                ("accepted_authority_reference", models.JSONField()),
                ("authority_reference_sha256", models.CharField(max_length=64)),
                ("workflow_id", models.CharField(max_length=200)),
                ("execution_id", models.CharField(max_length=200)),
                (
                    "derived_native_union_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "state",
                    models.CharField(db_default="RESERVED", default="RESERVED", max_length=16),
                ),
                ("submissions", models.JSONField(db_default={}, default=dict)),
                ("ledger", models.JSONField(db_default={}, default=dict)),
                ("ledger_sha256", models.CharField(max_length=64)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_iam_journal_id", models.UUIDField(blank=True, null=True)),
                (
                    "completed_iam_journal_version",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "completed_iam_generation",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "completed_iam_ledger_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="astrolift_services.gcpgkepreparationjournal",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="gcpgkepreparationjournal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("registered_app", "tenant_cluster"),
                name="gcp_preparation_journal_live_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcpgkepreparationjournal",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gte", 1)),
                name="gcp_preparation_generation_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcpgkepreparationjournal",
            constraint=models.CheckConstraint(
                condition=models.Q(("desired_revision__gte", 1)),
                name="gcp_preparation_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcpgkepreparationoperation",
            constraint=models.UniqueConstraint(
                fields=("journal", "generation"),
                name="gcp_preparation_operation_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcpgkepreparationoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gte", 1)),
                name="gcp_preparation_op_generation_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcpgkepreparationoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("desired_revision__gte", 1)),
                name="gcp_preparation_op_revision_positive",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_retained_preparation_rollback),
    ]
