# Generated by Django 6.0.5 on 2026-10-04 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def refuse_retained_source_rollback(apps, schema_editor):
    for name in ("GCPClusterIdentitySource", "GCPAppIdentitySource"):
        if (
            apps.get_model("astrolift_services", name)
            ._base_manager.using(schema_editor.connection.alias)
            .exists()
        ):
            raise RuntimeError("GCP_ORIGINAL_SOURCE_ROLLBACK_REQUIRES_EMPTY_HISTORY")


SOURCE_GUARDS = r"""
CREATE FUNCTION astrolift_original_gcp_source_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'GCP_ORIGINAL_SOURCE_HISTORY_RETAINED' USING ERRCODE = '23514';
    END IF;
    IF TG_TABLE_NAME = 'astrolift_services_gcpclusteridentitysource' THEN
        IF ROW(NEW.guid,NEW.tenant_cluster_id,NEW.provider_plugin_id,NEW.organization_id,
               NEW.original_snapshot,NEW.original_sha256,NEW.admitted_operation_id,NEW.deleted_at)
           IS DISTINCT FROM
           ROW(OLD.guid,OLD.tenant_cluster_id,OLD.provider_plugin_id,OLD.organization_id,
               OLD.original_snapshot,OLD.original_sha256,OLD.admitted_operation_id,OLD.deleted_at) THEN
            RAISE EXCEPTION 'GCP_ORIGINAL_SOURCE_IMMUTABLE' USING ERRCODE = '23514';
        END IF;
    ELSE
        IF ROW(NEW.guid,NEW.organization_id,NEW.registered_app_id,NEW.tenant_cluster_id,
               NEW.provider_plugin_id,NEW.cluster_source_id,NEW.original_snapshot,NEW.original_sha256,
               NEW.operation_id,NEW.reservation_nonce,NEW.workflow_id,NEW.execution_id,
               NEW.authority_reference,NEW.authority_reference_sha256,NEW.accepted_union_sha256,NEW.accepted_native_sha256,
               NEW.create_request_sha256,NEW.account_id,NEW.deleted_at)
           IS DISTINCT FROM
           ROW(OLD.guid,OLD.organization_id,OLD.registered_app_id,OLD.tenant_cluster_id,
               OLD.provider_plugin_id,OLD.cluster_source_id,OLD.original_snapshot,OLD.original_sha256,
               OLD.operation_id,OLD.reservation_nonce,OLD.workflow_id,OLD.execution_id,
               OLD.authority_reference,OLD.authority_reference_sha256,OLD.accepted_union_sha256,OLD.accepted_native_sha256,
               OLD.create_request_sha256,OLD.account_id,OLD.deleted_at)
           OR OLD.unique_id IS NOT NULL AND OLD.unique_id IS DISTINCT FROM NEW.unique_id THEN
            RAISE EXCEPTION 'GCP_ORIGINAL_SOURCE_IMMUTABLE' USING ERRCODE = '23514';
        END IF;
        IF NOT (OLD.state = NEW.state OR
                OLD.state = 'UNSENT' AND NEW.state = 'SENT' OR
                OLD.state = 'SENT' AND NEW.state IN ('UNKNOWN','EVIDENCE') OR
                OLD.state = 'EVIDENCE' AND NEW.state = 'OBSERVED') THEN
            RAISE EXCEPTION 'GCP_ORIGINAL_SOURCE_STATE_REGRESSION' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER astrolift_original_gcp_cluster_guard BEFORE UPDATE OR DELETE
ON astrolift_services_gcpclusteridentitysource FOR EACH ROW EXECUTE FUNCTION astrolift_original_gcp_source_guard();
CREATE TRIGGER astrolift_original_gcp_app_guard BEFORE UPDATE OR DELETE
ON astrolift_services_gcpappidentitysource FOR EACH ROW EXECUTE FUNCTION astrolift_original_gcp_source_guard();
"""
REMOVE_SOURCE_GUARDS = """
DROP TRIGGER astrolift_original_gcp_app_guard ON astrolift_services_gcpappidentitysource;
DROP TRIGGER astrolift_original_gcp_cluster_guard ON astrolift_services_gcpclusteridentitysource;
DROP FUNCTION astrolift_original_gcp_source_guard();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_clusters", "0022_reviewed_log_collector"),
        ("astrolift_identity", "0042_team_membership_actions"),
        ("astrolift_registry", "0042_registeredapp_edge_access"),
        ("astrolift_services", "0039_gcp_gke_preparation_journal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GCPClusterIdentitySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("original_snapshot", models.JSONField()),
                ("original_sha256", models.CharField(max_length=64)),
                ("admitted_operation_id", models.UUIDField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "provider_plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.providerplugin",
                    ),
                ),
                (
                    "tenant_cluster",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.tenantcluster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GCPAppIdentitySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("original_snapshot", models.JSONField()),
                ("original_sha256", models.CharField(max_length=64)),
                ("operation_id", models.UUIDField()),
                ("reservation_nonce", models.UUIDField()),
                ("workflow_id", models.CharField(max_length=200)),
                ("execution_id", models.CharField(max_length=200)),
                ("authority_reference", models.JSONField()),
                ("authority_reference_sha256", models.CharField(max_length=64)),
                ("accepted_union_sha256", models.CharField(max_length=64)),
                ("accepted_native_sha256", models.CharField(max_length=64)),
                ("create_request_sha256", models.CharField(max_length=64)),
                ("account_id", models.CharField(max_length=30)),
                ("unique_id", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("UNSENT", "Unsent"),
                            ("SENT", "Sent"),
                            ("UNKNOWN", "Unknown"),
                            ("EVIDENCE", "Evidence"),
                            ("OBSERVED", "Observed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("evidence_at", models.DateTimeField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "provider_plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.providerplugin",
                    ),
                ),
                (
                    "registered_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_registry.registeredapp",
                    ),
                ),
                (
                    "tenant_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.tenantcluster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cluster_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_services.gcpclusteridentitysource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("registered_app", "tenant_cluster"),
                        name="gcp_original_app_cluster_retained",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("state__in", ["UNSENT", "SENT", "UNKNOWN"]),
                                ("unique_id__isnull", True),
                            ),
                            models.Q(
                                ("state__in", ["EVIDENCE", "OBSERVED"]),
                                ("unique_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="gcp_original_source_evidence_state",
                    ),
                ],
            },
        ),
        migrations.RunSQL(SOURCE_GUARDS, REMOVE_SOURCE_GUARDS),
        migrations.RunPython(migrations.RunPython.noop, refuse_retained_source_rollback),
    ]
