# Generated by Django 6.0.5 on 2026-10-04 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def protect(apps, editor):
    if editor.connection.vendor != "postgresql":
        raise RuntimeError("POSTGRES_APP_APPLY_REQUIRED")
    editor.execute("""
        CREATE FUNCTION gcp_app_apply_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE old_resource jsonb; new_resource jsonb;
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'GCP_APP_APPLY_ERASURE_REFUSED'; END IF;
          IF NEW.deleted_at IS DISTINCT FROM OLD.deleted_at THEN
            RAISE EXCEPTION 'GCP_APP_APPLY_RETIREMENT_REQUIRES_REVIEW';
          END IF;
          IF TG_TABLE_NAME = 'astrolift_services_gcpgkeappapplyjournal' THEN
            IF (to_jsonb(NEW) - ARRAY['version','updated_at','operation_id','nonce','generation','state','ledger','ledger_sha256','observed_at'])
              IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['version','updated_at','operation_id','nonce','generation','state','ledger','ledger_sha256','observed_at']) THEN
              RAISE EXCEPTION 'GCP_APP_APPLY_ORIGINAL_TARGET_IMMUTABLE';
            END IF;
          ELSE
            IF NOT NEW.observations @> OLD.observations THEN
              RAISE EXCEPTION 'GCP_APP_APPLY_ATTEMPT_HISTORY_IMMUTABLE';
            END IF;
            IF (to_jsonb(NEW) - ARRAY['version','updated_at','state','ledger','ledger_sha256','observations','observed_at'])
              IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['version','updated_at','state','ledger','ledger_sha256','observations','observed_at']) THEN
              RAISE EXCEPTION 'GCP_APP_APPLY_ACCEPTED_METADATA_IMMUTABLE';
            END IF;
          END IF;
          FOR old_resource IN SELECT value FROM jsonb_array_elements(OLD.ledger->'resources') LOOP
            SELECT value INTO new_resource FROM jsonb_array_elements(NEW.ledger->'resources')
              WHERE (value->'resource'->>'api_version',value->'resource'->>'kind',value->'resource'->>'namespace',value->'resource'->>'name') =
                (old_resource->'resource'->>'api_version',old_resource->'resource'->>'kind',old_resource->'resource'->>'namespace',old_resource->'resource'->>'name');
            IF new_resource IS NULL OR new_resource->>'uid' IS DISTINCT FROM old_resource->>'uid' OR
               new_resource->>'native_assignments_sha256' IS DISTINCT FROM old_resource->>'native_assignments_sha256' THEN
              RAISE EXCEPTION 'GCP_APP_APPLY_ORIGINAL_UID_IMMUTABLE';
            END IF;
          END LOOP;
          RETURN NEW;
        END $$;
        CREATE TRIGGER gcp_app_apply_journal_protected BEFORE UPDATE OR DELETE ON astrolift_services_gcpgkeappapplyjournal FOR EACH ROW EXECUTE FUNCTION gcp_app_apply_guard();
        CREATE TRIGGER gcp_app_apply_operation_protected BEFORE UPDATE OR DELETE ON astrolift_services_gcpgkeappapplyoperation FOR EACH ROW EXECUTE FUNCTION gcp_app_apply_guard();
    """)


def unprotect(apps, editor):
    for name in ("GCPGKEAppApplyJournal", "GCPGKEAppApplyOperation"):
        if apps.get_model("astrolift_services", name).objects.exists():
            raise RuntimeError("GCP_APP_APPLY_ROLLBACK_REQUIRES_REVIEW")
    editor.execute(
        "DROP TRIGGER gcp_app_apply_journal_protected ON astrolift_services_gcpgkeappapplyjournal; DROP TRIGGER gcp_app_apply_operation_protected ON astrolift_services_gcpgkeappapplyoperation; DROP FUNCTION gcp_app_apply_guard();"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_clusters", "0022_reviewed_log_collector"),
        ("astrolift_identity", "0042_team_membership_actions"),
        ("astrolift_lifecycle", "0047_deployment_execution_receipts"),
        ("astrolift_registry", "0042_registeredapp_edge_access"),
        ("astrolift_services", "0040_gcp_identity_sources"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GCPGKEAppApplyJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("namespace", models.CharField(max_length=63)),
                ("original_target", models.JSONField()),
                ("original_target_sha256", models.CharField(max_length=64)),
                ("operation_id", models.UUIDField()),
                ("nonce", models.UUIDField()),
                ("generation", models.PositiveBigIntegerField(db_default=1, default=1)),
                (
                    "state",
                    models.CharField(db_default="RESERVED", default="RESERVED", max_length=16),
                ),
                ("ledger", models.JSONField()),
                ("ledger_sha256", models.CharField(max_length=64)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "app_environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_lifecycle.appenvironment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "provider_plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.providerplugin",
                    ),
                ),
                (
                    "registered_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_registry.registeredapp",
                    ),
                ),
                (
                    "tenant_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_clusters.tenantcluster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GCPGKEAppApplyOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("operation_id", models.UUIDField(unique=True)),
                ("nonce", models.UUIDField()),
                ("generation", models.PositiveBigIntegerField()),
                ("workflow_id", models.CharField(max_length=200)),
                ("execution_id", models.CharField(max_length=200)),
                ("accepted_plan", models.JSONField()),
                ("accepted_plan_sha256", models.CharField(max_length=64)),
                ("source_fence", models.JSONField()),
                ("prepared_identity", models.JSONField()),
                (
                    "state",
                    models.CharField(db_default="RESERVED", default="RESERVED", max_length=16),
                ),
                ("ledger", models.JSONField()),
                ("ledger_sha256", models.CharField(max_length=64)),
                ("observations", models.JSONField(db_default={}, default=dict)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_lifecycle.deployment",
                    ),
                ),
                (
                    "execution_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_lifecycle.deploymentexecutionreceipt",
                    ),
                ),
                (
                    "identity_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_services.gcpappidentitysource",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="astrolift_services.gcpgkeappapplyjournal",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "preparation_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_services.gcpgkepreparationoperation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="gcpgkeappapplyjournal",
            constraint=models.UniqueConstraint(
                fields=("registered_app", "tenant_cluster", "namespace"),
                name="gcp_app_apply_physical_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcpgkeappapplyjournal",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gte", 1)),
                name="gcp_app_apply_generation_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="gcpgkeappapplyoperation",
            constraint=models.UniqueConstraint(
                fields=("journal", "generation"),
                name="gcp_app_apply_operation_generation",
            ),
        ),
        migrations.RunPython(protect, unprotect),
    ]
