# Generated by Django 6.0.5 on 2026-10-04 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields.uuid_v7


def refuse_retained_acknowledgements(apps, schema_editor):
    model = apps.get_model("astrolift_services", "GCPIdentityAcknowledgement")
    if model._base_manager.using(schema_editor.connection.alias).exists():
        raise RuntimeError("GCP_ACKNOWLEDGEMENT_ROLLBACK_REQUIRES_EMPTY_HISTORY")


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_identity", "0042_team_membership_actions"),
        ("astrolift_lifecycle", "0047_deployment_execution_receipts"),
        ("astrolift_services", "0041_gcp_gke_app_apply_journal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GCPIdentityAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PREPARATION", "Preparation"), ("IAM", "IAM")],
                        max_length=16,
                    ),
                ),
                ("operation_id", models.UUIDField()),
                ("reservation_nonce", models.UUIDField()),
                ("generation", models.PositiveBigIntegerField()),
                ("submission_id", models.UUIDField()),
                ("target_sha256", models.CharField(max_length=64)),
                ("accepted_union_sha256", models.CharField(max_length=64)),
                ("authority_reference_sha256", models.CharField(max_length=64)),
                ("submission_sha256", models.CharField(max_length=64)),
                ("binding_sha256", models.CharField(max_length=64)),
                ("acknowledgement", models.JSONField()),
                ("acknowledgement_sha256", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "execution_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_lifecycle.deploymentexecutionreceipt",
                    ),
                ),
                (
                    "iam_journal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_services.gcpworkloadidentityjournal",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "preparation_journal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_services.gcpgkepreparationjournal",
                    ),
                ),
                (
                    "preparation_operation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_services.gcpgkepreparationoperation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "operation_id", "submission_id"),
                        name="gcp_ack_original_submission_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("iam_journal__isnull", True),
                                ("kind", "PREPARATION"),
                                ("preparation_journal__isnull", False),
                                ("preparation_operation__isnull", False),
                            ),
                            models.Q(
                                ("iam_journal__isnull", False),
                                ("kind", "IAM"),
                                ("preparation_journal__isnull", True),
                                ("preparation_operation__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="gcp_ack_original_journal_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("generation__gte", 1)),
                        name="gcp_ack_generation_positive",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION astrolift_refuse_gcp_acknowledgement_mutation() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'GCP_ACKNOWLEDGEMENT_IMMUTABLE';
            END;
            $$;
            CREATE TRIGGER gcp_acknowledgement_immutable
            BEFORE UPDATE OR DELETE ON astrolift_services_gcpidentityacknowledgement
            FOR EACH ROW EXECUTE FUNCTION astrolift_refuse_gcp_acknowledgement_mutation();
            """,
            reverse_sql="""
            DROP TRIGGER gcp_acknowledgement_immutable ON astrolift_services_gcpidentityacknowledgement;
            DROP FUNCTION astrolift_refuse_gcp_acknowledgement_mutation();
            """,
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=refuse_retained_acknowledgements),
    ]
