# Generated by Django 6.0.5 on 2026-10-04 22:29

import core.fields.uuid_v7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def refuse_retained_email_tests(apps, schema_editor):
    for name in ("EmailDeliveryTest", "EmailDeliveryObservation"):
        model = apps.get_model("astrolift_services", name)
        if model._base_manager.using(schema_editor.connection.alias).exists():
            raise RuntimeError("EMAIL_TEST_ROLLBACK_REQUIRES_EMPTY_HISTORY")


class Migration(migrations.Migration):
    dependencies = [
        ("astrolift_identity", "0041_merge_agent_enforcement_scim_groups"),
        ("astrolift_services", "0035_merge_model_sources"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDeliveryTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("intent_sha256", models.CharField(max_length=64)),
                ("source_sha256", models.CharField(max_length=64)),
                ("sender", models.EmailField(max_length=254)),
                ("recipient", models.EmailField(max_length=254)),
                ("account_id", models.CharField(max_length=12)),
                ("region", models.CharField(max_length=64)),
                ("identity", models.CharField(max_length=254)),
                ("configuration_set", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitting", "Submitting"),
                            ("accepted", "Accepted"),
                            ("unknown", "Unknown"),
                            ("failed", "Failed"),
                            ("suppressed", "Suppressed"),
                            ("delivered", "Delivered"),
                            ("deferred", "Deferred"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitting",
                        max_length=16,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("feedback_topic_arns", models.JSONField(default=list)),
                ("simulator", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "managed_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_services.managedservice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="astrolift_identity.organization",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailDeliveryObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "guid",
                    core.fields.uuid_v7.UUIDv7Field(
                        db_index=True,
                        default=core.fields.uuid_v7.uuid7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("event_sha256", models.CharField(max_length=64, unique=True)),
                ("provider_message_id", models.CharField(max_length=255)),
                ("provider_topic_arn", models.CharField(max_length=512)),
                ("kind", models.CharField(max_length=16)),
                ("occurred_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="astrolift_services.emaildeliverytest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="emaildeliverytest",
            index=models.Index(
                fields=["managed_service", "created_at"],
                name="email_test_service_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliverytest",
            constraint=models.UniqueConstraint(
                fields=("organization", "request_id"),
                name="email_test_intent_org_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildeliverytest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "submitting",
                            "accepted",
                            "unknown",
                            "failed",
                            "suppressed",
                            "delivered",
                            "deferred",
                            "bounced",
                            "complained",
                            "rejected",
                        ],
                    )
                ),
                name="email_test_status_known",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliveryobservation",
            index=models.Index(fields=["delivery_test", "occurred_at"], name="email_test_observed_time"),
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=refuse_retained_email_tests),
    ]
