"""
``manage.py make_perms``

Renders the frontend's permission-slug mirror,
``frontend/lib/permissions/permissions.generated.ts``, from
``core.permissions.Permission``.

The mirror exists because the UI gates on permission slugs and has to
narrow them at compile time; the backend resolver stays the authority on
the yes/no. Before #1490 it was hand-maintained and this command wrote a
Python copy of the enum that nothing imported, so the mirror drifted 29
slugs behind while the generated Python file drifted too and neither
failure was visible. The generator now targets the one file that is
load-bearing, and ``core/tests/test_permission_mirror.py`` fails when it
is stale.
"""

from __future__ import annotations

from pathlib import Path

from django.core.management.base import BaseCommand

from core.permissions import all_permissions

REPO_ROOT = Path(__file__).resolve().parents[4]
OUTPUT = REPO_ROOT / "frontend" / "lib" / "permissions" / "permissions.generated.ts"

HEADER = """/**
 * Astrolift permission slugs — auto-generated by `manage.py make_perms`.
 * Do not edit by hand; run `make perms` after changing
 * `core/permissions.py:Permission`.
 *
 * The backend resolver is the authority on whether a viewer holds a
 * permission. This mirror exists so the UI's `PermissionCheck` unions
 * narrow at compile time instead of accepting any string.
 */

export const ASTROLIFT_PERMISSIONS = [
"""

FOOTER = """] as const;

export type AstroliftPermission = (typeof ASTROLIFT_PERMISSIONS)[number];
"""


def render() -> str:
    """The full text of the generated TypeScript module."""

    slugs = "".join(f'  "{perm.value}",\n' for perm in all_permissions())
    return HEADER + slugs + FOOTER


class Command(BaseCommand):
    help = "Regenerate the frontend permission-slug mirror from the Permission enum"

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help="Fail if the file would change (CI guard).",
        )
        parser.add_argument(
            "--print",
            action="store_true",
            dest="to_stdout",
            help=(
                "Write the module to stdout instead of to a file. The backend "
                "container mounts only ./backend, so `make perms` renders here "
                "and redirects on the host."
            ),
        )
        parser.add_argument("--out", default=str(OUTPUT), help="Output file path.")

    def handle(self, *args, check: bool, to_stdout: bool, out: str, **options):
        new_text = render()

        if to_stdout:
            self.stdout.write(new_text, ending="")
            return

        out_path = Path(out)
        if check:
            current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
            if current != new_text:
                self.stderr.write(f"{out_path.name} is out of date; run `make perms`")
                raise SystemExit(1)
            self.stdout.write(f"{out_path.name} is up to date")
            return

        out_path.write_text(new_text, encoding="utf-8")
        self.stdout.write(f"wrote {out_path}")
