"""
``manage.py make_perms``

Regenerates ``core/permissions_generated.py`` from
``core.permissions.Permission``. The generated file is a frozen
dictionary of ``{permission_value: {"slug", "category", "verb"}}`` that
the role engine and the GraphQL schema introspect at startup.

Keeping the catalog in code (and forbidding additions outside the
enum) means typos surface at import time instead of at request time.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from django.core.management.base import BaseCommand

from core.permissions import all_permissions

HEADER = '''"""
Auto-generated by ``manage.py make_perms`` — do not edit by hand.

The dictionary below is the canonical permission catalog the role
engine consults. The source of truth is ``core.permissions.Permission``;
re-run ``make perms`` after modifying that enum.
"""

from __future__ import annotations

PERMISSIONS: dict[str, dict[str, str]] = {
'''

FOOTER = "}\n"


class Command(BaseCommand):
    help = "Regenerate core/permissions_generated.py from the Permission enum"

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help="Fail if the file would change (CI guard).",
        )
        parser.add_argument(
            "--out",
            default=str(Path(__file__).resolve().parents[3] / "permissions_generated.py"),
            help="Output file path.",
        )

    def handle(self, *args, check: bool, out: str, **options):
        body_parts: list[str] = []
        for perm in all_permissions():
            value = perm.value
            resource, _, verb = value.partition(".")
            body_parts.append(
                textwrap.indent(
                    f'"{value}": {{"slug": "{value}", "resource": "{resource}", "verb": "{verb}"}},',
                    "    ",
                )
            )
        new_text = HEADER + "\n".join(body_parts) + "\n" + FOOTER

        out_path = Path(out)
        if check:
            current = out_path.read_text() if out_path.exists() else ""
            if current != new_text:
                self.stderr.write("permissions_generated.py is out of date; run `make perms`")
                raise SystemExit(1)
            self.stdout.write("permissions_generated.py is up to date")
            return

        out_path.write_text(new_text)
        self.stdout.write(f"wrote {out_path}")
