export const routeLabels: Record<string, string> = {
  dashboard: "Overview",
  apps: "Apps",
  projects: "Projects",
  teams: "Teams",
  members: "Members",
  deployments: "Deployments",
  workflows: "Workflows",
  ops: "Operations",
  downloads: "Downloads",
  console: "Console",
  observability: "Observability",
  events: "Events",
  audit: "Audit",
  clusters: "Clusters",
  domains: "Domains",
  providers: "Providers",
  webhooks: "Webhooks",
  cost: "Cost",
  quotas: "Quotas",
  tokens: "Tokens",
  metrics: "Metrics",
  resources: "Resources",
  docs: "Docs",
  manifest: "Manifest reference",
  drivers: "Driver reference",
  help: "Get help",
  settings: "Settings",
  organization: "Organization",
  general: "General",
  billing: "Billing",
  identity: "Identity",
  policies: "Policies",
  scim: "SCIM",
  new: "Create",
};
