# Generated by Django 6.0.5 on 2026-05-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_drop_metabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalMetabaseChart',
        ),
    ]
