# Generated by Django 6.0.5 on 2026-05-07 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrolift_clusters', '0002_initial'),
        ('astrolift_identity', '0001_initial'),
        ('astrolift_lifecycle', '0001_initial'),
        ('astrolift_operations', '0001_initial'),
        ('astrolift_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='astrolift_operations.workflowrun'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='workload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='astrolift_registry.workload'),
        ),
        migrations.AddField(
            model_name='deploymentlog',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_log_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deploymentlog',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='astrolift_lifecycle.deployment'),
        ),
        migrations.AddField(
            model_name='deploytoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='deploytoken',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deploy_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deploytoken',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deploytoken',
            name='registered_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_tokens', to='astrolift_registry.registeredapp'),
        ),
        migrations.AddField(
            model_name='deploytoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingressrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='ingressrule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingressrule',
            name='managed_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingress_rules', to='astrolift_clusters.manageddomain'),
        ),
        migrations.AddField(
            model_name='ingressrule',
            name='registered_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingress_rules', to='astrolift_registry.registeredapp'),
        ),
        migrations.AddField(
            model_name='ingressrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingressrule',
            name='workload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingress_rules', to='astrolift_registry.workload'),
        ),
        migrations.AddField(
            model_name='previewenvironment',
            name='app_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_environments', to='astrolift_lifecycle.appenvironment'),
        ),
        migrations.AddField(
            model_name='previewenvironment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='previewenvironment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previewenvironment',
            name='registered_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_environments', to='astrolift_registry.registeredapp'),
        ),
        migrations.AddField(
            model_name='previewenvironment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previewenvironment',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_environments', to='astrolift_operations.workflowrun'),
        ),
        migrations.AddField(
            model_name='projectingress',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='projectingress',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectingress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresses', to='astrolift_identity.project'),
        ),
        migrations.AddField(
            model_name='projectingress',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledjobrun',
            name='app_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_runs', to='astrolift_lifecycle.appenvironment'),
        ),
        migrations.AddField(
            model_name='scheduledjobrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='scheduledjobrun',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledjobrun',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledjobrun',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_runs', to='astrolift_registry.workload'),
        ),
        migrations.AddConstraint(
            model_name='appenvironment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('registered_app', 'name'), name='appenv_name_unique_active_per_app'),
        ),
        migrations.AddConstraint(
            model_name='customdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hostname',), name='custom_domain_hostname_unique_active'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['registered_app', 'app_environment', '-created_at'], name='deploy_app_env_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['status'], name='deploy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentlog',
            index=models.Index(fields=['deployment', 'occurred_at'], name='deploylog_deploy_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingressrule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('subdomain', 'managed_domain'), name='ingress_subdomain_unique_active_per_domain'),
        ),
        migrations.AddConstraint(
            model_name='previewenvironment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('registered_app', 'pr_number'), name='preview_pr_unique_active_per_app'),
        ),
    ]
